# Safe Driver Prediction: Systematic Evaluation of Deep Learning and Classical Models

> Objective: Conduct a rigorous and reproducible comparison of TabNet, FT-Transformer, and classical models (XGBoost, LightGBM, CatBoost, Logistic Regression, Random Forest).

## Experimental Protocol (Strictly Enforced)
- Fixed data split: Train/Valid/Test = 60%/20%/20%, and all methods must share the same split
- Random seeds: at least 3 seeds, report mean and standard deviation
- Hyperparameter budget: 10 Optuna trials per method (configurable via global variables)
- Classification metrics: Accuracy, AUC-ROC, F1-score
- Practical evaluation: preprocessing complexity, training cost, inference latency, model size, stability, interpretability

## Notebook Stages
1. Data cleaning and preprocessing
2. Feature engineering
3. Model training and tuning (separate block per model)
4. Prediction and comprehensive analysis

In [ ]:
# ===== 0) Environment Setup and Global Configuration =====
import os
import gc
import time
import json
import random
import warnings
from pathlib import Path
from collections import defaultdict

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler, OrdinalEncoder
from sklearn.metrics import accuracy_score, roc_auc_score, f1_score
from sklearn.inspection import permutation_importance

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

import optuna
optuna.logging.set_verbosity(optuna.logging.INFO)

warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", 200)

# Reproducible experiment configuration
FAST_MODE = False

if FAST_MODE:
    # Fast mode: used for quick pipeline validation with much shorter training time
    SEEDS = [123]
    N_TRIALS = 1
    MAX_TRAIN_ROWS = 80000
    MAX_VALID_ROWS = 30000
    MAX_TRAIN_ROWS_FT = 15000
    MAX_VALID_ROWS_FT = 6000
    TABNET_MAX_EPOCHS = 40
    FT_MAX_EPOCHS = 10
    INFER_REPEAT = 1
    FT_FORCE_CPU = True
else:
    # Production mode: used for final report
    SEEDS = [123, 456, 789]
    N_TRIALS = 5
    MAX_TRAIN_ROWS = None
    MAX_VALID_ROWS = None
    # Explicitly set subsampling for FT-Transformer to avoid OOM, even in non-FAST_MODE
    MAX_TRAIN_ROWS_FT = 15000 # Use a reasonable cap for FT-Transformer
    MAX_VALID_ROWS_FT = 6000  # Use a reasonable cap for FT-Transformer
    TABNET_MAX_EPOCHS = 80
    FT_MAX_EPOCHS = 20
    INFER_REPEAT = 5
    FT_FORCE_CPU = False

VALID_SIZE = 0.20  # 20% of the full dataset
TEST_SIZE = 0.20   # 20% of the full dataset
TARGET_COL = "target"

# Use  suffix consistently to avoid conflicts with FAST_MODE artifacts
DATA_PATH = Path("./dataset.csv")
RESULT_DIR = Path("./artifacts")
RESULT_DIR.mkdir(parents=True, exist_ok=True)
SPLIT_INDEX_PATH = RESULT_DIR / "fixed_split_indices.json"
SUMMARY_PATH = RESULT_DIR / "model_summary.csv"
PRED_PATH = RESULT_DIR / "test_predictions_all_models.csv"
CATBOOST_TRAIN_DIR = Path("./catboost_info")
CATBOOST_TRAIN_DIR.mkdir(parents=True, exist_ok=True)

print("[INFO] Config loaded")
print(f"[INFO] FAST_MODE: {FAST_MODE}")
print(f"[INFO] Seeds: {SEEDS}")
print(f"[INFO] Optuna trials per method: {N_TRIALS}")
print(f"[INFO] Train/Valid cap for tuning: {MAX_TRAIN_ROWS}/{MAX_VALID_ROWS}")
print(f"[INFO] FT Train/Valid cap: {MAX_TRAIN_ROWS_FT}/{MAX_VALID_ROWS_FT}")
print(f"[INFO] FT_FORCE_CPU: {FT_FORCE_CPU}")
print(f"[INFO] Result dir: {RESULT_DIR}")
print(f"[INFO] CatBoost train dir: {CATBOOST_TRAIN_DIR}")

[INFO] Config loaded
[INFO] FAST_MODE: False
[INFO] Seeds: [123, 456, 789]
[INFO] Optuna trials per method: 5
[INFO] Train/Valid cap for tuning: None/None
[INFO] FT Train/Valid cap: 15000/6000
[INFO] FT_FORCE_CPU: False
[INFO] Result dir: artifacts
[INFO] CatBoost train dir: catboost_info

In [ ]:
# Set maximum display rows
pd.set_option('display.max_rows', 500)
# Set maximum display columns
pd.set_option('display.max_columns', None)
# Set column width to avoid truncation
pd.set_option('display.max_colwidth', None)
# Set floating-point display precision
pd.set_option('display.precision', 2)

In [ ]:
import importlib
import subprocess
import sys
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from pytorch_tabnet.tab_model import TabNetClassifier
import torch

USE_GPU = torch.cuda.is_available()
print("[INFO] Core model libraries imported successfully")
print(f"[INFO] CUDA available: {USE_GPU}")
if USE_GPU:
    print(f"[INFO] CUDA device: {torch.cuda.get_device_name(0)}")
else:
    print("[WARN] CUDA is not available. GPU-specific configs will fallback to CPU.")

[INFO] Core model libraries imported successfully
[INFO] CUDA available: True
[INFO] CUDA device: Tesla T4

## 1) Data Cleaning and Preprocessing

Objectives in this stage:
- Correctly handle missing value markers (`-1`)
- Automatically identify feature types (`*_bin`, `*_cat`, and remaining numeric/ordinal features)
- Fix and save train/valid/test split indices so all models use exactly the same split
- Output data quality and missingness logs

In [ ]:
# ===== 1.1 Load Data and Basic Audit =====
assert DATA_PATH.exists(), f"dataset not found: {DATA_PATH}"
df = pd.read_csv(DATA_PATH)
print(f"[INFO] Loaded data shape: {df.shape}")
print(f"[INFO] Columns: {len(df.columns)}")

assert TARGET_COL in df.columns, f"target column '{TARGET_COL}' not found"
print("[INFO] target distribution:")
print(df[TARGET_COL].value_counts(normalize=True).rename("ratio"))

# Treat -1 as missing values (per assignment specification)
feature_cols = [c for c in df.columns if c != TARGET_COL]
df[feature_cols] = df[feature_cols].replace(-1, np.nan)

missing_stats = df[feature_cols].isna().mean().sort_values(ascending=False)
print("[INFO] Top-20 missing ratio columns:")
print(missing_stats.head(20))

print("[INFO] Sample rows:")
display(df.head(5))

[INFO] Loaded data shape: (595212, 59)
[INFO] Columns: 59
[INFO] target distribution:
target
0    0.96
1    0.04
Name: ratio, dtype: float64
[INFO] Top-20 missing ratio columns:
ps_car_03_cat    6.91e-01
ps_car_05_cat    4.48e-01
ps_reg_03        1.81e-01
ps_car_14        7.16e-02
ps_car_07_cat    1.93e-02
ps_ind_05_cat    9.76e-03
ps_car_09_cat    9.56e-04
ps_ind_02_cat    3.63e-04
ps_car_01_cat    1.80e-04
ps_ind_04_cat    1.39e-04
ps_car_02_cat    8.40e-06
ps_car_11        8.40e-06
ps_car_12        1.68e-06
ps_ind_08_bin    0.00e+00
ps_ind_09_bin    0.00e+00
ps_ind_11_bin    0.00e+00
ps_ind_12_bin    0.00e+00
ps_ind_13_bin    0.00e+00
ps_ind_17_bin    0.00e+00
ps_ind_16_bin    0.00e+00
dtype: float64
[INFO] Sample rows:

,id,target,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,ps_ind_10_bin,ps_ind_11_bin,ps_ind_12_bin,ps_ind_13_bin,ps_ind_14,ps_ind_15,ps_ind_16_bin,ps_ind_17_bin,ps_ind_18_bin,ps_reg_01,ps_reg_02,ps_reg_03,ps_car_01_cat,ps_car_02_cat,ps_car_03_cat,ps_car_04_cat,ps_car_05_cat,ps_car_06_cat,ps_car_07_cat,ps_car_08_cat,ps_car_09_cat,ps_car_10_cat,ps_car_11_cat,ps_car_11,ps_car_12,ps_car_13,ps_car_14,ps_car_15,ps_calc_01,ps_calc_02,ps_calc_03,ps_calc_04,ps_calc_05,ps_calc_06,ps_calc_07,ps_calc_08,ps_calc_09,ps_calc_10,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,7,0,2,2.0,5,1.0,0.0,0,1,0,0,0,0,0,0,0,11,0,1,0,0.7,0.2,0.72,10.0,1.0,NaN,0,1.0,4,1.0,0,0.0,1,12,2.0,0.40,0.88,0.37,3.61,0.6,0.5,0.2,3,1,10,1,10,1,5,9,1,5,8,0,1,1,0,0,1
1,9,0,1,1.0,7,0.0,0.0,0,0,1,0,0,0,0,0,0,3,0,0,1,0.8,0.4,0.77,11.0,1.0,NaN,0,NaN,11,1.0,1,2.0,1,19,3.0,0.32,0.62,0.39,2.45,0.3,0.1,0.3,2,1,9,5,8,1,7,3,1,1,9,0,1,1,0,1,0
2,13,0,5,4.0,9,1.0,0.0,0,0,1,0,0,0,0,0,0,12,1,0,0,0.0,0.0,NaN,7.0,1.0,NaN,0,NaN,14,1.0,1,2.0,1,60,1.0,0.32,0.64,0.35,3.32,0.5,0.7,0.1,2,2,9,1,8,2,7,4,2,7,7,0,1,1,0,1,0
3,16,0,0,1.0,2,0.0,0.0,1,0,0,0,0,0,0,0,0,8,1,0,0,0.9,0.2,0.58,7.0,1.0,0.0,0,1.0,11,1.0,1,3.0,1,104,1.0,0.37,0.54,0.29,2.00,0.6,0.9,0.1,2,4,7,1,8,4,2,2,2,4,9,0,0,0,0,0,0
4,17,0,0,2.0,0,1.0,0.0,1,0,0,0,0,0,0,0,0,9,1,0,0,0.7,0.6,0.84,11.0,1.0,NaN,0,NaN,14,1.0,1,2.0,1,82,3.0,0.32,0.57,0.37,2.00,0.4,0.6,0.0,2,2,6,3,10,2,12,3,1,1,3,0,0,0,1,1,0

In [ ]:
# ===== 1.2 Automatically Identify Feature Types =====
all_features = [c for c in df.columns if c != TARGET_COL]

bin_cols = [c for c in all_features if c.endswith("_bin")]
cat_cols = [c for c in all_features if c.endswith("_cat")]
num_cols = [c for c in all_features if c not in set(bin_cols + cat_cols)]

# Count prefix groups based on assignment hint (ind/reg/car/calc)
def get_prefix(col):
    parts = col.split("_")
    return parts[1] if len(parts) > 1 else "unknown"

prefix_group = pd.Series([get_prefix(c) for c in all_features]).value_counts()

print(f"[INFO] Binary columns: {len(bin_cols)}")
print(f"[INFO] Categorical columns: {len(cat_cols)}")
print(f"[INFO] Numeric/Ordinal columns: {len(num_cols)}")
print("[INFO] Prefix group counts:")
print(prefix_group)

# Check high-cardinality categorical features (for preprocessing complexity analysis)
high_cardinality = []
for c in cat_cols:
    n_unique = df[c].nunique(dropna=True)
    if n_unique >= 20:
        high_cardinality.append((c, n_unique))
high_cardinality = sorted(high_cardinality, key=lambda x: x[1], reverse=True)

print(f"[INFO] High-cardinality categorical features (>=20 unique): {len(high_cardinality)}")
print(high_cardinality[:20])

[INFO] Binary columns: 17
[INFO] Categorical columns: 14
[INFO] Numeric/Ordinal columns: 27
[INFO] Prefix group counts:
calc       20
ind        18
car        16
reg         3
unknown     1
Name: count, dtype: int64
[INFO] High-cardinality categorical features (>=20 unique): 1
[('ps_car_11_cat', 104)]

In [ ]:
# ===== 1.3 Fixed 60/20/20 Split (Stratified) =====
X = df.drop(columns=[TARGET_COL]).copy()
y = df[TARGET_COL].astype(int).copy()

# Step 1: split out test=20%
X_train_valid, X_test, y_train_valid, y_test = train_test_split(
    X, y, test_size=TEST_SIZE, random_state=SEEDS[0], stratify=y
)

# Step 2: split valid=20% of total from the remaining 80%
valid_ratio_in_train_valid = VALID_SIZE / (1 - TEST_SIZE)  # 0.2/0.8 = 0.25
X_train, X_valid, y_train, y_valid = train_test_split(
    X_train_valid, y_train_valid,
    test_size=valid_ratio_in_train_valid,
    random_state=SEEDS[0],
    stratify=y_train_valid
)

print("[INFO] Split summary:")
print(f"Train: {X_train.shape}, ratio={len(X_train)/len(X):.3f}")
print(f"Valid: {X_valid.shape}, ratio={len(X_valid)/len(X):.3f}")
print(f"Test : {X_test.shape}, ratio={len(X_test)/len(X):.3f}")

# Save indices for strict reproducibility
split_idx = {
    "train_index": X_train.index.tolist(),
    "valid_index": X_valid.index.tolist(),
    "test_index": X_test.index.tolist(),
}
with open(SPLIT_INDEX_PATH, "w", encoding="utf-8") as f:
    json.dump(split_idx, f, ensure_ascii=False, indent=2)
print(f"[INFO] Saved split indices to {SPLIT_INDEX_PATH}")

[INFO] Split summary:
Train: (357126, 58), ratio=0.600
Valid: (119043, 58), ratio=0.200
Test : (119043, 58), ratio=0.200
[INFO] Saved split indices to artifacts/fixed_split_indices.json

## 2) Feature Engineering and Shared Utilities

Objectives in this stage:
- Build reusable preprocessing pipelines for different model families
- Provide shared utilities for evaluation, latency benchmarking, model size estimation, and result aggregation
- Reduce duplicated code in later model-specific training blocks

In [ ]:
# ===== 2.1 Shared Preprocessors and Evaluation Utilities =====
def build_sklearn_preprocessor(model_family: str):
    """
    model_family: 'linear' | 'tree'
    linear: numeric standardization + categorical one-hot
    tree  : numeric median imputation + categorical ordinal encoding
    """
    if model_family == "linear":
        num_pipe = Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
        ])
        cat_pipe = Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=True)),
        ])
    elif model_family == "tree":
        num_pipe = Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
        ])
        cat_pipe = Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("ordinal", OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1)),
        ])
    else:
        raise ValueError(f"unknown model_family={model_family}")

    preprocessor = ColumnTransformer([
        ("num", num_pipe, num_cols + bin_cols),
        ("cat", cat_pipe, cat_cols),
    ], remainder="drop")
    return preprocessor


def evaluate_predictions(y_true, y_prob, threshold=0.5):
    y_pred = (y_prob >= threshold).astype(int)
    return {
        "accuracy": float(accuracy_score(y_true, y_pred)),
        "auc_roc": float(roc_auc_score(y_true, y_prob)),
        "f1": float(f1_score(y_true, y_pred)),
    }


def benchmark_inference(model_predict_proba_fn, X_input, n_repeat=INFER_REPEAT, batch_size=2048):
    # Record per-sample inference latency (milliseconds)
    n = len(X_input)
    idx = np.arange(n)
    latencies = []
    for _ in range(n_repeat):
        np.random.shuffle(idx)
        t0 = time.perf_counter()
        for i in range(0, n, batch_size):
            batch_idx = idx[i:i+batch_size]
            _ = model_predict_proba_fn(X_input.iloc[batch_idx])
        t1 = time.perf_counter()
        elapsed = (t1 - t0) / n * 1000.0
        latencies.append(elapsed)
    return float(np.mean(latencies)), float(np.std(latencies))


def estimate_model_size_mb(model_obj):
    # Estimate model size via temporary serialization
    import tempfile
    import joblib
    with tempfile.NamedTemporaryFile(suffix=".pkl", delete=False) as tmp:
        joblib.dump(model_obj, tmp.name)
        size_mb = os.path.getsize(tmp.name) / (1024 * 1024)
    try:
        os.remove(tmp.name)
    except Exception:
        pass
    return float(size_mb)


def print_seed_metrics(model_name, seed_results):
    print(f"\n[SUMMARY] {model_name}")
    for m in ["accuracy", "auc_roc", "f1", "train_seconds", "infer_ms_per_sample", "model_size_mb"]:
        vals = [r[m] for r in seed_results]
        print(f"  - {m:20s}: mean={np.mean(vals):.6f}, std={np.std(vals):.6f}")

In [ ]:
# ===== 2.2 Result Containers, Logging Helpers, and Checkpoint Resume Utilities =====
all_results = {}
best_models = {}
best_preprocessors = {}

def optuna_log_callback(study, trial):
    print(
        f"[Optuna] Trial {trial.number:03d} | value={trial.value:.6f} | "
        f"params={trial.params}"
    )

# ===== checkpoint / resume =====
CKPT_ROOT = RESULT_DIR / "checkpoints"
CKPT_ROOT.mkdir(parents=True, exist_ok=True)

def _safe_model_name(model_name: str) -> str:
    return "".join(ch if ch.isalnum() or ch in ["_", "-"] else "_" for ch in model_name)

def get_seed_ckpt_paths(model_name: str, seed: int):
    seed_dir = CKPT_ROOT / f"{_safe_model_name(model_name)}_seed{seed}"
    seed_dir.mkdir(parents=True, exist_ok=True)
    return {
        "dir": seed_dir,
        "meta": seed_dir / "meta.json",
        "model_joblib": seed_dir / "model.joblib",
        "bundle_joblib": seed_dir / "bundle.joblib",
        "tabnet_zip": seed_dir / "tabnet_model.zip",
        "ft_state": seed_dir / "ft_state.pt",
    }

def _json_default(obj):
    if isinstance(obj, (np.integer,)):
        return int(obj)
    if isinstance(obj, (np.floating,)):
        return float(obj)
    if isinstance(obj, (np.bool_,)):
        return bool(obj)
    if isinstance(obj, Path):
        return str(obj)
    raise TypeError(f"Object of type {type(obj)} is not JSON serializable")

def save_seed_meta(model_name: str, seed: int, payload: dict):
    paths = get_seed_ckpt_paths(model_name, seed)
    with open(paths["meta"], "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2, default=_json_default)

def load_seed_meta(model_name: str, seed: int):
    paths = get_seed_ckpt_paths(model_name, seed)
    if not paths["meta"].exists():
        return None
    with open(paths["meta"], "r", encoding="utf-8") as f:
        return json.load(f)

def compact_deep_bundle(bundle: dict):
    return {
        "num_imputer": bundle["num_imputer"],
        "cat_encoder": bundle["cat_encoder"],
        "cat_dims": bundle["cat_dims"],
        "n_num": bundle["n_num"],
        "n_cat": bundle["n_cat"],
    }

def build_deep_infer_bundle_from_compact(compact_bundle: dict, Xte_df: pd.DataFrame):
    numbin_cols = num_cols + bin_cols
    Xte_num = compact_bundle["num_imputer"].transform(Xte_df[numbin_cols]).astype(np.float32)

    if len(cat_cols) > 0 and compact_bundle.get("cat_encoder") is not None:
        te_cat = Xte_df[cat_cols].astype("string").fillna("MISSING")
        Xte_cat = compact_bundle["cat_encoder"].transform(te_cat).astype(np.int64) + 1
    else:
        Xte_cat = np.zeros((len(Xte_df), 0), dtype=np.int64)

    return {
        "Xte_num": Xte_num,
        "Xte_cat": Xte_cat,
        "cat_dims": compact_bundle["cat_dims"],
        "n_num": compact_bundle["n_num"],
        "n_cat": compact_bundle["n_cat"],
    }

print("[INFO] Utilities + checkpoint manager ready")
print(f"[INFO] Checkpoint root: {CKPT_ROOT}")

[INFO] Utilities + checkpoint manager ready
[INFO] Checkpoint root: artifacts/checkpoints

## 3) Model Training and Tuning (Separate Block per Model)

Notes:
- Each model uses the same Optuna tuning budget (`N_TRIALS`)
- Each model is trained with 3 random seeds on the same data split
- Outputs: validation logs per seed, test metrics, training time, inference latency, and model size

In [ ]:
# ===== 2.3 Unified Tuning and Evaluation Runner for Classical Models (Checkpoint Resume Enabled) =====
def run_classical_experiment(
    model_name,
    model_builder_fn,
    param_suggester_fn,
    model_family,
    use_native_cat=False,
    n_trials=N_TRIALS,
    seeds=SEEDS,
    verbose=True,
    ):
    import joblib

    seed_results = []

    for seed in seeds:
        paths = get_seed_ckpt_paths(model_name, seed)
        cached_meta = load_seed_meta(model_name, seed)
        if cached_meta is not None and paths["model_joblib"].exists():
            cached_metrics = cached_meta.get("metrics", {})
            if "seed" not in cached_metrics:
                cached_metrics["seed"] = int(seed)
            print(f"[RESUME] {model_name} seed={seed} loaded from checkpoint, skip training")
            seed_results.append(cached_metrics)
            continue

        print(f"\n{'='*20} {model_name} | seed={seed} {'='*20}")
        np.random.seed(seed)
        random.seed(seed)

        # FAST_MODE: use subsampling during tuning to reduce training time
        X_train_seed = X_train
        y_train_seed = y_train
        X_valid_seed = X_valid
        y_valid_seed = y_valid

        if MAX_TRAIN_ROWS is not None and len(X_train_seed) > MAX_TRAIN_ROWS:
            idx = X_train_seed.sample(n=MAX_TRAIN_ROWS, random_state=seed).index
            X_train_seed = X_train_seed.loc[idx]
            y_train_seed = y_train_seed.loc[idx]

        if MAX_VALID_ROWS is not None and len(X_valid_seed) > MAX_VALID_ROWS:
            idx = X_valid_seed.sample(n=MAX_VALID_ROWS, random_state=seed).index
            X_valid_seed = X_valid_seed.loc[idx]
            y_valid_seed = y_valid_seed.loc[idx]

        if use_native_cat:
            # Path for CatBoost native categorical support
            Xtr = X_train_seed.copy()
            Xva = X_valid_seed.copy()
            Xte = X_test.copy()

            for c in cat_cols:
                Xtr[c] = Xtr[c].astype("string").fillna("MISSING")
                Xva[c] = Xva[c].astype("string").fillna("MISSING")
                Xte[c] = Xte[c].astype("string").fillna("MISSING")
        else:
            preprocessor = build_sklearn_preprocessor(model_family)
            Xtr = preprocessor.fit_transform(X_train_seed)
            Xva = preprocessor.transform(X_valid_seed)
            Xte = preprocessor.transform(X_test)

        def objective(trial):
            params = param_suggester_fn(trial)
            model = model_builder_fn(params, seed)

            t0 = time.perf_counter()
            if use_native_cat:
                model.fit(
                    Xtr, y_train_seed,
                    eval_set=(Xva, y_valid_seed),
                    cat_features=cat_cols,
                    use_best_model=True,
                    verbose=100
                )
                yva_prob = model.predict_proba(Xva)[:, 1]
            else:
                model.fit(Xtr, y_train_seed)
                yva_prob = model.predict_proba(Xva)[:, 1]
            t1 = time.perf_counter()

            auc = roc_auc_score(y_valid_seed, yva_prob)
            if verbose:
                print(
                    f"[{model_name}|seed={seed}] trial={trial.number} auc={auc:.6f} "
                    f"train_time={t1-t0:.2f}s"
                )
            return auc

        study = optuna.create_study(direction="maximize")
        study.optimize(objective, n_trials=n_trials, callbacks=[optuna_log_callback])

        best_params = study.best_trial.params
        print(f"[BEST] {model_name} seed={seed} best_auc(valid)={study.best_value:.6f}")
        print(f"[BEST] params={best_params}")

        final_model = model_builder_fn(best_params, seed)
        t0 = time.perf_counter()
        if use_native_cat:
            final_model.fit(
                Xtr, y_train_seed,
                eval_set=(Xva, y_valid_seed),
                cat_features=cat_cols,
                use_best_model=True,
                verbose=100
            )
            y_prob_test = final_model.predict_proba(Xte)[:, 1]
            infer_mean, infer_std = benchmark_inference(
                lambda x: final_model.predict_proba(x)[:, 1], Xte
            )
            model_size = estimate_model_size_mb(final_model)
            preprocess_obj = None
        else:
            final_model.fit(Xtr, y_train_seed)
            y_prob_test = final_model.predict_proba(Xte)[:, 1]
            infer_mean, infer_std = benchmark_inference(
                lambda x: final_model.predict_proba(preprocessor.transform(x))[:, 1],
                X_test
            )
            try:
                model_size = estimate_model_size_mb((preprocessor, final_model))
            except Exception:
                model_size = np.nan
            preprocess_obj = preprocessor
        t1 = time.perf_counter()

        m = evaluate_predictions(y_test, y_prob_test)
        m["seed"] = int(seed)
        m["train_seconds"] = float(t1 - t0)
        m["infer_ms_per_sample"] = float(infer_mean)
        m["infer_ms_per_sample_std"] = float(infer_std)
        m["model_size_mb"] = float(model_size)
        m["best_valid_auc"] = float(study.best_value)
        m["best_params"] = best_params
        seed_results.append(m)

        # Save checkpoint per seed to support resume after interruption
        joblib.dump({"model": final_model, "preprocessor": preprocess_obj}, paths["model_joblib"])
        save_seed_meta(
            model_name,
            seed,
            {
                "model_name": model_name,
                "seed": int(seed),
                "format": "joblib",
                "metrics": m,
                "best_params": best_params,
            },
        )
        print(f"[CKPT] Saved {model_name} seed={seed} -> {paths['dir']}")

        gc.collect()

    if len(seed_results) == 0:
        raise RuntimeError(f"No seed results found for model {model_name}")

    all_results[model_name] = seed_results

    # Deserialize from best-seed checkpoint so post-restart prediction can continue
    best_seed = int(max(seed_results, key=lambda r: r["auc_roc"])["seed"])
    best_paths = get_seed_ckpt_paths(model_name, best_seed)
    best_pack = joblib.load(best_paths["model_joblib"])

    best_models[model_name] = best_pack["model"]
    best_preprocessors[model_name] = best_pack["preprocessor"]

    print(f"[RESUME] {model_name} best seed selected: {best_seed}")
    print_seed_metrics(model_name, seed_results)

In [ ]:
# ===== 3.1 Logistic Regression =====
def logistic_builder(params, seed):
    return LogisticRegression(
        C=params["C"],
        penalty=params["penalty"],
        solver="saga",
        max_iter=3000,
        class_weight="balanced",
        random_state=seed,
        n_jobs=-1,
    )

def logistic_suggester(trial):
    return {
        "C": trial.suggest_float("C", 1e-3, 30.0, log=True),
        "penalty": trial.suggest_categorical("penalty", ["l1", "l2"]),
    }

run_classical_experiment(
    model_name="LogisticRegression",
    model_builder_fn=logistic_builder,
    param_suggester_fn=logistic_suggester,
    model_family="linear",
    use_native_cat=False,
    n_trials=N_TRIALS,
    seeds=SEEDS,
    verbose=True,
    )

==================== LogisticRegression | seed=123 ====================

[I 2026-04-05 04:01:12,974] A new study created in memory with name: no-name-6a24216a-23b7-4254-966f-a9507212bdd3
[I 2026-04-05 04:08:54,962] Trial 0 finished with value: 0.622586929039531 and parameters: {'C': 0.3450922232156312, 'penalty': 'l2'}. Best is trial 0 with value: 0.622586929039531.

[LogisticRegression|seed=123] trial=0 auc=0.622587 train_time=461.96s
[Optuna] Trial 000 | value=0.622587 | params={'C': 0.3450922232156312, 'penalty': 'l2'}

[I 2026-04-05 04:24:57,035] Trial 1 finished with value: 0.6227870935335877 and parameters: {'C': 0.3015430440745738, 'penalty': 'l1'}. Best is trial 1 with value: 0.6227870935335877.

[LogisticRegression|seed=123] trial=1 auc=0.622787 train_time=962.04s
[Optuna] Trial 001 | value=0.622787 | params={'C': 0.3015430440745738, 'penalty': 'l1'}

[I 2026-04-05 04:31:57,375] Trial 2 finished with value: 0.6225366237009743 and parameters: {'C': 2.3354215643806397, 'penalty': 'l2'}. Best is trial 1 with value: 0.6227870935335877.

[LogisticRegression|seed=123] trial=2 auc=0.622537 train_time=420.31s
[Optuna] Trial 002 | value=0.622537 | params={'C': 2.3354215643806397, 'penalty': 'l2'}

[I 2026-04-05 04:43:00,176] Trial 3 finished with value: 0.6227054561085409 and parameters: {'C': 0.4873959127218885, 'penalty': 'l1'}. Best is trial 1 with value: 0.6227870935335877.

[LogisticRegression|seed=123] trial=3 auc=0.622705 train_time=662.77s
[Optuna] Trial 003 | value=0.622705 | params={'C': 0.4873959127218885, 'penalty': 'l1'}

[I 2026-04-05 04:48:59,950] Trial 4 finished with value: 0.6237931219443681 and parameters: {'C': 0.004379040283932205, 'penalty': 'l1'}. Best is trial 4 with value: 0.6237931219443681.

[LogisticRegression|seed=123] trial=4 auc=0.623793 train_time=359.74s
[Optuna] Trial 004 | value=0.623793 | params={'C': 0.004379040283932205, 'penalty': 'l1'}
[BEST] LogisticRegression seed=123 best_auc(valid)=0.623793
[BEST] params={'C': 0.004379040283932205, 'penalty': 'l1'}
[CKPT] Saved LogisticRegression seed=123 -> artifacts/checkpoints/LogisticRegression_seed123

==================== LogisticRegression | seed=456 ====================

[I 2026-04-05 04:54:54,189] A new study created in memory with name: no-name-410d910b-e282-46c2-a6b8-5aaff32b44b6
[I 2026-04-05 05:03:26,700] Trial 0 finished with value: 0.6226642285157045 and parameters: {'C': 0.6582055830831948, 'penalty': 'l1'}. Best is trial 0 with value: 0.6226642285157045.

[LogisticRegression|seed=456] trial=0 auc=0.622664 train_time=512.48s
[Optuna] Trial 000 | value=0.622664 | params={'C': 0.6582055830831948, 'penalty': 'l1'}

[I 2026-04-05 05:16:39,329] Trial 1 finished with value: 0.6229043587999611 and parameters: {'C': 0.18185120483322575, 'penalty': 'l1'}. Best is trial 1 with value: 0.6229043587999611.

[LogisticRegression|seed=456] trial=1 auc=0.622904 train_time=792.60s
[Optuna] Trial 001 | value=0.622904 | params={'C': 0.18185120483322575, 'penalty': 'l1'}

[I 2026-04-05 05:29:28,765] Trial 2 finished with value: 0.6231878806283911 and parameters: {'C': 0.09415313567737851, 'penalty': 'l1'}. Best is trial 2 with value: 0.6231878806283911.

[LogisticRegression|seed=456] trial=2 auc=0.623188 train_time=769.41s
[Optuna] Trial 002 | value=0.623188 | params={'C': 0.09415313567737851, 'penalty': 'l1'}

[I 2026-04-05 06:03:01,505] Trial 3 finished with value: 0.6237026840487025 and parameters: {'C': 0.04531995730789292, 'penalty': 'l1'}. Best is trial 3 with value: 0.6237026840487025.

[LogisticRegression|seed=456] trial=3 auc=0.623703 train_time=2012.71s
[Optuna] Trial 003 | value=0.623703 | params={'C': 0.04531995730789292, 'penalty': 'l1'}

[I 2026-04-05 06:11:51,986] Trial 4 finished with value: 0.6225824403976674 and parameters: {'C': 1.8166618867901667, 'penalty': 'l1'}. Best is trial 3 with value: 0.6237026840487025.

[LogisticRegression|seed=456] trial=4 auc=0.622582 train_time=530.46s
[Optuna] Trial 004 | value=0.622582 | params={'C': 1.8166618867901667, 'penalty': 'l1'}
[BEST] LogisticRegression seed=456 best_auc(valid)=0.623703
[BEST] params={'C': 0.04531995730789292, 'penalty': 'l1'}
[CKPT] Saved LogisticRegression seed=456 -> artifacts/checkpoints/LogisticRegression_seed456

==================== LogisticRegression | seed=789 ====================

[I 2026-04-05 06:45:38,126] A new study created in memory with name: no-name-c8173c6f-5dd5-433f-8925-91531089fc9c
[I 2026-04-05 06:53:57,600] Trial 0 finished with value: 0.6225375640252321 and parameters: {'C': 3.8275488260526274, 'penalty': 'l2'}. Best is trial 0 with value: 0.6225375640252321.

[LogisticRegression|seed=789] trial=0 auc=0.622538 train_time=499.45s
[Optuna] Trial 000 | value=0.622538 | params={'C': 3.8275488260526274, 'penalty': 'l2'}

[I 2026-04-05 07:02:23,924] Trial 1 finished with value: 0.6225430171022317 and parameters: {'C': 1.9400467348669546, 'penalty': 'l2'}. Best is trial 1 with value: 0.6225430171022317.

[LogisticRegression|seed=789] trial=1 auc=0.622543 train_time=506.30s
[Optuna] Trial 001 | value=0.622543 | params={'C': 1.9400467348669546, 'penalty': 'l2'}

[I 2026-04-05 07:03:34,861] Trial 2 finished with value: 0.6233117100814108 and parameters: {'C': 0.014376195292490474, 'penalty': 'l2'}. Best is trial 2 with value: 0.6233117100814108.

[LogisticRegression|seed=789] trial=2 auc=0.623312 train_time=70.91s
[Optuna] Trial 002 | value=0.623312 | params={'C': 0.014376195292490474, 'penalty': 'l2'}

[I 2026-04-05 07:17:03,749] Trial 3 finished with value: 0.6226100252518052 and parameters: {'C': 1.1568615941717317, 'penalty': 'l1'}. Best is trial 2 with value: 0.6233117100814108.

[LogisticRegression|seed=789] trial=3 auc=0.622610 train_time=808.86s
[Optuna] Trial 003 | value=0.622610 | params={'C': 1.1568615941717317, 'penalty': 'l1'}

[I 2026-04-05 07:19:19,302] Trial 4 finished with value: 0.6229571053649566 and parameters: {'C': 0.03420554062243378, 'penalty': 'l2'}. Best is trial 2 with value: 0.6233117100814108.

[LogisticRegression|seed=789] trial=4 auc=0.622957 train_time=135.53s
[Optuna] Trial 004 | value=0.622957 | params={'C': 0.03420554062243378, 'penalty': 'l2'}
[BEST] LogisticRegression seed=789 best_auc(valid)=0.623312
[BEST] params={'C': 0.014376195292490474, 'penalty': 'l2'}
[CKPT] Saved LogisticRegression seed=789 -> artifacts/checkpoints/LogisticRegression_seed789
[RESUME] LogisticRegression best seed selected: 456

[SUMMARY] LogisticRegression
  - accuracy            : mean=0.620059, std=0.000699
  - auc_roc             : mean=0.625624, std=0.001916
  - f1                  : mean=0.095956, std=0.000652
  - train_seconds       : mean=816.116632, std=859.861846
  - infer_ms_per_sample : mean=0.006752, std=0.000122
  - model_size_mb       : mean=0.011026, std=0.000000

In [ ]:
# ===== 3.2 Random Forest =====
def rf_builder(params, seed):
    return RandomForestClassifier(
        n_estimators=params["n_estimators"],
        max_depth=params["max_depth"],
        min_samples_split=params["min_samples_split"],
        min_samples_leaf=params["min_samples_leaf"],
        max_features=params["max_features"],
        class_weight="balanced_subsample",
        n_jobs=-1,
        random_state=seed,
    )

def rf_suggester(trial):
    return {
        "n_estimators": trial.suggest_int("n_estimators", 200, 1200, step=100),
        "max_depth": trial.suggest_int("max_depth", 4, 24),
        "min_samples_split": trial.suggest_int("min_samples_split", 2, 20),
        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 10),
        "max_features": trial.suggest_categorical("max_features", ["sqrt", "log2", None]),
    }

run_classical_experiment(
    model_name="RandomForest",
    model_builder_fn=rf_builder,
    param_suggester_fn=rf_suggester,
    model_family="tree",
    use_native_cat=False,
    n_trials=N_TRIALS,
    seeds=SEEDS,
    verbose=True,
    )

==================== RandomForest | seed=123 ====================

[I 2026-04-05 07:20:38,256] A new study created in memory with name: no-name-cf304048-82f1-4376-ac31-4ac7747073a1
[I 2026-04-05 07:21:25,685] Trial 0 finished with value: 0.5962209280270669 and parameters: {'n_estimators': 300, 'max_depth': 14, 'min_samples_split': 15, 'min_samples_leaf': 7, 'max_features': 'log2'}. Best is trial 0 with value: 0.5962209280270669.

[RandomForest|seed=123] trial=0 auc=0.596221 train_time=47.40s
[Optuna] Trial 000 | value=0.596221 | params={'n_estimators': 300, 'max_depth': 14, 'min_samples_split': 15, 'min_samples_leaf': 7, 'max_features': 'log2'}

[I 2026-04-05 07:22:05,538] Trial 1 finished with value: 0.614548440538925 and parameters: {'n_estimators': 400, 'max_depth': 4, 'min_samples_split': 12, 'min_samples_leaf': 7, 'max_features': 'sqrt'}. Best is trial 1 with value: 0.614548440538925.

[RandomForest|seed=123] trial=1 auc=0.614548 train_time=39.82s
[Optuna] Trial 001 | value=0.614548 | params={'n_estimators': 400, 'max_depth': 4, 'min_samples_split': 12, 'min_samples_leaf': 7, 'max_features': 'sqrt'}

[I 2026-04-05 07:24:41,341] Trial 2 finished with value: 0.6007986093552588 and parameters: {'n_estimators': 900, 'max_depth': 20, 'min_samples_split': 12, 'min_samples_leaf': 8, 'max_features': 'log2'}. Best is trial 1 with value: 0.614548440538925.

[RandomForest|seed=123] trial=2 auc=0.600799 train_time=155.76s
[Optuna] Trial 002 | value=0.600799 | params={'n_estimators': 900, 'max_depth': 20, 'min_samples_split': 12, 'min_samples_leaf': 8, 'max_features': 'log2'}

[I 2026-04-05 07:25:42,946] Trial 3 finished with value: 0.6193979599657188 and parameters: {'n_estimators': 600, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 7, 'max_features': 'log2'}. Best is trial 3 with value: 0.6193979599657188.

[RandomForest|seed=123] trial=3 auc=0.619398 train_time=61.57s
[Optuna] Trial 003 | value=0.619398 | params={'n_estimators': 600, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 7, 'max_features': 'log2'}

[I 2026-04-05 07:26:32,554] Trial 4 finished with value: 0.6128341912412509 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 3 with value: 0.6193979599657188.

[RandomForest|seed=123] trial=4 auc=0.612834 train_time=49.58s
[Optuna] Trial 004 | value=0.612834 | params={'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'sqrt'}
[BEST] RandomForest seed=123 best_auc(valid)=0.619398
[BEST] params={'n_estimators': 600, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 7, 'max_features': 'log2'}
[CKPT] Saved RandomForest seed=123 -> artifacts/checkpoints/RandomForest_seed123

==================== RandomForest | seed=456 ====================

[I 2026-04-05 07:28:32,597] A new study created in memory with name: no-name-c67d1d09-3fb8-473b-93db-366f7c506c73
[I 2026-04-05 07:39:34,657] Trial 0 finished with value: 0.5968620463301137 and parameters: {'n_estimators': 700, 'max_depth': 12, 'min_samples_split': 17, 'min_samples_leaf': 8, 'max_features': None}. Best is trial 0 with value: 0.5968620463301137.

[RandomForest|seed=456] trial=0 auc=0.596862 train_time=662.03s
[Optuna] Trial 000 | value=0.596862 | params={'n_estimators': 700, 'max_depth': 12, 'min_samples_split': 17, 'min_samples_leaf': 8, 'max_features': None}

[I 2026-04-05 07:41:50,982] Trial 1 finished with value: 0.6181046223093587 and parameters: {'n_estimators': 1200, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 1 with value: 0.6181046223093587.

[RandomForest|seed=456] trial=1 auc=0.618105 train_time=136.29s
[Optuna] Trial 001 | value=0.618105 | params={'n_estimators': 1200, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 8, 'max_features': 'sqrt'}

[I 2026-04-05 07:43:44,733] Trial 2 finished with value: 0.6193297985124616 and parameters: {'n_estimators': 800, 'max_depth': 10, 'min_samples_split': 17, 'min_samples_leaf': 5, 'max_features': 'log2'}. Best is trial 2 with value: 0.6193297985124616.

[RandomForest|seed=456] trial=2 auc=0.619330 train_time=113.72s
[Optuna] Trial 002 | value=0.619330 | params={'n_estimators': 800, 'max_depth': 10, 'min_samples_split': 17, 'min_samples_leaf': 5, 'max_features': 'log2'}

[I 2026-04-05 07:57:47,756] Trial 3 finished with value: 0.6178050225435106 and parameters: {'n_estimators': 1100, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 8, 'max_features': None}. Best is trial 2 with value: 0.6193297985124616.

[RandomForest|seed=456] trial=3 auc=0.617805 train_time=842.99s
[Optuna] Trial 003 | value=0.617805 | params={'n_estimators': 1100, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 8, 'max_features': None}

[I 2026-04-05 08:01:05,222] Trial 4 finished with value: 0.5589326830222221 and parameters: {'n_estimators': 1100, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 2 with value: 0.6193297985124616.

[RandomForest|seed=456] trial=4 auc=0.558933 train_time=197.39s
[Optuna] Trial 004 | value=0.558933 | params={'n_estimators': 1100, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'log2'}
[BEST] RandomForest seed=456 best_auc(valid)=0.619330
[BEST] params={'n_estimators': 800, 'max_depth': 10, 'min_samples_split': 17, 'min_samples_leaf': 5, 'max_features': 'log2'}
[CKPT] Saved RandomForest seed=456 -> artifacts/checkpoints/RandomForest_seed456

==================== RandomForest | seed=789 ====================

[I 2026-04-05 08:04:11,632] A new study created in memory with name: no-name-090c863a-dccf-491c-adf1-11442a6fc2e0
[I 2026-04-05 08:06:00,193] Trial 0 finished with value: 0.6149042226699416 and parameters: {'n_estimators': 1100, 'max_depth': 4, 'min_samples_split': 16, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.6149042226699416.

[RandomForest|seed=789] trial=0 auc=0.614904 train_time=108.53s
[Optuna] Trial 000 | value=0.614904 | params={'n_estimators': 1100, 'max_depth': 4, 'min_samples_split': 16, 'min_samples_leaf': 10, 'max_features': 'sqrt'}

[I 2026-04-05 08:08:38,562] Trial 1 finished with value: 0.6182999686462137 and parameters: {'n_estimators': 1000, 'max_depth': 10, 'min_samples_split': 18, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 1 with value: 0.6182999686462137.

[RandomForest|seed=789] trial=1 auc=0.618300 train_time=158.34s
[Optuna] Trial 001 | value=0.618300 | params={'n_estimators': 1000, 'max_depth': 10, 'min_samples_split': 18, 'min_samples_leaf': 9, 'max_features': 'sqrt'}

[I 2026-04-05 08:10:46,329] Trial 2 finished with value: 0.6206450549665339 and parameters: {'n_estimators': 1100, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 10, 'max_features': 'log2'}. Best is trial 2 with value: 0.6206450549665339.

[RandomForest|seed=789] trial=2 auc=0.620645 train_time=127.74s
[Optuna] Trial 002 | value=0.620645 | params={'n_estimators': 1100, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 10, 'max_features': 'log2'}

[I 2026-04-05 08:11:04,481] Trial 3 finished with value: 0.6154984473237262 and parameters: {'n_estimators': 200, 'max_depth': 4, 'min_samples_split': 6, 'min_samples_leaf': 6, 'max_features': 'log2'}. Best is trial 2 with value: 0.6206450549665339.

[RandomForest|seed=789] trial=3 auc=0.615498 train_time=18.12s
[Optuna] Trial 003 | value=0.615498 | params={'n_estimators': 200, 'max_depth': 4, 'min_samples_split': 6, 'min_samples_leaf': 6, 'max_features': 'log2'}

[I 2026-04-05 08:13:29,016] Trial 4 finished with value: 0.6191855893394683 and parameters: {'n_estimators': 200, 'max_depth': 7, 'min_samples_split': 20, 'min_samples_leaf': 8, 'max_features': None}. Best is trial 2 with value: 0.6206450549665339.

[RandomForest|seed=789] trial=4 auc=0.619186 train_time=144.50s
[Optuna] Trial 004 | value=0.619186 | params={'n_estimators': 200, 'max_depth': 7, 'min_samples_split': 20, 'min_samples_leaf': 8, 'max_features': None}
[BEST] RandomForest seed=789 best_auc(valid)=0.620645
[BEST] params={'n_estimators': 1100, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 10, 'max_features': 'log2'}
[CKPT] Saved RandomForest seed=789 -> artifacts/checkpoints/RandomForest_seed789
[RESUME] RandomForest best seed selected: 789

[SUMMARY] RandomForest
  - accuracy            : mean=0.664457, std=0.053086
  - auc_roc             : mean=0.616941, std=0.001500
  - f1                  : mean=0.096822, std=0.001748
  - train_seconds       : mean=177.385270, std=46.686830
  - infer_ms_per_sample : mean=0.131132, std=0.032507
  - model_size_mb       : mean=31.085119, std=26.741593

In [ ]:
# ===== 3.3 XGBoost =====
def xgb_builder(params, seed):
    xgb_common = dict(
        objective="binary:logistic",
        eval_metric="auc",
        learning_rate=params["learning_rate"],
        max_depth=params["max_depth"],
        min_child_weight=params["min_child_weight"],
        subsample=params["subsample"],
        colsample_bytree=params["colsample_bytree"],
        reg_alpha=params["reg_alpha"],
        reg_lambda=params["reg_lambda"],
        n_estimators=params["n_estimators"],
        random_state=seed,
        n_jobs=-1,
    )
    if USE_GPU:
        # XGBoost 2.x recommends device='cuda' + hist
        return XGBClassifier(tree_method="hist", device="cuda", **xgb_common)
    return XGBClassifier(tree_method="hist", **xgb_common)

def xgb_suggester(trial):
    return {
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
        "max_depth": trial.suggest_int("max_depth", 3, 10),
        "min_child_weight": trial.suggest_float("min_child_weight", 1e-2, 20.0, log=True),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-8, 10.0, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-8, 20.0, log=True),
        "n_estimators": trial.suggest_int("n_estimators", 200, 1400, step=100),
    }

run_classical_experiment(
    model_name="XGBoost",
    model_builder_fn=xgb_builder,
    param_suggester_fn=xgb_suggester,
    model_family="tree",
    use_native_cat=False,
    n_trials=N_TRIALS,
    seeds=SEEDS,
    verbose=True,
    )

==================== XGBoost | seed=123 ====================

[I 2026-04-05 08:17:23,263] A new study created in memory with name: no-name-1c1ad658-f455-4c75-b0da-7390fed5a3e8
[I 2026-04-05 08:17:30,450] Trial 0 finished with value: 0.5801933260863534 and parameters: {'learning_rate': 0.11173563190654363, 'max_depth': 6, 'min_child_weight': 4.784472615172413, 'subsample': 0.6344487326037691, 'colsample_bytree': 0.771510036023904, 'reg_alpha': 0.0072062010845638635, 'reg_lambda': 0.4608317091104452, 'n_estimators': 1300}. Best is trial 0 with value: 0.5801933260863534.

[XGBoost|seed=123] trial=0 auc=0.580193 train_time=7.14s
[Optuna] Trial 000 | value=0.580193 | params={'learning_rate': 0.11173563190654363, 'max_depth': 6, 'min_child_weight': 4.784472615172413, 'subsample': 0.6344487326037691, 'colsample_bytree': 0.771510036023904, 'reg_alpha': 0.0072062010845638635, 'reg_lambda': 0.4608317091104452, 'n_estimators': 1300}

[I 2026-04-05 08:17:32,348] Trial 1 finished with value: 0.6262655086795786 and parameters: {'learning_rate': 0.19477181057696416, 'max_depth': 3, 'min_child_weight': 0.24432548003700166, 'subsample': 0.8743921662054399, 'colsample_bytree': 0.7988246277710186, 'reg_alpha': 4.033231047390516e-05, 'reg_lambda': 0.002758223855977828, 'n_estimators': 500}. Best is trial 1 with value: 0.6262655086795786.

[XGBoost|seed=123] trial=1 auc=0.626266 train_time=1.86s
[Optuna] Trial 001 | value=0.626266 | params={'learning_rate': 0.19477181057696416, 'max_depth': 3, 'min_child_weight': 0.24432548003700166, 'subsample': 0.8743921662054399, 'colsample_bytree': 0.7988246277710186, 'reg_alpha': 4.033231047390516e-05, 'reg_lambda': 0.002758223855977828, 'n_estimators': 500}

[I 2026-04-05 08:17:38,701] Trial 2 finished with value: 0.6291317164749728 and parameters: {'learning_rate': 0.010044272129662104, 'max_depth': 10, 'min_child_weight': 2.7899704473857514, 'subsample': 0.6630377106745151, 'colsample_bytree': 0.8705893066464654, 'reg_alpha': 0.07208173521625011, 'reg_lambda': 0.014365192637209635, 'n_estimators': 500}. Best is trial 2 with value: 0.6291317164749728.

[XGBoost|seed=123] trial=2 auc=0.629132 train_time=6.32s
[Optuna] Trial 002 | value=0.629132 | params={'learning_rate': 0.010044272129662104, 'max_depth': 10, 'min_child_weight': 2.7899704473857514, 'subsample': 0.6630377106745151, 'colsample_bytree': 0.8705893066464654, 'reg_alpha': 0.07208173521625011, 'reg_lambda': 0.014365192637209635, 'n_estimators': 500}

[I 2026-04-05 08:17:42,267] Trial 3 finished with value: 0.6072351610482909 and parameters: {'learning_rate': 0.07045811759574756, 'max_depth': 7, 'min_child_weight': 0.02113382120890887, 'subsample': 0.5547949165519306, 'colsample_bytree': 0.5997646727592162, 'reg_alpha': 0.5622479376104094, 'reg_lambda': 1.2231467491872179, 'n_estimators': 500}. Best is trial 2 with value: 0.6291317164749728.

[XGBoost|seed=123] trial=3 auc=0.607235 train_time=3.53s
[Optuna] Trial 003 | value=0.607235 | params={'learning_rate': 0.07045811759574756, 'max_depth': 7, 'min_child_weight': 0.02113382120890887, 'subsample': 0.5547949165519306, 'colsample_bytree': 0.5997646727592162, 'reg_alpha': 0.5622479376104094, 'reg_lambda': 1.2231467491872179, 'n_estimators': 500}

[I 2026-04-05 08:17:44,482] Trial 4 finished with value: 0.6209531487939208 and parameters: {'learning_rate': 0.0693317635098388, 'max_depth': 7, 'min_child_weight': 5.929139362031749, 'subsample': 0.9862012136776332, 'colsample_bytree': 0.9675766166580151, 'reg_alpha': 1.4741846279471402, 'reg_lambda': 2.1327490235697648e-08, 'n_estimators': 300}. Best is trial 2 with value: 0.6291317164749728.

[XGBoost|seed=123] trial=4 auc=0.620953 train_time=2.18s
[Optuna] Trial 004 | value=0.620953 | params={'learning_rate': 0.0693317635098388, 'max_depth': 7, 'min_child_weight': 5.929139362031749, 'subsample': 0.9862012136776332, 'colsample_bytree': 0.9675766166580151, 'reg_alpha': 1.4741846279471402, 'reg_lambda': 2.1327490235697648e-08, 'n_estimators': 300}
[BEST] XGBoost seed=123 best_auc(valid)=0.629132
[BEST] params={'learning_rate': 0.010044272129662104, 'max_depth': 10, 'min_child_weight': 2.7899704473857514, 'subsample': 0.6630377106745151, 'colsample_bytree': 0.8705893066464654, 'reg_alpha': 0.07208173521625011, 'reg_lambda': 0.014365192637209635, 'n_estimators': 500}
[CKPT] Saved XGBoost seed=123 -> artifacts/checkpoints/XGBoost_seed123

==================== XGBoost | seed=456 ====================

[I 2026-04-05 08:17:59,106] A new study created in memory with name: no-name-739a1166-d21c-4fba-9b00-d689acc78c9b
[I 2026-04-05 08:18:02,518] Trial 0 finished with value: 0.6222400267441078 and parameters: {'learning_rate': 0.050654547820224334, 'max_depth': 6, 'min_child_weight': 0.010684109271978864, 'subsample': 0.9641091639034916, 'colsample_bytree': 0.8767819260202622, 'reg_alpha': 0.012040743672009484, 'reg_lambda': 0.00019702964294095128, 'n_estimators': 600}. Best is trial 0 with value: 0.6222400267441078.

[XGBoost|seed=456] trial=0 auc=0.622240 train_time=3.37s
[Optuna] Trial 000 | value=0.622240 | params={'learning_rate': 0.050654547820224334, 'max_depth': 6, 'min_child_weight': 0.010684109271978864, 'subsample': 0.9641091639034916, 'colsample_bytree': 0.8767819260202622, 'reg_alpha': 0.012040743672009484, 'reg_lambda': 0.00019702964294095128, 'n_estimators': 600}

[I 2026-04-05 08:18:05,869] Trial 1 finished with value: 0.5768714046059042 and parameters: {'learning_rate': 0.2014612214186296, 'max_depth': 6, 'min_child_weight': 0.04816261521869371, 'subsample': 0.957720765006068, 'colsample_bytree': 0.6094766770047831, 'reg_alpha': 0.005860778579556531, 'reg_lambda': 0.0002806470758188383, 'n_estimators': 600}. Best is trial 0 with value: 0.6222400267441078.

[XGBoost|seed=456] trial=1 auc=0.576871 train_time=3.32s
[Optuna] Trial 001 | value=0.576871 | params={'learning_rate': 0.2014612214186296, 'max_depth': 6, 'min_child_weight': 0.04816261521869371, 'subsample': 0.957720765006068, 'colsample_bytree': 0.6094766770047831, 'reg_alpha': 0.005860778579556531, 'reg_lambda': 0.0002806470758188383, 'n_estimators': 600}

[I 2026-04-05 08:18:09,372] Trial 2 finished with value: 0.6345433006622359 and parameters: {'learning_rate': 0.028616761094994503, 'max_depth': 4, 'min_child_weight': 18.635372864722914, 'subsample': 0.581992398786102, 'colsample_bytree': 0.8505580217877864, 'reg_alpha': 0.0003685235982641501, 'reg_lambda': 0.14921089972391988, 'n_estimators': 900}. Best is trial 2 with value: 0.6345433006622359.

[XGBoost|seed=456] trial=2 auc=0.634543 train_time=3.46s
[Optuna] Trial 002 | value=0.634543 | params={'learning_rate': 0.028616761094994503, 'max_depth': 4, 'min_child_weight': 18.635372864722914, 'subsample': 0.581992398786102, 'colsample_bytree': 0.8505580217877864, 'reg_alpha': 0.0003685235982641501, 'reg_lambda': 0.14921089972391988, 'n_estimators': 900}

[I 2026-04-05 08:18:11,874] Trial 3 finished with value: 0.6320811037870121 and parameters: {'learning_rate': 0.01711000494698094, 'max_depth': 10, 'min_child_weight': 10.670319207422107, 'subsample': 0.6272735569988115, 'colsample_bytree': 0.7798052145123882, 'reg_alpha': 0.02905519173526372, 'reg_lambda': 2.046964805265329e-06, 'n_estimators': 200}. Best is trial 2 with value: 0.6345433006622359.

[XGBoost|seed=456] trial=3 auc=0.632081 train_time=2.47s
[Optuna] Trial 003 | value=0.632081 | params={'learning_rate': 0.01711000494698094, 'max_depth': 10, 'min_child_weight': 10.670319207422107, 'subsample': 0.6272735569988115, 'colsample_bytree': 0.7798052145123882, 'reg_alpha': 0.02905519173526372, 'reg_lambda': 2.046964805265329e-06, 'n_estimators': 200}

[I 2026-04-05 08:18:14,023] Trial 4 finished with value: 0.6303288065185914 and parameters: {'learning_rate': 0.010547522905350128, 'max_depth': 8, 'min_child_weight': 0.7305418821532923, 'subsample': 0.9160037638706161, 'colsample_bytree': 0.6125847470541876, 'reg_alpha': 1.0011685645308773e-08, 'reg_lambda': 8.288582757926263e-06, 'n_estimators': 200}. Best is trial 2 with value: 0.6345433006622359.

[XGBoost|seed=456] trial=4 auc=0.630329 train_time=2.12s
[Optuna] Trial 004 | value=0.630329 | params={'learning_rate': 0.010547522905350128, 'max_depth': 8, 'min_child_weight': 0.7305418821532923, 'subsample': 0.9160037638706161, 'colsample_bytree': 0.6125847470541876, 'reg_alpha': 1.0011685645308773e-08, 'reg_lambda': 8.288582757926263e-06, 'n_estimators': 200}
[BEST] XGBoost seed=456 best_auc(valid)=0.634543
[BEST] params={'learning_rate': 0.028616761094994503, 'max_depth': 4, 'min_child_weight': 18.635372864722914, 'subsample': 0.581992398786102, 'colsample_bytree': 0.8505580217877864, 'reg_alpha': 0.0003685235982641501, 'reg_lambda': 0.14921089972391988, 'n_estimators': 900}
[CKPT] Saved XGBoost seed=456 -> artifacts/checkpoints/XGBoost_seed456

==================== XGBoost | seed=789 ====================

[I 2026-04-05 08:18:25,185] A new study created in memory with name: no-name-a9ba1bbe-ece1-4560-8f74-59aeb4331edf
[I 2026-04-05 08:18:27,615] Trial 0 finished with value: 0.6348707494972641 and parameters: {'learning_rate': 0.022127403832621583, 'max_depth': 3, 'min_child_weight': 1.7790267814124234, 'subsample': 0.7945567382721752, 'colsample_bytree': 0.8696824869009516, 'reg_alpha': 0.0014139104597015485, 'reg_lambda': 7.028978444644654e-05, 'n_estimators': 600}. Best is trial 0 with value: 0.6348707494972641.

[XGBoost|seed=789] trial=0 auc=0.634871 train_time=2.39s
[Optuna] Trial 000 | value=0.634871 | params={'learning_rate': 0.022127403832621583, 'max_depth': 3, 'min_child_weight': 1.7790267814124234, 'subsample': 0.7945567382721752, 'colsample_bytree': 0.8696824869009516, 'reg_alpha': 0.0014139104597015485, 'reg_lambda': 7.028978444644654e-05, 'n_estimators': 600}

[I 2026-04-05 08:18:32,549] Trial 1 finished with value: 0.550240715374906 and parameters: {'learning_rate': 0.2870691869493593, 'max_depth': 6, 'min_child_weight': 1.5395932764302285, 'subsample': 0.7701733440162399, 'colsample_bytree': 0.9864987780371528, 'reg_alpha': 1.7642006041982626e-07, 'reg_lambda': 2.4920407862178344e-07, 'n_estimators': 900}. Best is trial 0 with value: 0.6348707494972641.

[XGBoost|seed=789] trial=1 auc=0.550241 train_time=4.89s
[Optuna] Trial 001 | value=0.550241 | params={'learning_rate': 0.2870691869493593, 'max_depth': 6, 'min_child_weight': 1.5395932764302285, 'subsample': 0.7701733440162399, 'colsample_bytree': 0.9864987780371528, 'reg_alpha': 1.7642006041982626e-07, 'reg_lambda': 2.4920407862178344e-07, 'n_estimators': 900}

[I 2026-04-05 08:18:37,095] Trial 2 finished with value: 0.5740709933884435 and parameters: {'learning_rate': 0.1334427232368235, 'max_depth': 7, 'min_child_weight': 0.10931478305228041, 'subsample': 0.8551461527332738, 'colsample_bytree': 0.5464767112312398, 'reg_alpha': 5.939661176861022e-08, 'reg_lambda': 2.008958002335519e-06, 'n_estimators': 700}. Best is trial 0 with value: 0.6348707494972641.

[XGBoost|seed=789] trial=2 auc=0.574071 train_time=4.51s
[Optuna] Trial 002 | value=0.574071 | params={'learning_rate': 0.1334427232368235, 'max_depth': 7, 'min_child_weight': 0.10931478305228041, 'subsample': 0.8551461527332738, 'colsample_bytree': 0.5464767112312398, 'reg_alpha': 5.939661176861022e-08, 'reg_lambda': 2.008958002335519e-06, 'n_estimators': 700}

[I 2026-04-05 08:18:44,864] Trial 3 finished with value: 0.6160075776552724 and parameters: {'learning_rate': 0.04248856382780391, 'max_depth': 7, 'min_child_weight': 16.88108135894345, 'subsample': 0.8057991119645812, 'colsample_bytree': 0.8484712718112042, 'reg_alpha': 0.2013427510507727, 'reg_lambda': 5.643805895891701, 'n_estimators': 1300}. Best is trial 0 with value: 0.6348707494972641.

[XGBoost|seed=789] trial=3 auc=0.616008 train_time=7.72s
[Optuna] Trial 003 | value=0.616008 | params={'learning_rate': 0.04248856382780391, 'max_depth': 7, 'min_child_weight': 16.88108135894345, 'subsample': 0.8057991119645812, 'colsample_bytree': 0.8484712718112042, 'reg_alpha': 0.2013427510507727, 'reg_lambda': 5.643805895891701, 'n_estimators': 1300}

[I 2026-04-05 08:18:49,229] Trial 4 finished with value: 0.6293907959004177 and parameters: {'learning_rate': 0.014707349542611832, 'max_depth': 9, 'min_child_weight': 0.39499484550107444, 'subsample': 0.6298867452398829, 'colsample_bytree': 0.8524183916826701, 'reg_alpha': 2.1649693345769293e-06, 'reg_lambda': 0.010557679586468777, 'n_estimators': 400}. Best is trial 0 with value: 0.6348707494972641.

[XGBoost|seed=789] trial=4 auc=0.629391 train_time=4.33s
[Optuna] Trial 004 | value=0.629391 | params={'learning_rate': 0.014707349542611832, 'max_depth': 9, 'min_child_weight': 0.39499484550107444, 'subsample': 0.6298867452398829, 'colsample_bytree': 0.8524183916826701, 'reg_alpha': 2.1649693345769293e-06, 'reg_lambda': 0.010557679586468777, 'n_estimators': 400}
[BEST] XGBoost seed=789 best_auc(valid)=0.634871
[BEST] params={'learning_rate': 0.022127403832621583, 'max_depth': 3, 'min_child_weight': 1.7790267814124234, 'subsample': 0.7945567382721752, 'colsample_bytree': 0.8696824869009516, 'reg_alpha': 0.0014139104597015485, 'reg_lambda': 7.028978444644654e-05, 'n_estimators': 600}
[CKPT] Saved XGBoost seed=789 -> artifacts/checkpoints/XGBoost_seed789
[RESUME] XGBoost best seed selected: 456

[SUMMARY] XGBoost
  - accuracy            : mean=0.963551, std=0.000000
  - auc_roc             : mean=0.634833, std=0.000335
  - f1                  : mean=0.000000, std=0.000000
  - train_seconds       : mean=9.120490, std=2.115997
  - infer_ms_per_sample : mean=0.008366, std=0.000804
  - model_size_mb       : mean=4.281381, std=4.621639

In [ ]:
# ===== 3.4 LightGBM =====
def lgbm_builder(params, seed):
    return LGBMClassifier(
        objective="binary",
        metric="auc",
        learning_rate=params["learning_rate"],
        n_estimators=params["n_estimators"],
        num_leaves=params["num_leaves"],
        max_depth=params["max_depth"],
        min_child_samples=params["min_child_samples"],
        subsample=params["subsample"],
        colsample_bytree=params["colsample_bytree"],
        reg_alpha=params["reg_alpha"],
        reg_lambda=params["reg_lambda"],
        random_state=seed,
        n_jobs=-1,
        verbosity=1,
        device_type="gpu" if USE_GPU else "cpu",
    )

def lgbm_suggester(trial):
    return {
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.2, log=True),
        "n_estimators": trial.suggest_int("n_estimators", 300, 1800, step=100),
        "num_leaves": trial.suggest_int("num_leaves", 16, 256),
        "max_depth": trial.suggest_int("max_depth", -1, 16),
        "min_child_samples": trial.suggest_int("min_child_samples", 5, 100),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-8, 10.0, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-8, 10.0, log=True),
    }

run_classical_experiment(
    model_name="LightGBM",
    model_builder_fn=lgbm_builder,
    param_suggester_fn=lgbm_suggester,
    model_family="tree",
    use_native_cat=False,
    n_trials=N_TRIALS,
    seeds=SEEDS,
    verbose=True,
    )

==================== LightGBM | seed=123 ====================

[I 2026-04-05 08:18:58,673] A new study created in memory with name: no-name-769f8ea3-25c5-4578-94b4-760c94944ddb

[LightGBM] [Info] Number of positive: 13016, number of negative: 344110
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 1609
[LightGBM] [Info] Number of data points in the train set: 357126, number of used features: 58
[LightGBM] [Info] Using GPU Device: Tesla T4, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 35 dense feature groups (12.26 MB) transferred to GPU in 0.011612 secs. 1 sparse feature groups
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.036447 -> initscore=-3.274782
[LightGBM] [Info] Start training from score -3.274782

[I 2026-04-05 08:19:22,490] Trial 0 finished with value: 0.6308098737969112 and parameters: {'learning_rate': 0.03439031558660186, 'n_estimators': 1200, 'num_leaves': 27, 'max_depth': 16, 'min_child_samples': 100, 'subsample': 0.8046998006115287, 'colsample_bytree': 0.5491797894669113, 'reg_alpha': 7.747445968206635, 'reg_lambda': 9.108783169342993e-06}. Best is trial 0 with value: 0.6308098737969112.

[LightGBM|seed=123] trial=0 auc=0.630810 train_time=23.79s
[Optuna] Trial 000 | value=0.630810 | params={'learning_rate': 0.03439031558660186, 'n_estimators': 1200, 'num_leaves': 27, 'max_depth': 16, 'min_child_samples': 100, 'subsample': 0.8046998006115287, 'colsample_bytree': 0.5491797894669113, 'reg_alpha': 7.747445968206635, 'reg_lambda': 9.108783169342993e-06}
[LightGBM] [Info] Number of positive: 13016, number of negative: 344110
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 1609
[LightGBM] [Info] Number of data points in the train set: 357126, number of used features: 58
[LightGBM] [Info] Using GPU Device: Tesla T4, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 35 dense feature groups (12.26 MB) transferred to GPU in 0.011596 secs. 1 sparse feature groups
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.036447 -> initscore=-3.274782
[LightGBM] [Info] Start training from score -3.274782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2026-04-05 08:19:32,044] Trial 1 finished with value: 0.6307813466092759 and parameters: {'learning_rate': 0.012942181670442308, 'n_estimators': 900, 'num_leaves': 28, 'max_depth': 2, 'min_child_samples': 81, 'subsample': 0.5141170785500236, 'colsample_bytree': 0.6614385248974765, 'reg_alpha': 1.4884274597375612e-07, 'reg_lambda': 0.050435902448870945}. Best is trial 0 with value: 0.6308098737969112.

[LightGBM|seed=123] trial=1 auc=0.630781 train_time=9.52s
[Optuna] Trial 001 | value=0.630781 | params={'learning_rate': 0.012942181670442308, 'n_estimators': 900, 'num_leaves': 28, 'max_depth': 2, 'min_child_samples': 81, 'subsample': 0.5141170785500236, 'colsample_bytree': 0.6614385248974765, 'reg_alpha': 1.4884274597375612e-07, 'reg_lambda': 0.050435902448870945}
[LightGBM] [Info] Number of positive: 13016, number of negative: 344110
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 1609
[LightGBM] [Info] Number of data points in the train set: 357126, number of used features: 58
[LightGBM] [Info] Using GPU Device: Tesla T4, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 35 dense feature groups (12.26 MB) transferred to GPU in 0.011645 secs. 1 sparse feature groups
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.036447 -> initscore=-3.274782
[LightGBM] [Info] Start training from score -3.274782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2026-04-05 08:20:07,749] Trial 2 finished with value: 0.6184001754661139 and parameters: {'learning_rate': 0.01602483289810771, 'n_estimators': 1300, 'num_leaves': 224, 'max_depth': 8, 'min_child_samples': 100, 'subsample': 0.7976530731277356, 'colsample_bytree': 0.9262546942040917, 'reg_alpha': 0.00013154588807135916, 'reg_lambda': 1.3874087416566441e-08}. Best is trial 0 with value: 0.6308098737969112.

[LightGBM|seed=123] trial=2 auc=0.618400 train_time=35.67s
[Optuna] Trial 002 | value=0.618400 | params={'learning_rate': 0.01602483289810771, 'n_estimators': 1300, 'num_leaves': 224, 'max_depth': 8, 'min_child_samples': 100, 'subsample': 0.7976530731277356, 'colsample_bytree': 0.9262546942040917, 'reg_alpha': 0.00013154588807135916, 'reg_lambda': 1.3874087416566441e-08}
[LightGBM] [Info] Number of positive: 13016, number of negative: 344110
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 1609
[LightGBM] [Info] Number of data points in the train set: 357126, number of used features: 58
[LightGBM] [Info] Using GPU Device: Tesla T4, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 35 dense feature groups (12.26 MB) transferred to GPU in 0.011340 secs. 1 sparse feature groups
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.036447 -> initscore=-3.274782
[LightGBM] [Info] Start training from score -3.274782

[I 2026-04-05 08:20:28,001] Trial 3 finished with value: 0.6308166650276628 and parameters: {'learning_rate': 0.02259973366560454, 'n_estimators': 1600, 'num_leaves': 29, 'max_depth': 8, 'min_child_samples': 9, 'subsample': 0.8606108249839577, 'colsample_bytree': 0.697435240170543, 'reg_alpha': 3.9846312604622795e-06, 'reg_lambda': 2.7120012515427227e-05}. Best is trial 3 with value: 0.6308166650276628.

[LightGBM|seed=123] trial=3 auc=0.630817 train_time=20.22s
[Optuna] Trial 003 | value=0.630817 | params={'learning_rate': 0.02259973366560454, 'n_estimators': 1600, 'num_leaves': 29, 'max_depth': 8, 'min_child_samples': 9, 'subsample': 0.8606108249839577, 'colsample_bytree': 0.697435240170543, 'reg_alpha': 3.9846312604622795e-06, 'reg_lambda': 2.7120012515427227e-05}
[LightGBM] [Info] Number of positive: 13016, number of negative: 344110
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 1609
[LightGBM] [Info] Number of data points in the train set: 357126, number of used features: 58
[LightGBM] [Info] Using GPU Device: Tesla T4, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 35 dense feature groups (12.26 MB) transferred to GPU in 0.011762 secs. 1 sparse feature groups
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.036447 -> initscore=-3.274782
[LightGBM] [Info] Start training from score -3.274782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2026-04-05 08:21:15,205] Trial 4 finished with value: 0.5774312079669028 and parameters: {'learning_rate': 0.08804697176685419, 'n_estimators': 1100, 'num_leaves': 230, 'max_depth': 10, 'min_child_samples': 32, 'subsample': 0.7178805196883318, 'colsample_bytree': 0.5139044316804963, 'reg_alpha': 0.0007961900245094472, 'reg_lambda': 4.94678330572949}. Best is trial 3 with value: 0.6308166650276628.

[LightGBM|seed=123] trial=4 auc=0.577431 train_time=47.17s
[Optuna] Trial 004 | value=0.577431 | params={'learning_rate': 0.08804697176685419, 'n_estimators': 1100, 'num_leaves': 230, 'max_depth': 10, 'min_child_samples': 32, 'subsample': 0.7178805196883318, 'colsample_bytree': 0.5139044316804963, 'reg_alpha': 0.0007961900245094472, 'reg_lambda': 4.94678330572949}
[BEST] LightGBM seed=123 best_auc(valid)=0.630817
[BEST] params={'learning_rate': 0.02259973366560454, 'n_estimators': 1600, 'num_leaves': 29, 'max_depth': 8, 'min_child_samples': 9, 'subsample': 0.8606108249839577, 'colsample_bytree': 0.697435240170543, 'reg_alpha': 3.9846312604622795e-06, 'reg_lambda': 2.7120012515427227e-05}
[LightGBM] [Info] Number of positive: 13016, number of negative: 344110
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 1609
[LightGBM] [Info] Number of data points in the train set: 357126, number of used features: 58
[LightGBM] [Info] Using GPU Device: Tesla T4, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 35 dense feature groups (12.26 MB) transferred to GPU in 0.035671 secs. 1 sparse feature groups
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.036447 -> initscore=-3.274782
[LightGBM] [Info] Start training from score -3.274782
[CKPT] Saved LightGBM seed=123 -> artifacts/checkpoints/LightGBM_seed123

==================== LightGBM | seed=456 ====================

[I 2026-04-05 08:21:57,178] A new study created in memory with name: no-name-254a3012-2436-4b3c-bfff-bc29ba2925e6

[LightGBM] [Info] Number of positive: 13016, number of negative: 344110
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 1607
[LightGBM] [Info] Number of data points in the train set: 357126, number of used features: 58
[LightGBM] [Info] Using GPU Device: Tesla T4, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 35 dense feature groups (12.26 MB) transferred to GPU in 0.042229 secs. 1 sparse feature groups
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.036447 -> initscore=-3.274782
[LightGBM] [Info] Start training from score -3.274782

[I 2026-04-05 08:22:03,984] Trial 0 finished with value: 0.6317765311524925 and parameters: {'learning_rate': 0.046071274823772934, 'n_estimators': 300, 'num_leaves': 57, 'max_depth': 13, 'min_child_samples': 46, 'subsample': 0.6070725538538317, 'colsample_bytree': 0.676049902158778, 'reg_alpha': 1.7415642506281814, 'reg_lambda': 1.9829316362154138e-08}. Best is trial 0 with value: 0.6317765311524925.

[LightGBM|seed=456] trial=0 auc=0.631777 train_time=6.78s
[Optuna] Trial 000 | value=0.631777 | params={'learning_rate': 0.046071274823772934, 'n_estimators': 300, 'num_leaves': 57, 'max_depth': 13, 'min_child_samples': 46, 'subsample': 0.6070725538538317, 'colsample_bytree': 0.676049902158778, 'reg_alpha': 1.7415642506281814, 'reg_lambda': 1.9829316362154138e-08}
[LightGBM] [Info] Number of positive: 13016, number of negative: 344110
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 1607
[LightGBM] [Info] Number of data points in the train set: 357126, number of used features: 58
[LightGBM] [Info] Using GPU Device: Tesla T4, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 35 dense feature groups (12.26 MB) transferred to GPU in 0.012405 secs. 1 sparse feature groups
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.036447 -> initscore=-3.274782
[LightGBM] [Info] Start training from score -3.274782

[I 2026-04-05 08:22:45,832] Trial 1 finished with value: 0.5855265217894349 and parameters: {'learning_rate': 0.06707073859758884, 'n_estimators': 1600, 'num_leaves': 128, 'max_depth': 11, 'min_child_samples': 21, 'subsample': 0.9688347548741878, 'colsample_bytree': 0.6561719804943695, 'reg_alpha': 0.461024181990501, 'reg_lambda': 0.00010158049467832453}. Best is trial 0 with value: 0.6317765311524925.

[LightGBM|seed=456] trial=1 auc=0.585527 train_time=41.81s
[Optuna] Trial 001 | value=0.585527 | params={'learning_rate': 0.06707073859758884, 'n_estimators': 1600, 'num_leaves': 128, 'max_depth': 11, 'min_child_samples': 21, 'subsample': 0.9688347548741878, 'colsample_bytree': 0.6561719804943695, 'reg_alpha': 0.461024181990501, 'reg_lambda': 0.00010158049467832453}
[LightGBM] [Info] Number of positive: 13016, number of negative: 344110
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 1607
[LightGBM] [Info] Number of data points in the train set: 357126, number of used features: 58
[LightGBM] [Info] Using GPU Device: Tesla T4, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 35 dense feature groups (12.26 MB) transferred to GPU in 0.021039 secs. 1 sparse feature groups
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.036447 -> initscore=-3.274782
[LightGBM] [Info] Start training from score -3.274782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2026-04-05 08:23:19,318] Trial 2 finished with value: 0.5725483291305928 and parameters: {'learning_rate': 0.11001544953949068, 'n_estimators': 900, 'num_leaves': 198, 'max_depth': 12, 'min_child_samples': 100, 'subsample': 0.9572753851410296, 'colsample_bytree': 0.903280677865751, 'reg_alpha': 3.342063623802249e-06, 'reg_lambda': 9.435122878204101e-08}. Best is trial 0 with value: 0.6317765311524925.

[LightGBM|seed=456] trial=2 auc=0.572548 train_time=33.45s
[Optuna] Trial 002 | value=0.572548 | params={'learning_rate': 0.11001544953949068, 'n_estimators': 900, 'num_leaves': 198, 'max_depth': 12, 'min_child_samples': 100, 'subsample': 0.9572753851410296, 'colsample_bytree': 0.903280677865751, 'reg_alpha': 3.342063623802249e-06, 'reg_lambda': 9.435122878204101e-08}
[LightGBM] [Info] Number of positive: 13016, number of negative: 344110
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 1607
[LightGBM] [Info] Number of data points in the train set: 357126, number of used features: 58
[LightGBM] [Info] Using GPU Device: Tesla T4, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 35 dense feature groups (12.26 MB) transferred to GPU in 0.036763 secs. 1 sparse feature groups
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.036447 -> initscore=-3.274782
[LightGBM] [Info] Start training from score -3.274782

[I 2026-04-05 08:23:36,640] Trial 3 finished with value: 0.5849061187494194 and parameters: {'learning_rate': 0.07855051976980262, 'n_estimators': 500, 'num_leaves': 202, 'max_depth': 15, 'min_child_samples': 22, 'subsample': 0.9388911329421974, 'colsample_bytree': 0.8295363532347442, 'reg_alpha': 0.005245480019684198, 'reg_lambda': 1.2588148358309215e-07}. Best is trial 0 with value: 0.6317765311524925.

[LightGBM|seed=456] trial=3 auc=0.584906 train_time=17.29s
[Optuna] Trial 003 | value=0.584906 | params={'learning_rate': 0.07855051976980262, 'n_estimators': 500, 'num_leaves': 202, 'max_depth': 15, 'min_child_samples': 22, 'subsample': 0.9388911329421974, 'colsample_bytree': 0.8295363532347442, 'reg_alpha': 0.005245480019684198, 'reg_lambda': 1.2588148358309215e-07}
[LightGBM] [Info] Number of positive: 13016, number of negative: 344110
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 1607
[LightGBM] [Info] Number of data points in the train set: 357126, number of used features: 58
[LightGBM] [Info] Using GPU Device: Tesla T4, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 35 dense feature groups (12.26 MB) transferred to GPU in 0.023154 secs. 1 sparse feature groups
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.036447 -> initscore=-3.274782
[LightGBM] [Info] Start training from score -3.274782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2026-04-05 08:23:56,871] Trial 4 finished with value: 0.6205543598881653 and parameters: {'learning_rate': 0.03139465356239859, 'n_estimators': 500, 'num_leaves': 197, 'max_depth': 10, 'min_child_samples': 96, 'subsample': 0.6993739919078469, 'colsample_bytree': 0.8790115257008285, 'reg_alpha': 0.008071899881340919, 'reg_lambda': 2.961707598247445}. Best is trial 0 with value: 0.6317765311524925.

[LightGBM|seed=456] trial=4 auc=0.620554 train_time=20.20s
[Optuna] Trial 004 | value=0.620554 | params={'learning_rate': 0.03139465356239859, 'n_estimators': 500, 'num_leaves': 197, 'max_depth': 10, 'min_child_samples': 96, 'subsample': 0.6993739919078469, 'colsample_bytree': 0.8790115257008285, 'reg_alpha': 0.008071899881340919, 'reg_lambda': 2.961707598247445}
[BEST] LightGBM seed=456 best_auc(valid)=0.631777
[BEST] params={'learning_rate': 0.046071274823772934, 'n_estimators': 300, 'num_leaves': 57, 'max_depth': 13, 'min_child_samples': 46, 'subsample': 0.6070725538538317, 'colsample_bytree': 0.676049902158778, 'reg_alpha': 1.7415642506281814, 'reg_lambda': 1.9829316362154138e-08}
[LightGBM] [Info] Number of positive: 13016, number of negative: 344110
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 1607
[LightGBM] [Info] Number of data points in the train set: 357126, number of used features: 58
[LightGBM] [Info] Using GPU Device: Tesla T4, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 35 dense feature groups (12.26 MB) transferred to GPU in 0.044181 secs. 1 sparse feature groups
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.036447 -> initscore=-3.274782
[LightGBM] [Info] Start training from score -3.274782
[CKPT] Saved LightGBM seed=456 -> artifacts/checkpoints/LightGBM_seed456

==================== LightGBM | seed=789 ====================

[I 2026-04-05 08:24:11,654] A new study created in memory with name: no-name-a33ddca1-7b76-4ae5-8bf1-729364dc9116

[LightGBM] [Info] Number of positive: 13016, number of negative: 344110
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 1613
[LightGBM] [Info] Number of data points in the train set: 357126, number of used features: 58
[LightGBM] [Info] Using GPU Device: Tesla T4, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 35 dense feature groups (12.26 MB) transferred to GPU in 0.022695 secs. 1 sparse feature groups
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.036447 -> initscore=-3.274782
[LightGBM] [Info] Start training from score -3.274782

[I 2026-04-05 08:24:26,600] Trial 0 finished with value: 0.5992745265740618 and parameters: {'learning_rate': 0.14724872218419327, 'n_estimators': 700, 'num_leaves': 62, 'max_depth': -1, 'min_child_samples': 64, 'subsample': 0.9803603031993826, 'colsample_bytree': 0.6635803850379207, 'reg_alpha': 7.309437451507658, 'reg_lambda': 1.4054601847987693e-08}. Best is trial 0 with value: 0.5992745265740618.

[LightGBM|seed=789] trial=0 auc=0.599275 train_time=14.91s
[Optuna] Trial 000 | value=0.599275 | params={'learning_rate': 0.14724872218419327, 'n_estimators': 700, 'num_leaves': 62, 'max_depth': -1, 'min_child_samples': 64, 'subsample': 0.9803603031993826, 'colsample_bytree': 0.6635803850379207, 'reg_alpha': 7.309437451507658, 'reg_lambda': 1.4054601847987693e-08}
[LightGBM] [Info] Number of positive: 13016, number of negative: 344110
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 1613
[LightGBM] [Info] Number of data points in the train set: 357126, number of used features: 58
[LightGBM] [Info] Using GPU Device: Tesla T4, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 35 dense feature groups (12.26 MB) transferred to GPU in 0.011897 secs. 1 sparse feature groups
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.036447 -> initscore=-3.274782
[LightGBM] [Info] Start training from score -3.274782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2026-04-05 08:24:35,865] Trial 1 finished with value: 0.6344901904248244 and parameters: {'learning_rate': 0.0361939152362532, 'n_estimators': 800, 'num_leaves': 56, 'max_depth': 3, 'min_child_samples': 24, 'subsample': 0.9072226176812946, 'colsample_bytree': 0.8909437324352822, 'reg_alpha': 0.0011836728969323266, 'reg_lambda': 0.0038699301510127988}. Best is trial 1 with value: 0.6344901904248244.

[LightGBM|seed=789] trial=1 auc=0.634490 train_time=9.23s
[Optuna] Trial 001 | value=0.634490 | params={'learning_rate': 0.0361939152362532, 'n_estimators': 800, 'num_leaves': 56, 'max_depth': 3, 'min_child_samples': 24, 'subsample': 0.9072226176812946, 'colsample_bytree': 0.8909437324352822, 'reg_alpha': 0.0011836728969323266, 'reg_lambda': 0.0038699301510127988}
[LightGBM] [Info] Number of positive: 13016, number of negative: 344110
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 1613
[LightGBM] [Info] Number of data points in the train set: 357126, number of used features: 58
[LightGBM] [Info] Using GPU Device: Tesla T4, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 35 dense feature groups (12.26 MB) transferred to GPU in 0.011621 secs. 1 sparse feature groups
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.036447 -> initscore=-3.274782
[LightGBM] [Info] Start training from score -3.274782

[I 2026-04-05 08:24:51,426] Trial 2 finished with value: 0.606008847615423 and parameters: {'learning_rate': 0.0636295835032485, 'n_estimators': 400, 'num_leaves': 208, 'max_depth': 0, 'min_child_samples': 65, 'subsample': 0.5121067527647679, 'colsample_bytree': 0.6300222930162904, 'reg_alpha': 3.611918735610124e-07, 'reg_lambda': 0.0007168519183077282}. Best is trial 1 with value: 0.6344901904248244.

[LightGBM|seed=789] trial=2 auc=0.606009 train_time=15.53s
[Optuna] Trial 002 | value=0.606009 | params={'learning_rate': 0.0636295835032485, 'n_estimators': 400, 'num_leaves': 208, 'max_depth': 0, 'min_child_samples': 65, 'subsample': 0.5121067527647679, 'colsample_bytree': 0.6300222930162904, 'reg_alpha': 3.611918735610124e-07, 'reg_lambda': 0.0007168519183077282}
[LightGBM] [Info] Number of positive: 13016, number of negative: 344110
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 1613
[LightGBM] [Info] Number of data points in the train set: 357126, number of used features: 58
[LightGBM] [Info] Using GPU Device: Tesla T4, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 35 dense feature groups (12.26 MB) transferred to GPU in 0.011471 secs. 1 sparse feature groups
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.036447 -> initscore=-3.274782
[LightGBM] [Info] Start training from score -3.274782

[I 2026-04-05 08:25:29,862] Trial 3 finished with value: 0.6205491700215883 and parameters: {'learning_rate': 0.023197464550952545, 'n_estimators': 900, 'num_leaves': 222, 'max_depth': 13, 'min_child_samples': 34, 'subsample': 0.7931608352777721, 'colsample_bytree': 0.708901341436224, 'reg_alpha': 1.2333330717536986, 'reg_lambda': 1.7082400761897393e-07}. Best is trial 1 with value: 0.6344901904248244.

[LightGBM|seed=789] trial=3 auc=0.620549 train_time=38.40s
[Optuna] Trial 003 | value=0.620549 | params={'learning_rate': 0.023197464550952545, 'n_estimators': 900, 'num_leaves': 222, 'max_depth': 13, 'min_child_samples': 34, 'subsample': 0.7931608352777721, 'colsample_bytree': 0.708901341436224, 'reg_alpha': 1.2333330717536986, 'reg_lambda': 1.7082400761897393e-07}
[LightGBM] [Info] Number of positive: 13016, number of negative: 344110
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 1613
[LightGBM] [Info] Number of data points in the train set: 357126, number of used features: 58
[LightGBM] [Info] Using GPU Device: Tesla T4, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 35 dense feature groups (12.26 MB) transferred to GPU in 0.012529 secs. 1 sparse feature groups
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.036447 -> initscore=-3.274782
[LightGBM] [Info] Start training from score -3.274782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2026-04-05 08:26:33,389] Trial 4 finished with value: 0.5985414212514119 and parameters: {'learning_rate': 0.026268280465006115, 'n_estimators': 1800, 'num_leaves': 191, 'max_depth': 13, 'min_child_samples': 77, 'subsample': 0.9467357777803387, 'colsample_bytree': 0.7368093051235503, 'reg_alpha': 4.863579058459068e-07, 'reg_lambda': 5.432712995150697e-08}. Best is trial 1 with value: 0.6344901904248244.

[LightGBM|seed=789] trial=4 auc=0.598541 train_time=63.49s
[Optuna] Trial 004 | value=0.598541 | params={'learning_rate': 0.026268280465006115, 'n_estimators': 1800, 'num_leaves': 191, 'max_depth': 13, 'min_child_samples': 77, 'subsample': 0.9467357777803387, 'colsample_bytree': 0.7368093051235503, 'reg_alpha': 4.863579058459068e-07, 'reg_lambda': 5.432712995150697e-08}
[BEST] LightGBM seed=789 best_auc(valid)=0.634490
[BEST] params={'learning_rate': 0.0361939152362532, 'n_estimators': 800, 'num_leaves': 56, 'max_depth': 3, 'min_child_samples': 24, 'subsample': 0.9072226176812946, 'colsample_bytree': 0.8909437324352822, 'reg_alpha': 0.0011836728969323266, 'reg_lambda': 0.0038699301510127988}
[LightGBM] [Info] Number of positive: 13016, number of negative: 344110
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 1613
[LightGBM] [Info] Number of data points in the train set: 357126, number of used features: 58
[LightGBM] [Info] Using GPU Device: Tesla T4, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 35 dense feature groups (12.26 MB) transferred to GPU in 0.038462 secs. 1 sparse feature groups
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.036447 -> initscore=-3.274782
[LightGBM] [Info] Start training from score -3.274782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [ ]:
# ===== 3.5 CatBoost =====
def cat_builder(params, seed):
    return CatBoostClassifier(
        loss_function="Logloss",
        eval_metric="AUC",
        depth=params["depth"],
        learning_rate=params["learning_rate"],
        l2_leaf_reg=params["l2_leaf_reg"],
        iterations=params["iterations"],
        random_seed=seed,
        verbose=100,
        task_type="GPU" if USE_GPU else "CPU",
        train_dir=str(CATBOOST_TRAIN_DIR),
    )

def cat_suggester(trial):
    return {
        "depth": trial.suggest_int("depth", 4, 10),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
        "l2_leaf_reg": trial.suggest_float("l2_leaf_reg", 1.0, 20.0),
        "iterations": trial.suggest_int("iterations", 300, 2000, step=100),
    }

run_classical_experiment(
    model_name="CatBoost",
    model_builder_fn=cat_builder,
    param_suggester_fn=cat_suggester,
    model_family="tree",
    use_native_cat=True,
    n_trials=N_TRIALS,
    seeds=SEEDS,
    verbose=True,
    )

==================== CatBoost | seed=123 ====================

[I 2026-04-05 08:26:53,872] A new study created in memory with name: no-name-169773fc-aa8c-4a62-9eb1-25fc89529fc5
Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.5568849	best: 0.5568849 (0)	total: 118ms	remaining: 1m 22s
100:	test: 0.6318208	best: 0.6318208 (100)	total: 7.91s	remaining: 46.9s
200:	test: 0.6335561	best: 0.6335561 (200)	total: 15.8s	remaining: 39.2s
300:	test: 0.6344244	best: 0.6344373 (285)	total: 23.9s	remaining: 31.6s
400:	test: 0.6342730	best: 0.6344771 (320)	total: 32.1s	remaining: 24s
500:	test: 0.6339919	best: 0.6344771 (320)	total: 40.4s	remaining: 16s
600:	test: 0.6328574	best: 0.6344771 (320)	total: 48.8s	remaining: 8.04s
699:	test: 0.6314823	best: 0.6344771 (320)	total: 57.2s	remaining: 0us
bestTest = 0.6344771385
bestIteration = 320
Shrink model to first 321 iterations.

[I 2026-04-05 08:27:55,075] Trial 0 finished with value: 0.6344771303656871 and parameters: {'depth': 8, 'learning_rate': 0.08432113568876762, 'l2_leaf_reg': 15.554906428804477, 'iterations': 700}. Best is trial 0 with value: 0.6344771303656871.

[CatBoost|seed=123] trial=0 auc=0.634477 train_time=61.17s
[Optuna] Trial 000 | value=0.634477 | params={'depth': 8, 'learning_rate': 0.08432113568876762, 'l2_leaf_reg': 15.554906428804477, 'iterations': 700}

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.5627290	best: 0.5627290 (0)	total: 165ms	remaining: 3m 50s
100:	test: 0.6322275	best: 0.6322483 (85)	total: 10.1s	remaining: 2m 9s
200:	test: 0.6297384	best: 0.6323300 (105)	total: 20.7s	remaining: 2m 3s
300:	test: 0.6274665	best: 0.6323300 (105)	total: 31.3s	remaining: 1m 54s
400:	test: 0.6229631	best: 0.6323300 (105)	total: 42s	remaining: 1m 44s
500:	test: 0.6183438	best: 0.6323300 (105)	total: 52.7s	remaining: 1m 34s
600:	test: 0.6143917	best: 0.6323300 (105)	total: 1m 3s	remaining: 1m 24s
700:	test: 0.6106164	best: 0.6323300 (105)	total: 1m 14s	remaining: 1m 13s
800:	test: 0.6058953	best: 0.6323300 (105)	total: 1m 25s	remaining: 1m 3s
900:	test: 0.5993159	best: 0.6323300 (105)	total: 1m 35s	remaining: 53.1s
1000:	test: 0.5961802	best: 0.6323300 (105)	total: 1m 46s	remaining: 42.6s
1100:	test: 0.5912080	best: 0.6323300 (105)	total: 1m 57s	remaining: 32s
1200:	test: 0.5895383	best: 0.6323300 (105)	total: 2m 8s	remaining: 21.3s
1300:	test: 0.5838735	best: 0.6323300 (105)	total: 2m 19s	remaining: 10.6s
1399:	test: 0.5819649	best: 0.6323300 (105)	total: 2m 30s	remaining: 0us
bestTest = 0.6323299706
bestIteration = 105
Shrink model to first 106 iterations.

[I 2026-04-05 08:30:29,719] Trial 1 finished with value: 0.6323300606620056 and parameters: {'depth': 9, 'learning_rate': 0.11908339521008107, 'l2_leaf_reg': 4.358561154277121, 'iterations': 1400}. Best is trial 0 with value: 0.6344771303656871.

[CatBoost|seed=123] trial=1 auc=0.632330 train_time=154.61s
[Optuna] Trial 001 | value=0.632330 | params={'depth': 9, 'learning_rate': 0.11908339521008107, 'l2_leaf_reg': 4.358561154277121, 'iterations': 1400}

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.5568979	best: 0.5568979 (0)	total: 112ms	remaining: 2m 3s
100:	test: 0.6252133	best: 0.6252133 (100)	total: 8.07s	remaining: 1m 19s
200:	test: 0.6297800	best: 0.6297800 (200)	total: 16.2s	remaining: 1m 12s
300:	test: 0.6312445	best: 0.6312445 (300)	total: 24.4s	remaining: 1m 4s
400:	test: 0.6321859	best: 0.6321859 (400)	total: 32.4s	remaining: 56.6s
500:	test: 0.6328770	best: 0.6328770 (500)	total: 40.5s	remaining: 48.4s
600:	test: 0.6331790	best: 0.6331858 (595)	total: 48.6s	remaining: 40.3s
700:	test: 0.6337108	best: 0.6337108 (700)	total: 56.9s	remaining: 32.4s
800:	test: 0.6340123	best: 0.6340241 (770)	total: 1m 5s	remaining: 24.3s
900:	test: 0.6342560	best: 0.6342560 (900)	total: 1m 13s	remaining: 16.2s
1000:	test: 0.6343380	best: 0.6343517 (965)	total: 1m 21s	remaining: 8.07s
1099:	test: 0.6344084	best: 0.6344290 (1095)	total: 1m 29s	remaining: 0us
bestTest = 0.634428978
bestIteration = 1095
Shrink model to first 1096 iterations.

[I 2026-04-05 08:32:05,059] Trial 2 finished with value: 0.6344288965534336 and parameters: {'depth': 8, 'learning_rate': 0.021437626313145525, 'l2_leaf_reg': 10.766824298827917, 'iterations': 1100}. Best is trial 0 with value: 0.6344771303656871.

[CatBoost|seed=123] trial=2 auc=0.634429 train_time=95.31s
[Optuna] Trial 002 | value=0.634429 | params={'depth': 8, 'learning_rate': 0.021437626313145525, 'l2_leaf_reg': 10.766824298827917, 'iterations': 1100}

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.5568943	best: 0.5568943 (0)	total: 110ms	remaining: 1m 38s
100:	test: 0.6331960	best: 0.6332380 (95)	total: 9.91s	remaining: 1m 18s
200:	test: 0.6344295	best: 0.6347990 (185)	total: 20s	remaining: 1m 9s
300:	test: 0.6337744	best: 0.6347990 (185)	total: 30.5s	remaining: 1m
400:	test: 0.6330010	best: 0.6347990 (185)	total: 41.1s	remaining: 51.1s
500:	test: 0.6311159	best: 0.6347990 (185)	total: 51.6s	remaining: 41.1s
600:	test: 0.6292270	best: 0.6347990 (185)	total: 1m 2s	remaining: 30.9s
700:	test: 0.6265972	best: 0.6347990 (185)	total: 1m 12s	remaining: 20.6s
800:	test: 0.6247197	best: 0.6347990 (185)	total: 1m 23s	remaining: 10.3s
899:	test: 0.6219955	best: 0.6347990 (185)	total: 1m 33s	remaining: 0us
bestTest = 0.6347990334
bestIteration = 185
Shrink model to first 186 iterations.

[I 2026-04-05 08:33:42,959] Trial 3 finished with value: 0.6347990467587409 and parameters: {'depth': 9, 'learning_rate': 0.10639734290938918, 'l2_leaf_reg': 18.84375791835453, 'iterations': 900}. Best is trial 3 with value: 0.6347990467587409.

[CatBoost|seed=123] trial=3 auc=0.634799 train_time=97.87s
[Optuna] Trial 003 | value=0.634799 | params={'depth': 9, 'learning_rate': 0.10639734290938918, 'l2_leaf_reg': 18.84375791835453, 'iterations': 900}

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.5568943	best: 0.5568943 (0)	total: 110ms	remaining: 44s
100:	test: 0.6306416	best: 0.6311527 (70)	total: 10.1s	remaining: 29.8s
200:	test: 0.6266927	best: 0.6311527 (70)	total: 20.6s	remaining: 20.4s
300:	test: 0.6230064	best: 0.6311527 (70)	total: 31.2s	remaining: 10.3s
399:	test: 0.6164310	best: 0.6311527 (70)	total: 41.8s	remaining: 0us
bestTest = 0.6311526597
bestIteration = 70
Shrink model to first 71 iterations.

[I 2026-04-05 08:34:28,381] Trial 4 finished with value: 0.631152724460142 and parameters: {'depth': 9, 'learning_rate': 0.2058572386400141, 'l2_leaf_reg': 18.198889930306258, 'iterations': 400}. Best is trial 3 with value: 0.6347990467587409.

[CatBoost|seed=123] trial=4 auc=0.631153 train_time=45.39s
[Optuna] Trial 004 | value=0.631153 | params={'depth': 9, 'learning_rate': 0.2058572386400141, 'l2_leaf_reg': 18.198889930306258, 'iterations': 400}
[BEST] CatBoost seed=123 best_auc(valid)=0.634799
[BEST] params={'depth': 9, 'learning_rate': 0.10639734290938918, 'l2_leaf_reg': 18.84375791835453, 'iterations': 900}

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.5568943	best: 0.5568943 (0)	total: 111ms	remaining: 1m 39s
100:	test: 0.6334201	best: 0.6334201 (100)	total: 9.88s	remaining: 1m 18s
200:	test: 0.6344734	best: 0.6344734 (200)	total: 20s	remaining: 1m 9s
300:	test: 0.6336942	best: 0.6344734 (200)	total: 30.3s	remaining: 1m
400:	test: 0.6314508	best: 0.6344734 (200)	total: 40.9s	remaining: 50.9s
500:	test: 0.6307753	best: 0.6344734 (200)	total: 51.3s	remaining: 40.9s
600:	test: 0.6280698	best: 0.6344734 (200)	total: 1m 1s	remaining: 30.8s
700:	test: 0.6256618	best: 0.6344734 (200)	total: 1m 12s	remaining: 20.6s
800:	test: 0.6223654	best: 0.6344734 (200)	total: 1m 23s	remaining: 10.3s
899:	test: 0.6191841	best: 0.6344734 (200)	total: 1m 33s	remaining: 0us
bestTest = 0.634473443
bestIteration = 200
Shrink model to first 201 iterations.
[CKPT] Saved CatBoost seed=123 -> artifacts/checkpoints/CatBoost_seed123

==================== CatBoost | seed=456 ====================

[I 2026-04-05 08:36:17,771] A new study created in memory with name: no-name-dab8861f-3adf-4081-8c33-ccfa69fae679
Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.5492852	best: 0.5492852 (0)	total: 50.3ms	remaining: 1m 15s
100:	test: 0.6296349	best: 0.6296349 (100)	total: 3.64s	remaining: 50.5s
200:	test: 0.6319215	best: 0.6319215 (200)	total: 7.19s	remaining: 46.5s
300:	test: 0.6328320	best: 0.6328847 (290)	total: 10.8s	remaining: 43s
400:	test: 0.6337475	best: 0.6337475 (400)	total: 14.4s	remaining: 39.5s
500:	test: 0.6336200	best: 0.6338117 (445)	total: 18s	remaining: 36s
600:	test: 0.6338145	best: 0.6338145 (600)	total: 21.7s	remaining: 32.5s
700:	test: 0.6335814	best: 0.6338256 (605)	total: 25.4s	remaining: 29s
800:	test: 0.6336485	best: 0.6338256 (605)	total: 29.1s	remaining: 25.4s
900:	test: 0.6336426	best: 0.6338859 (830)	total: 32.8s	remaining: 21.8s
1000:	test: 0.6334141	best: 0.6338859 (830)	total: 36.4s	remaining: 18.1s
1100:	test: 0.6336606	best: 0.6338859 (830)	total: 40s	remaining: 14.5s
1200:	test: 0.6338081	best: 0.6338859 (830)	total: 43.7s	remaining: 10.9s
1300:	test: 0.6338831	best: 0.6339481 (1295)	total: 47.3s	remaining: 7.24s
1400:	test: 0.6342014	best: 0.6342705 (1395)	total: 50.9s	remaining: 3.6s
1499:	test: 0.6338007	best: 0.6342705 (1395)	total: 54.4s	remaining: 0us
bestTest = 0.6342704594
bestIteration = 1395
Shrink model to first 1396 iterations.

[I 2026-04-05 08:37:16,599] Trial 0 finished with value: 0.634270476026859 and parameters: {'depth': 4, 'learning_rate': 0.07657915289880192, 'l2_leaf_reg': 1.4718950321842255, 'iterations': 1500}. Best is trial 0 with value: 0.634270476026859.

[CatBoost|seed=456] trial=0 auc=0.634270 train_time=58.80s
[Optuna] Trial 000 | value=0.634270 | params={'depth': 4, 'learning_rate': 0.07657915289880192, 'l2_leaf_reg': 1.4718950321842255, 'iterations': 1500}

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.5647373	best: 0.5647373 (0)	total: 100ms	remaining: 3m 10s
100:	test: 0.6307411	best: 0.6307411 (100)	total: 6.57s	remaining: 1m 57s
200:	test: 0.6323436	best: 0.6323436 (200)	total: 13.2s	remaining: 1m 51s
300:	test: 0.6335711	best: 0.6335711 (300)	total: 19.9s	remaining: 1m 45s
400:	test: 0.6340007	best: 0.6340493 (395)	total: 26.5s	remaining: 1m 39s
500:	test: 0.6342649	best: 0.6343424 (445)	total: 33.3s	remaining: 1m 32s
600:	test: 0.6346515	best: 0.6347647 (580)	total: 40.1s	remaining: 1m 26s
700:	test: 0.6347222	best: 0.6349243 (655)	total: 46.8s	remaining: 1m 20s
800:	test: 0.6348190	best: 0.6349243 (655)	total: 53.5s	remaining: 1m 13s
900:	test: 0.6347290	best: 0.6349243 (655)	total: 1m	remaining: 1m 6s
1000:	test: 0.6344934	best: 0.6349243 (655)	total: 1m 6s	remaining: 1m
1100:	test: 0.6342818	best: 0.6349243 (655)	total: 1m 13s	remaining: 53.5s
1200:	test: 0.6344244	best: 0.6349243 (655)	total: 1m 20s	remaining: 46.9s
1300:	test: 0.6340144	best: 0.6349243 (655)	total: 1m 27s	remaining: 40.2s
1400:	test: 0.6337896	best: 0.6349243 (655)	total: 1m 34s	remaining: 33.5s
1500:	test: 0.6331111	best: 0.6349243 (655)	total: 1m 41s	remaining: 26.9s
1600:	test: 0.6326643	best: 0.6349243 (655)	total: 1m 47s	remaining: 20.1s
1700:	test: 0.6322227	best: 0.6349243 (655)	total: 1m 54s	remaining: 13.4s
1800:	test: 0.6316405	best: 0.6349243 (655)	total: 2m 1s	remaining: 6.69s
1899:	test: 0.6316456	best: 0.6349243 (655)	total: 2m 8s	remaining: 0us
bestTest = 0.6349242628
bestIteration = 655
Shrink model to first 656 iterations.

[I 2026-04-05 08:39:29,694] Trial 1 finished with value: 0.6349243047813061 and parameters: {'depth': 7, 'learning_rate': 0.05163082999694355, 'l2_leaf_reg': 9.945866706506287, 'iterations': 1900}. Best is trial 1 with value: 0.6349243047813061.

[CatBoost|seed=456] trial=1 auc=0.634924 train_time=133.07s
[Optuna] Trial 001 | value=0.634924 | params={'depth': 7, 'learning_rate': 0.05163082999694355, 'l2_leaf_reg': 9.945866706506287, 'iterations': 1900}

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.5658654	best: 0.5658654 (0)	total: 129ms	remaining: 1m 55s
100:	test: 0.6307198	best: 0.6307198 (100)	total: 8.24s	remaining: 1m 5s
200:	test: 0.6331223	best: 0.6331223 (200)	total: 16.3s	remaining: 56.6s
300:	test: 0.6344149	best: 0.6344537 (280)	total: 24.3s	remaining: 48.3s
400:	test: 0.6352331	best: 0.6352331 (400)	total: 32.5s	remaining: 40.4s
500:	test: 0.6350587	best: 0.6353576 (435)	total: 40.7s	remaining: 32.4s
600:	test: 0.6355512	best: 0.6355512 (600)	total: 49s	remaining: 24.4s
700:	test: 0.6350693	best: 0.6355512 (600)	total: 57.1s	remaining: 16.2s
800:	test: 0.6352385	best: 0.6355512 (600)	total: 1m 5s	remaining: 8.08s
899:	test: 0.6349694	best: 0.6355512 (600)	total: 1m 13s	remaining: 0us
bestTest = 0.6355511546
bestIteration = 600
Shrink model to first 601 iterations.

[I 2026-04-05 08:40:47,730] Trial 2 finished with value: 0.6355512197677313 and parameters: {'depth': 8, 'learning_rate': 0.04678677239810055, 'l2_leaf_reg': 14.94975333454759, 'iterations': 900}. Best is trial 2 with value: 0.6355512197677313.

[CatBoost|seed=456] trial=2 auc=0.635551 train_time=78.01s
[Optuna] Trial 002 | value=0.635551 | params={'depth': 8, 'learning_rate': 0.04678677239810055, 'l2_leaf_reg': 14.94975333454759, 'iterations': 900}

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.5614381	best: 0.5614381 (0)	total: 81.3ms	remaining: 1m 45s
100:	test: 0.6319970	best: 0.6319970 (100)	total: 5.57s	remaining: 1m 6s
200:	test: 0.6327538	best: 0.6330718 (155)	total: 11.1s	remaining: 1m
300:	test: 0.6329594	best: 0.6333363 (250)	total: 16.6s	remaining: 55.2s
400:	test: 0.6333206	best: 0.6334087 (345)	total: 22.2s	remaining: 49.8s
500:	test: 0.6324871	best: 0.6334963 (425)	total: 27.9s	remaining: 44.6s
600:	test: 0.6325648	best: 0.6334963 (425)	total: 33.6s	remaining: 39s
700:	test: 0.6321051	best: 0.6334963 (425)	total: 39.2s	remaining: 33.5s
800:	test: 0.6313381	best: 0.6334963 (425)	total: 44.8s	remaining: 27.9s
900:	test: 0.6307784	best: 0.6334963 (425)	total: 50.5s	remaining: 22.4s
1000:	test: 0.6297145	best: 0.6334963 (425)	total: 56.1s	remaining: 16.8s
1100:	test: 0.6295147	best: 0.6334963 (425)	total: 1m 1s	remaining: 11.2s
1200:	test: 0.6286289	best: 0.6334963 (425)	total: 1m 7s	remaining: 5.56s
1299:	test: 0.6280962	best: 0.6334963 (425)	total: 1m 13s	remaining: 0us
bestTest = 0.6334962547
bestIteration = 425
Shrink model to first 426 iterations.

[I 2026-04-05 08:42:04,747] Trial 3 finished with value: 0.6334962797396835 and parameters: {'depth': 6, 'learning_rate': 0.10366836985553907, 'l2_leaf_reg': 7.905369975059296, 'iterations': 1300}. Best is trial 2 with value: 0.6355512197677313.

[CatBoost|seed=456] trial=3 auc=0.633496 train_time=76.99s
[Optuna] Trial 003 | value=0.633496 | params={'depth': 6, 'learning_rate': 0.10366836985553907, 'l2_leaf_reg': 7.905369975059296, 'iterations': 1300}

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.5583656	best: 0.5583656 (0)	total: 64.2ms	remaining: 2m 1s
100:	test: 0.6206297	best: 0.6206297 (100)	total: 4.49s	remaining: 1m 19s
200:	test: 0.6256234	best: 0.6256234 (200)	total: 8.9s	remaining: 1m 15s
300:	test: 0.6281387	best: 0.6281387 (300)	total: 13.4s	remaining: 1m 11s
400:	test: 0.6296683	best: 0.6296683 (400)	total: 18s	remaining: 1m 7s
500:	test: 0.6306860	best: 0.6306860 (500)	total: 22.4s	remaining: 1m 2s
600:	test: 0.6311469	best: 0.6311475 (590)	total: 26.9s	remaining: 58.1s
700:	test: 0.6316199	best: 0.6316199 (700)	total: 31.4s	remaining: 53.7s
800:	test: 0.6319743	best: 0.6319743 (800)	total: 35.9s	remaining: 49.3s
900:	test: 0.6323797	best: 0.6323797 (900)	total: 40.4s	remaining: 44.8s
1000:	test: 0.6328039	best: 0.6328039 (1000)	total: 45s	remaining: 40.4s
1100:	test: 0.6330549	best: 0.6330549 (1100)	total: 49.6s	remaining: 36s
1200:	test: 0.6333100	best: 0.6333136 (1195)	total: 54.1s	remaining: 31.5s
1300:	test: 0.6335894	best: 0.6335988 (1285)	total: 58.8s	remaining: 27.1s
1400:	test: 0.6337515	best: 0.6337515 (1400)	total: 1m 3s	remaining: 22.6s
1500:	test: 0.6339097	best: 0.6339265 (1480)	total: 1m 7s	remaining: 18s
1600:	test: 0.6340615	best: 0.6340661 (1595)	total: 1m 12s	remaining: 13.5s
1700:	test: 0.6342135	best: 0.6342237 (1675)	total: 1m 16s	remaining: 9s
1800:	test: 0.6343817	best: 0.6343817 (1800)	total: 1m 21s	remaining: 4.48s
1899:	test: 0.6344598	best: 0.6344598 (1899)	total: 1m 26s	remaining: 0us
bestTest = 0.6344597936
bestIteration = 1899

[I 2026-04-05 08:43:35,813] Trial 4 finished with value: 0.6344598629582677 and parameters: {'depth': 5, 'learning_rate': 0.01395457805520438, 'l2_leaf_reg': 16.490126215151165, 'iterations': 1900}. Best is trial 2 with value: 0.6355512197677313.

[CatBoost|seed=456] trial=4 auc=0.634460 train_time=91.04s
[Optuna] Trial 004 | value=0.634460 | params={'depth': 5, 'learning_rate': 0.01395457805520438, 'l2_leaf_reg': 16.490126215151165, 'iterations': 1900}
[BEST] CatBoost seed=456 best_auc(valid)=0.635551
[BEST] params={'depth': 8, 'learning_rate': 0.04678677239810055, 'l2_leaf_reg': 14.94975333454759, 'iterations': 900}

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.5658654	best: 0.5658654 (0)	total: 129ms	remaining: 1m 55s
100:	test: 0.6307198	best: 0.6307198 (100)	total: 8.23s	remaining: 1m 5s
200:	test: 0.6331215	best: 0.6331215 (200)	total: 16.2s	remaining: 56.5s
300:	test: 0.6344814	best: 0.6344978 (285)	total: 24.2s	remaining: 48.1s
400:	test: 0.6352592	best: 0.6352592 (400)	total: 32.4s	remaining: 40.4s
500:	test: 0.6351233	best: 0.6353600 (440)	total: 40.8s	remaining: 32.5s
600:	test: 0.6355689	best: 0.6355689 (600)	total: 49.1s	remaining: 24.4s
700:	test: 0.6353182	best: 0.6356214 (630)	total: 57.3s	remaining: 16.3s
800:	test: 0.6354384	best: 0.6356214 (630)	total: 1m 5s	remaining: 8.1s
899:	test: 0.6350712	best: 0.6356214 (630)	total: 1m 13s	remaining: 0us
bestTest = 0.6356213987
bestIteration = 630
Shrink model to first 631 iterations.
[CKPT] Saved CatBoost seed=456 -> artifacts/checkpoints/CatBoost_seed456

==================== CatBoost | seed=789 ====================

[I 2026-04-05 08:45:06,842] A new study created in memory with name: no-name-eaaa5aef-aef8-47f4-a9b1-6196f8e2b9b8
Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.5607904	best: 0.5607904 (0)	total: 202ms	remaining: 3m 22s
100:	test: 0.6239538	best: 0.6239538 (100)	total: 13.2s	remaining: 1m 57s
200:	test: 0.6278941	best: 0.6278941 (200)	total: 26.8s	remaining: 1m 46s
300:	test: 0.6306349	best: 0.6306349 (300)	total: 40.4s	remaining: 1m 33s
400:	test: 0.6324401	best: 0.6324401 (400)	total: 54s	remaining: 1m 20s
500:	test: 0.6334016	best: 0.6334016 (500)	total: 1m 7s	remaining: 1m 6s
600:	test: 0.6338983	best: 0.6338983 (600)	total: 1m 20s	remaining: 53.3s
700:	test: 0.6344517	best: 0.6344517 (700)	total: 1m 33s	remaining: 39.9s
800:	test: 0.6345794	best: 0.6345811 (780)	total: 1m 47s	remaining: 26.7s
900:	test: 0.6347923	best: 0.6347923 (900)	total: 2m	remaining: 13.3s
999:	test: 0.6352821	best: 0.6352821 (999)	total: 2m 14s	remaining: 0us
bestTest = 0.6352820992
bestIteration = 999

[I 2026-04-05 08:47:26,926] Trial 0 finished with value: 0.6352821182538283 and parameters: {'depth': 10, 'learning_rate': 0.012459911629562195, 'l2_leaf_reg': 11.896767510906313, 'iterations': 1000}. Best is trial 0 with value: 0.6352821182538283.

[CatBoost|seed=789] trial=0 auc=0.635282 train_time=140.05s
[Optuna] Trial 000 | value=0.635282 | params={'depth': 10, 'learning_rate': 0.012459911629562195, 'l2_leaf_reg': 11.896767510906313, 'iterations': 1000}

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.5546084	best: 0.5546084 (0)	total: 229ms	remaining: 4m 33s
100:	test: 0.6305532	best: 0.6305532 (100)	total: 13.7s	remaining: 2m 28s
200:	test: 0.6330348	best: 0.6330348 (200)	total: 27.1s	remaining: 2m 14s
300:	test: 0.6331769	best: 0.6332977 (210)	total: 40.9s	remaining: 2m 2s
400:	test: 0.6326934	best: 0.6332977 (210)	total: 55.1s	remaining: 1m 49s
500:	test: 0.6318783	best: 0.6332977 (210)	total: 1m 9s	remaining: 1m 36s
600:	test: 0.6301723	best: 0.6332977 (210)	total: 1m 23s	remaining: 1m 23s
700:	test: 0.6290912	best: 0.6332977 (210)	total: 1m 37s	remaining: 1m 9s
800:	test: 0.6257730	best: 0.6332977 (210)	total: 1m 51s	remaining: 55.7s
900:	test: 0.6228622	best: 0.6332977 (210)	total: 2m 6s	remaining: 41.9s
1000:	test: 0.6195205	best: 0.6332977 (210)	total: 2m 20s	remaining: 28s
1100:	test: 0.6159140	best: 0.6332977 (210)	total: 2m 35s	remaining: 14s
1199:	test: 0.6121704	best: 0.6332977 (210)	total: 2m 49s	remaining: 0us
bestTest = 0.6332976818
bestIteration = 210
Shrink model to first 211 iterations.

[I 2026-04-05 08:50:20,623] Trial 1 finished with value: 0.633297654323365 and parameters: {'depth': 10, 'learning_rate': 0.050213168505747814, 'l2_leaf_reg': 3.841601864893353, 'iterations': 1200}. Best is trial 0 with value: 0.6352821182538283.

[CatBoost|seed=789] trial=1 auc=0.633298 train_time=173.67s
[Optuna] Trial 001 | value=0.633298 | params={'depth': 10, 'learning_rate': 0.050213168505747814, 'l2_leaf_reg': 3.841601864893353, 'iterations': 1200}

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.5546812	best: 0.5546812 (0)	total: 164ms	remaining: 4m 6s
100:	test: 0.6325313	best: 0.6325317 (95)	total: 10.4s	remaining: 2m 23s
200:	test: 0.6311376	best: 0.6332458 (110)	total: 20.9s	remaining: 2m 14s
300:	test: 0.6284397	best: 0.6332458 (110)	total: 31.4s	remaining: 2m 5s
400:	test: 0.6260280	best: 0.6332458 (110)	total: 42.1s	remaining: 1m 55s
500:	test: 0.6222980	best: 0.6332458 (110)	total: 52.9s	remaining: 1m 45s
600:	test: 0.6175503	best: 0.6332458 (110)	total: 1m 3s	remaining: 1m 35s
700:	test: 0.6141598	best: 0.6332458 (110)	total: 1m 14s	remaining: 1m 24s
800:	test: 0.6064051	best: 0.6332458 (110)	total: 1m 25s	remaining: 1m 14s
900:	test: 0.6004739	best: 0.6332458 (110)	total: 1m 36s	remaining: 1m 4s
1000:	test: 0.5940050	best: 0.6332458 (110)	total: 1m 47s	remaining: 53.5s
1100:	test: 0.5890357	best: 0.6332458 (110)	total: 1m 58s	remaining: 42.9s
1200:	test: 0.5846239	best: 0.6332458 (110)	total: 2m 9s	remaining: 32.2s
1300:	test: 0.5806762	best: 0.6332458 (110)	total: 2m 20s	remaining: 21.5s
1400:	test: 0.5780149	best: 0.6332458 (110)	total: 2m 31s	remaining: 10.7s
1499:	test: 0.5732845	best: 0.6332458 (110)	total: 2m 42s	remaining: 0us
bestTest = 0.6332458258
bestIteration = 110
Shrink model to first 111 iterations.

[I 2026-04-05 08:53:06,908] Trial 2 finished with value: 0.6332459204152626 and parameters: {'depth': 9, 'learning_rate': 0.1421834483392859, 'l2_leaf_reg': 7.022247577865779, 'iterations': 1500}. Best is trial 0 with value: 0.6352821182538283.

[CatBoost|seed=789] trial=2 auc=0.633246 train_time=166.25s
[Optuna] Trial 002 | value=0.633246 | params={'depth': 9, 'learning_rate': 0.1421834483392859, 'l2_leaf_reg': 7.022247577865779, 'iterations': 1500}

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.5616516	best: 0.5616516 (0)	total: 63.3ms	remaining: 37.9s
100:	test: 0.6222768	best: 0.6222768 (100)	total: 4.58s	remaining: 22.6s
200:	test: 0.6270857	best: 0.6270857 (200)	total: 9.09s	remaining: 18s
300:	test: 0.6290202	best: 0.6290202 (300)	total: 13.7s	remaining: 13.6s
400:	test: 0.6302457	best: 0.6302457 (400)	total: 18.3s	remaining: 9.09s
500:	test: 0.6310336	best: 0.6310336 (500)	total: 22.9s	remaining: 4.52s
599:	test: 0.6313685	best: 0.6313685 (599)	total: 27.4s	remaining: 0us
bestTest = 0.6313685477
bestIteration = 599

[I 2026-04-05 08:53:38,333] Trial 3 finished with value: 0.6313685228496062 and parameters: {'depth': 5, 'learning_rate': 0.01799181503604012, 'l2_leaf_reg': 11.317994260762886, 'iterations': 600}. Best is trial 0 with value: 0.6352821182538283.

[CatBoost|seed=789] trial=3 auc=0.631369 train_time=31.40s
[Optuna] Trial 003 | value=0.631369 | params={'depth': 5, 'learning_rate': 0.01799181503604012, 'l2_leaf_reg': 11.317994260762886, 'iterations': 600}

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.5606989	best: 0.5606989 (0)	total: 164ms	remaining: 1m 37s
100:	test: 0.6305565	best: 0.6308137 (95)	total: 10.1s	remaining: 50s
200:	test: 0.6302477	best: 0.6309150 (105)	total: 20.5s	remaining: 40.7s
300:	test: 0.6275191	best: 0.6309150 (105)	total: 31.1s	remaining: 30.9s
400:	test: 0.6220148	best: 0.6309150 (105)	total: 41.8s	remaining: 20.7s
500:	test: 0.6181541	best: 0.6309150 (105)	total: 52.5s	remaining: 10.4s
599:	test: 0.6149572	best: 0.6309150 (105)	total: 1m 3s	remaining: 0us
bestTest = 0.6309149861
bestIteration = 105
Shrink model to first 106 iterations.

[I 2026-04-05 08:54:45,166] Trial 4 finished with value: 0.630915009282206 and parameters: {'depth': 9, 'learning_rate': 0.14166609037852596, 'l2_leaf_reg': 11.851226387059095, 'iterations': 600}. Best is trial 0 with value: 0.6352821182538283.

[CatBoost|seed=789] trial=4 auc=0.630915 train_time=66.80s
[Optuna] Trial 004 | value=0.630915 | params={'depth': 9, 'learning_rate': 0.14166609037852596, 'l2_leaf_reg': 11.851226387059095, 'iterations': 600}
[BEST] CatBoost seed=789 best_auc(valid)=0.635282
[BEST] params={'depth': 10, 'learning_rate': 0.012459911629562195, 'l2_leaf_reg': 11.896767510906313, 'iterations': 1000}

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.5607904	best: 0.5607904 (0)	total: 204ms	remaining: 3m 23s
100:	test: 0.6239571	best: 0.6239571 (100)	total: 13.2s	remaining: 1m 57s
200:	test: 0.6278968	best: 0.6278968 (200)	total: 26.7s	remaining: 1m 46s
300:	test: 0.6307547	best: 0.6307547 (300)	total: 40s	remaining: 1m 32s
400:	test: 0.6323106	best: 0.6323106 (400)	total: 53.6s	remaining: 1m 20s
500:	test: 0.6332186	best: 0.6332186 (500)	total: 1m 6s	remaining: 1m 6s
600:	test: 0.6338102	best: 0.6338102 (600)	total: 1m 20s	remaining: 53.1s
700:	test: 0.6341583	best: 0.6341583 (700)	total: 1m 33s	remaining: 39.9s
800:	test: 0.6343452	best: 0.6343525 (760)	total: 1m 47s	remaining: 26.6s
900:	test: 0.6344573	best: 0.6344573 (900)	total: 2m	remaining: 13.3s
999:	test: 0.6349146	best: 0.6349146 (999)	total: 2m 14s	remaining: 0us
bestTest = 0.6349146068
bestIteration = 999
[CKPT] Saved CatBoost seed=789 -> artifacts/checkpoints/CatBoost_seed789
[RESUME] CatBoost best seed selected: 456

[SUMMARY] CatBoost
  - accuracy            : mean=0.963543, std=0.000000
  - auc_roc             : mean=0.636661, std=0.001076
  - f1                  : mean=0.000154, std=0.000217
  - train_seconds       : mean=114.065545, std=26.514790
  - infer_ms_per_sample : mean=0.014494, std=0.001728
  - model_size_mb       : mean=12.221758, std=9.385112

In [ ]:
# ===== 3.6 Deep Model Utilities: TabNet / FT-Transformer Preprocessing and Training =====
# FT-Transformer implementation package
try:
    from tab_transformer_pytorch import FTTransformer
except Exception:
    import subprocess, sys
    subprocess.check_call([sys.executable, "-m", "pip", "install", "tab-transformer-pytorch"])
    from tab_transformer_pytorch import FTTransformer

import torch
from torch import nn
from torch.utils.data import TensorDataset, DataLoader
DEVICE = "cpu" if FT_FORCE_CPU else ("cuda" if torch.cuda.is_available() else "cpu")
print(f"[INFO] Torch device: {DEVICE}")

def prepare_deep_inputs(Xtr_df, Xva_df, Xte_df):
    """Return encoded data that can be used by TabNet/FT-Transformer."""
    numbin_cols = num_cols + bin_cols
    # Numeric features: median imputation
    num_imputer = SimpleImputer(strategy="median")
    Xtr_num = num_imputer.fit_transform(Xtr_df[numbin_cols])
    Xva_num = num_imputer.transform(Xva_df[numbin_cols])
    Xte_num = num_imputer.transform(Xte_df[numbin_cols])

    # Categorical features: cast to string + missing placeholder + ordinal encoding (unknown -> -1, then +1)
    if len(cat_cols) > 0:
        tr_cat = Xtr_df[cat_cols].astype("string").fillna("MISSING")
        va_cat = Xva_df[cat_cols].astype("string").fillna("MISSING")
        te_cat = Xte_df[cat_cols].astype("string").fillna("MISSING")
        cat_encoder = OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1)
        Xtr_cat = cat_encoder.fit_transform(tr_cat).astype(np.int64) + 1
        Xva_cat = cat_encoder.transform(va_cat).astype(np.int64) + 1
        Xte_cat = cat_encoder.transform(te_cat).astype(np.int64) + 1
        cat_dims = [int(Xtr_cat[:, i].max() + 1) for i in range(Xtr_cat.shape[1])]
    else:
        Xtr_cat = np.zeros((len(Xtr_df), 0), dtype=np.int64)
        Xva_cat = np.zeros((len(Xva_df), 0), dtype=np.int64)
        Xte_cat = np.zeros((len(Xte_df), 0), dtype=np.int64)
        cat_dims = []
        cat_encoder = None

    bundle = {
        "Xtr_num": Xtr_num.astype(np.float32),
        "Xva_num": Xva_num.astype(np.float32),
        "Xte_num": Xte_num.astype(np.float32),
        "Xtr_cat": Xtr_cat,
        "Xva_cat": Xva_cat,
        "Xte_cat": Xte_cat,
        "cat_dims": cat_dims,
        "num_imputer": num_imputer,
        "cat_encoder": cat_encoder,
        "n_num": len(numbin_cols),
        "n_cat": len(cat_cols),
    }
    return bundle

def fit_fttransformer_once(bundle, ytr, yva, params, seed):
    torch.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)

    model = FTTransformer(
        categories=tuple(bundle["cat_dims"]),
        num_continuous=bundle["n_num"],
        dim=params["dim"],
        dim_out=1,
        depth=params["depth"],
        heads=params["heads"],
        attn_dropout=params["attn_dropout"],
        ff_dropout=params["ff_dropout"],
    ).to(DEVICE)

    optimizer = torch.optim.AdamW(model.parameters(), lr=params["lr"], weight_decay=params["weight_decay"])
    criterion = nn.BCEWithLogitsLoss()
    xtr_cat = torch.tensor(bundle["Xtr_cat"], dtype=torch.long)
    xtr_num = torch.tensor(bundle["Xtr_num"], dtype=torch.float32)
    ytr_t = torch.tensor(np.asarray(ytr).reshape(-1, 1), dtype=torch.float32)
    train_ds = TensorDataset(xtr_cat, xtr_num, ytr_t)
    train_loader = DataLoader(train_ds, batch_size=params["batch_size"], shuffle=True)
    xva_cat = torch.tensor(bundle["Xva_cat"], dtype=torch.long, device=DEVICE)
    xva_num = torch.tensor(bundle["Xva_num"], dtype=torch.float32, device=DEVICE)
    yva_np = np.asarray(yva).astype(int)
    best_auc = -np.inf
    best_state = None
    no_improve = 0

    for epoch in range(1, params["epochs"] + 1):
        model.train()
        running_loss = 0.0
        for bc, bn, by in train_loader:
            bc = bc.to(DEVICE)
            bn = bn.to(DEVICE)
            by = by.to(DEVICE)

            optimizer.zero_grad()
            logits = model(bc, bn)
            loss = criterion(logits, by)
            loss.backward()
            optimizer.step()
            running_loss += loss.item() * len(by)
        model.eval()
        with torch.no_grad():
            logits_va = model(xva_cat, xva_num).squeeze(1)
            prob_va = torch.sigmoid(logits_va).detach().cpu().numpy()
        auc_va = roc_auc_score(yva_np, prob_va)
        avg_loss = running_loss / len(train_ds)

        print(f"[FTTransformer|seed={seed}] epoch={epoch:03d} loss={avg_loss:.6f} valid_auc={auc_va:.6f}")

        if auc_va > best_auc:
            best_auc = auc_va
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
            no_improve = 0
        else:
            no_improve += 1

        if no_improve >= params["patience"]:
            print(f"[FTTransformer|seed={seed}] Early stopping at epoch {epoch}")
            break

    if best_state is not None:
        model.load_state_dict(best_state)

    return model, float(best_auc)

def ft_predict_proba(model, X_cat, X_num, batch_size=2048):
    model.eval()
    probs = []
    n = len(X_num)
    with torch.no_grad():
        for i in range(0, n, batch_size):
            bc = torch.tensor(X_cat[i:i+batch_size], dtype=torch.long, device=DEVICE)
            bn = torch.tensor(X_num[i:i+batch_size], dtype=torch.float32, device=DEVICE)
            logits = model(bc, bn).squeeze(1)
            probs.append(torch.sigmoid(logits).detach().cpu().numpy())
    return np.concatenate(probs, axis=0)

[INFO] Torch device: cuda

In [ ]:
# ===== 3.6 TabNet (checkpoint resume supported) =====
def run_tabnet_experiment(n_trials=N_TRIALS, seeds=SEEDS):
    import joblib
    model_name = "TabNet"
    seed_results = []

    for seed in seeds:
        paths = get_seed_ckpt_paths(model_name, seed)
        cached_meta = load_seed_meta(model_name, seed)
        if cached_meta is not None and paths["tabnet_zip"].exists() and paths["bundle_joblib"].exists():
            cached_metrics = cached_meta.get("metrics", {})
            if "seed" not in cached_metrics:
                cached_metrics["seed"] = int(seed)
            print(f"[RESUME] {model_name} seed={seed} loaded from checkpoint, skip training")
            seed_results.append(cached_metrics)
            continue

        print(f"\n{'='*20} {model_name} | seed={seed} {'='*20}")
        np.random.seed(seed)
        random.seed(seed)
        torch.manual_seed(seed)
        X_train_seed = X_train
        y_train_seed = y_train
        X_valid_seed = X_valid
        y_valid_seed = y_valid

        if MAX_TRAIN_ROWS is not None and len(X_train_seed) > MAX_TRAIN_ROWS:
            idx = X_train_seed.sample(n=MAX_TRAIN_ROWS, random_state=seed).index
            X_train_seed = X_train_seed.loc[idx]
            y_train_seed = y_train_seed.loc[idx]

        if MAX_VALID_ROWS is not None and len(X_valid_seed) > MAX_VALID_ROWS:
            idx = X_valid_seed.sample(n=MAX_VALID_ROWS, random_state=seed).index
            X_valid_seed = X_valid_seed.loc[idx]
            y_valid_seed = y_valid_seed.loc[idx]

        bundle = prepare_deep_inputs(X_train_seed, X_valid_seed, X_test)
        Xtr_tab = np.hstack([bundle["Xtr_num"], bundle["Xtr_cat"]]).astype(np.float32)
        Xva_tab = np.hstack([bundle["Xva_num"], bundle["Xva_cat"]]).astype(np.float32)
        Xte_tab = np.hstack([bundle["Xte_num"], bundle["Xte_cat"]]).astype(np.float32)
        cat_idxs = list(range(bundle["n_num"], bundle["n_num"] + bundle["n_cat"]))
        cat_dims = bundle["cat_dims"]
        ytr_np = y_train_seed.values
        yva_np = y_valid_seed.values
        yte_np = y_test.values

        def objective(trial):
            params = {
                "n_d": trial.suggest_int("n_d", 8, 64, step=8),
                "n_a": trial.suggest_int("n_a", 8, 64, step=8),
                "n_steps": trial.suggest_int("n_steps", 3, 8),
                "gamma": trial.suggest_float("gamma", 1.0, 2.0),
                "lambda_sparse": trial.suggest_float("lambda_sparse", 1e-7, 1e-2, log=True),
                "lr": trial.suggest_float("lr", 1e-4, 5e-2, log=True),
                "batch_size": trial.suggest_categorical("batch_size", [1024, 2048, 4096]),
                "virtual_batch_size": trial.suggest_categorical("virtual_batch_size", [128, 256, 512]),
            }

            model = TabNetClassifier(
                n_d=params["n_d"],
                n_a=params["n_a"],
                n_steps=params["n_steps"],
                gamma=params["gamma"],
                lambda_sparse=params["lambda_sparse"],
                cat_idxs=cat_idxs,
                cat_dims=cat_dims,
                optimizer_fn=torch.optim.Adam,
                optimizer_params=dict(lr=params["lr"]),
                seed=seed,
                verbose=10,
                device_name="cuda" if USE_GPU else "cpu",
            )

            t0 = time.perf_counter()
            model.fit(
                X_train=Xtr_tab, y_train=ytr_np,
                eval_set=[(Xva_tab, yva_np)],
                eval_name=["valid"],
                eval_metric=["auc"],
                max_epochs=TABNET_MAX_EPOCHS,
                patience=min(12, max(5, TABNET_MAX_EPOCHS // 4)),
                batch_size=params["batch_size"],
                virtual_batch_size=params["virtual_batch_size"],
                drop_last=False,
            )
            t1 = time.perf_counter()
            yva_prob = model.predict_proba(Xva_tab)[:, 1]
            auc = roc_auc_score(yva_np, yva_prob)
            print(f"[TabNet|seed={seed}] trial={trial.number} auc={auc:.6f} train_time={t1-t0:.2f}s")
            return auc

        study = optuna.create_study(direction="maximize")
        study.optimize(objective, n_trials=n_trials, callbacks=[optuna_log_callback])
        best_params = study.best_trial.params
        print(f"[BEST] TabNet seed={seed} best_valid_auc={study.best_value:.6f}")
        print(f"[BEST] params={best_params}")

        final_model = TabNetClassifier(
            n_d=best_params["n_d"],
            n_a=best_params["n_a"],
            n_steps=best_params["n_steps"],
            gamma=best_params["gamma"],
            lambda_sparse=best_params["lambda_sparse"],
            cat_idxs=cat_idxs,
            cat_dims=cat_dims,
            optimizer_fn=torch.optim.Adam,
            optimizer_params=dict(lr=best_params["lr"]),
            seed=seed,
            verbose=10,
            device_name="cuda" if USE_GPU else "cpu",
        )

        t0 = time.perf_counter()
        final_model.fit(
            X_train=Xtr_tab, y_train=ytr_np,
            eval_set=[(Xva_tab, yva_np)],
            eval_name=["valid"],
            eval_metric=["auc"],
            max_epochs=TABNET_MAX_EPOCHS,
            patience=min(12, max(5, TABNET_MAX_EPOCHS // 4)),
            batch_size=best_params["batch_size"],
            virtual_batch_size=best_params["virtual_batch_size"],
            drop_last=False,
        )
        y_prob_test = final_model.predict_proba(Xte_tab)[:, 1]
        t1 = time.perf_counter()

        m = evaluate_predictions(yte_np, y_prob_test)
        m["seed"] = int(seed)
        m["train_seconds"] = float(t1 - t0)

        # Inference latency benchmarking
        lat_list = []
        for _ in range(INFER_REPEAT):
            start = time.perf_counter()
            _ = final_model.predict_proba(Xte_tab)[:, 1]
            end = time.perf_counter()
            lat_list.append((end - start) / len(Xte_tab) * 1000)
        m["infer_ms_per_sample"] = float(np.mean(lat_list))
        m["infer_ms_per_sample_std"] = float(np.std(lat_list))

        # Save model checkpoint files
        save_prefix = str(paths["dir"] / "tabnet_model")
        saved_path = final_model.save_model(save_prefix)
        zip_path = Path(saved_path if str(saved_path).endswith(".zip") else f"{saved_path}.zip")
        if not zip_path.exists():
            zip_path = paths["tabnet_zip"]

        # Compatibility fallback: ensure standard path exists
        if zip_path != paths["tabnet_zip"] and zip_path.exists():
            import shutil
            shutil.copy2(zip_path, paths["tabnet_zip"] )
            zip_path = paths["tabnet_zip"]

        m["model_size_mb"] = float(os.path.getsize(zip_path) / (1024 * 1024))
        m["best_valid_auc"] = float(study.best_value)
        m["best_params"] = best_params
        seed_results.append(m)

        compact_bundle = compact_deep_bundle(bundle)
        joblib.dump(compact_bundle, paths["bundle_joblib"])
        save_seed_meta(
            model_name,
            seed,
            {
                "model_name": model_name,
                "seed": int(seed),
                "format": "tabnet",
                "metrics": m,
                "best_params": best_params,
                "model_zip": str(zip_path),
            },
        )
        print(f"[CKPT] Saved {model_name} seed={seed} -> {paths['dir']}")
        gc.collect()

    if len(seed_results) == 0:
        raise RuntimeError("No TabNet seed results found")

    all_results[model_name] = seed_results

    # Restore model object from best-seed checkpoint
    best_seed = int(max(seed_results, key=lambda r: r["auc_roc"])["seed"])
    best_paths = get_seed_ckpt_paths(model_name, best_seed)
    best_meta = load_seed_meta(model_name, best_seed)
    best_zip = Path(best_meta.get("model_zip", best_paths["tabnet_zip"]))

    best_model = TabNetClassifier()
    best_model.load_model(str(best_zip))

    compact_bundle = joblib.load(best_paths["bundle_joblib"])
    infer_bundle = build_deep_infer_bundle_from_compact(compact_bundle, X_test)

    best_models[model_name] = best_model
    best_preprocessors[model_name] = infer_bundle
    print(f"[RESUME] {model_name} best seed selected: {best_seed}")
    print_seed_metrics(model_name, seed_results)

run_tabnet_experiment()

==================== TabNet | seed=123 ====================

[I 2026-04-05 08:57:26,462] A new study created in memory with name: no-name-169778e8-50eb-4d8d-96ce-35639eea1434

epoch 0  | loss: 0.19187 | valid_auc: 0.5076  |  0:00:16s
epoch 10 | loss: 0.15586 | valid_auc: 0.5684  |  0:02:52s
epoch 20 | loss: 0.15491 | valid_auc: 0.58348 |  0:05:28s
epoch 30 | loss: 0.15439 | valid_auc: 0.59469 |  0:08:04s
epoch 40 | loss: 0.15409 | valid_auc: 0.59716 |  0:10:38s

Early stopping occurred at epoch 45 with best_epoch = 33 and best_valid_auc = 0.59998

[I 2026-04-05 09:09:53,709] Trial 0 finished with value: 0.5999808648032001 and parameters: {'n_d': 48, 'n_a': 64, 'n_steps': 4, 'gamma': 1.6320252002240783, 'lambda_sparse': 7.700428898922044e-05, 'lr': 0.0023332121502140425, 'batch_size': 2048, 'virtual_batch_size': 128}. Best is trial 0 with value: 0.5999808648032001.

[TabNet|seed=123] trial=0 auc=0.599981 train_time=745.11s
[Optuna] Trial 000 | value=0.599981 | params={'n_d': 48, 'n_a': 64, 'n_steps': 4, 'gamma': 1.6320252002240783, 'lambda_sparse': 7.700428898922044e-05, 'lr': 0.0023332121502140425, 'batch_size': 2048, 'virtual_batch_size': 128}
epoch 0  | loss: 0.20151 | valid_auc: 0.52673 |  0:00:14s
epoch 10 | loss: 0.15557 | valid_auc: 0.57615 |  0:02:38s
epoch 20 | loss: 0.15547 | valid_auc: 0.58275 |  0:05:03s
epoch 30 | loss: 0.15483 | valid_auc: 0.58601 |  0:07:26s
epoch 40 | loss: 0.15542 | valid_auc: 0.57754 |  0:09:51s

Early stopping occurred at epoch 40 with best_epoch = 28 and best_valid_auc = 0.59263

[I 2026-04-05 09:20:11,676] Trial 1 finished with value: 0.5926282685068431 and parameters: {'n_d': 40, 'n_a': 40, 'n_steps': 8, 'gamma': 1.6348618209068442, 'lambda_sparse': 1.9261906210018776e-05, 'lr': 0.022378830084117757, 'batch_size': 4096, 'virtual_batch_size': 256}. Best is trial 0 with value: 0.5999808648032001.

[TabNet|seed=123] trial=1 auc=0.592628 train_time=615.90s
[Optuna] Trial 001 | value=0.592628 | params={'n_d': 40, 'n_a': 40, 'n_steps': 8, 'gamma': 1.6348618209068442, 'lambda_sparse': 1.9261906210018776e-05, 'lr': 0.022378830084117757, 'batch_size': 4096, 'virtual_batch_size': 256}
epoch 0  | loss: 0.17388 | valid_auc: 0.52194 |  0:00:12s
epoch 10 | loss: 0.15502 | valid_auc: 0.58046 |  0:02:12s
epoch 20 | loss: 0.15465 | valid_auc: 0.59215 |  0:04:11s
epoch 30 | loss: 0.15444 | valid_auc: 0.58965 |  0:06:10s

Early stopping occurred at epoch 34 with best_epoch = 22 and best_valid_auc = 0.60072

[I 2026-04-05 09:27:43,129] Trial 2 finished with value: 0.600722871058462 and parameters: {'n_d': 8, 'n_a': 32, 'n_steps': 6, 'gamma': 1.3918216270075234, 'lambda_sparse': 0.00012934264834342442, 'lr': 0.006315153371937921, 'batch_size': 2048, 'virtual_batch_size': 512}. Best is trial 2 with value: 0.600722871058462.

[TabNet|seed=123] trial=2 auc=0.600723 train_time=449.80s
[Optuna] Trial 002 | value=0.600723 | params={'n_d': 8, 'n_a': 32, 'n_steps': 6, 'gamma': 1.3918216270075234, 'lambda_sparse': 0.00012934264834342442, 'lr': 0.006315153371937921, 'batch_size': 2048, 'virtual_batch_size': 512}
epoch 0  | loss: 0.30142 | valid_auc: 0.49642 |  0:00:15s
epoch 10 | loss: 0.15825 | valid_auc: 0.53069 |  0:02:49s
epoch 20 | loss: 0.15649 | valid_auc: 0.55063 |  0:05:21s
epoch 30 | loss: 0.15575 | valid_auc: 0.55916 |  0:07:54s
epoch 40 | loss: 0.15536 | valid_auc: 0.5703  |  0:10:26s
epoch 50 | loss: 0.15518 | valid_auc: 0.57178 |  0:12:58s
epoch 60 | loss: 0.15518 | valid_auc: 0.57451 |  0:15:30s
epoch 70 | loss: 0.15514 | valid_auc: 0.57265 |  0:18:03s

Early stopping occurred at epoch 74 with best_epoch = 62 and best_valid_auc = 0.57793

[I 2026-04-05 09:47:08,967] Trial 3 finished with value: 0.577934934447826 and parameters: {'n_d': 24, 'n_a': 24, 'n_steps': 5, 'gamma': 1.8773542480770842, 'lambda_sparse': 2.658078106715589e-06, 'lr': 0.0011878570041874844, 'batch_size': 4096, 'virtual_batch_size': 128}. Best is trial 2 with value: 0.600722871058462.

[TabNet|seed=123] trial=3 auc=0.577935 train_time=1163.67s
[Optuna] Trial 003 | value=0.577935 | params={'n_d': 24, 'n_a': 24, 'n_steps': 5, 'gamma': 1.8773542480770842, 'lambda_sparse': 2.658078106715589e-06, 'lr': 0.0011878570041874844, 'batch_size': 4096, 'virtual_batch_size': 128}
epoch 0  | loss: 0.18035 | valid_auc: 0.53394 |  0:00:27s
epoch 10 | loss: 0.15528 | valid_auc: 0.58504 |  0:05:01s
epoch 20 | loss: 0.15543 | valid_auc: 0.57515 |  0:09:35s
epoch 30 | loss: 0.15487 | valid_auc: 0.58665 |  0:14:08s
epoch 40 | loss: 0.15474 | valid_auc: 0.59599 |  0:18:41s

Early stopping occurred at epoch 47 with best_epoch = 35 and best_valid_auc = 0.59781

[I 2026-04-05 10:10:05,954] Trial 4 finished with value: 0.5978117266134365 and parameters: {'n_d': 16, 'n_a': 8, 'n_steps': 6, 'gamma': 1.3687297938025007, 'lambda_sparse': 3.009696429866067e-07, 'lr': 0.00565548604568021, 'batch_size': 1024, 'virtual_batch_size': 128}. Best is trial 2 with value: 0.600722871058462.

[TabNet|seed=123] trial=4 auc=0.597812 train_time=1373.09s
[Optuna] Trial 004 | value=0.597812 | params={'n_d': 16, 'n_a': 8, 'n_steps': 6, 'gamma': 1.3687297938025007, 'lambda_sparse': 3.009696429866067e-07, 'lr': 0.00565548604568021, 'batch_size': 1024, 'virtual_batch_size': 128}
[BEST] TabNet seed=123 best_valid_auc=0.600723
[BEST] params={'n_d': 8, 'n_a': 32, 'n_steps': 6, 'gamma': 1.3918216270075234, 'lambda_sparse': 0.00012934264834342442, 'lr': 0.006315153371937921, 'batch_size': 2048, 'virtual_batch_size': 512}
epoch 0  | loss: 0.17388 | valid_auc: 0.52194 |  0:00:11s
epoch 10 | loss: 0.15502 | valid_auc: 0.58046 |  0:02:09s
epoch 20 | loss: 0.15465 | valid_auc: 0.59215 |  0:04:07s
epoch 30 | loss: 0.15444 | valid_auc: 0.58965 |  0:06:05s

Early stopping occurred at epoch 34 with best_epoch = 22 and best_valid_auc = 0.60072
Successfully saved model at artifacts/checkpoints/TabNet_seed123/tabnet_model.zip
[CKPT] Saved TabNet seed=123 -> artifacts/checkpoints/TabNet_seed123

==================== TabNet | seed=456 ====================

[I 2026-04-05 10:17:48,846] A new study created in memory with name: no-name-390112e7-b1af-49a7-9fdc-f3c492fe8952

epoch 0  | loss: 0.28803 | valid_auc: 0.48995 |  0:00:13s
epoch 10 | loss: 0.16034 | valid_auc: 0.5273  |  0:02:33s
epoch 20 | loss: 0.15661 | valid_auc: 0.54634 |  0:04:53s
epoch 30 | loss: 0.15524 | valid_auc: 0.55454 |  0:07:12s
epoch 40 | loss: 0.15452 | valid_auc: 0.56198 |  0:09:32s
epoch 50 | loss: 0.15394 | valid_auc: 0.56282 |  0:11:50s
epoch 60 | loss: 0.15363 | valid_auc: 0.56891 |  0:14:09s
epoch 70 | loss: 0.15307 | valid_auc: 0.57219 |  0:16:29s
Stop training because you reached max_epochs = 80 with best_epoch = 78 and best_valid_auc = 0.58074

[I 2026-04-05 10:37:07,340] Trial 0 finished with value: 0.5807392727246075 and parameters: {'n_d': 56, 'n_a': 32, 'n_steps': 4, 'gamma': 1.1361989602530256, 'lambda_sparse': 2.9978714162737635e-05, 'lr': 0.00019833454295672853, 'batch_size': 1024, 'virtual_batch_size': 512}. Best is trial 0 with value: 0.5807392727246075.

[TabNet|seed=456] trial=0 auc=0.580739 train_time=1156.48s
[Optuna] Trial 000 | value=0.580739 | params={'n_d': 56, 'n_a': 32, 'n_steps': 4, 'gamma': 1.1361989602530256, 'lambda_sparse': 2.9978714162737635e-05, 'lr': 0.00019833454295672853, 'batch_size': 1024, 'virtual_batch_size': 512}
epoch 0  | loss: 0.17329 | valid_auc: 0.53219 |  0:00:11s
epoch 10 | loss: 0.15444 | valid_auc: 0.59851 |  0:02:00s
epoch 20 | loss: 0.15418 | valid_auc: 0.60253 |  0:03:47s
epoch 30 | loss: 0.15353 | valid_auc: 0.60878 |  0:05:35s
epoch 40 | loss: 0.15298 | valid_auc: 0.61546 |  0:07:25s
epoch 50 | loss: 0.15173 | valid_auc: 0.62313 |  0:09:24s

Early stopping occurred at epoch 59 with best_epoch = 47 and best_valid_auc = 0.62514

[I 2026-04-05 10:48:29,593] Trial 1 finished with value: 0.6251383140632227 and parameters: {'n_d': 32, 'n_a': 64, 'n_steps': 3, 'gamma': 1.6101304516898944, 'lambda_sparse': 5.519869466250662e-07, 'lr': 0.023472663855000447, 'batch_size': 4096, 'virtual_batch_size': 128}. Best is trial 1 with value: 0.6251383140632227.

[TabNet|seed=456] trial=1 auc=0.625138 train_time=680.69s
[Optuna] Trial 001 | value=0.625138 | params={'n_d': 32, 'n_a': 64, 'n_steps': 3, 'gamma': 1.6101304516898944, 'lambda_sparse': 5.519869466250662e-07, 'lr': 0.023472663855000447, 'batch_size': 4096, 'virtual_batch_size': 128}
epoch 0  | loss: 0.19587 | valid_auc: 0.52146 |  0:00:11s
epoch 10 | loss: 0.15392 | valid_auc: 0.60716 |  0:02:03s
epoch 20 | loss: 0.15262 | valid_auc: 0.61285 |  0:03:53s
epoch 30 | loss: 0.1501  | valid_auc: 0.61142 |  0:05:42s

Early stopping occurred at epoch 37 with best_epoch = 25 and best_valid_auc = 0.61819

[I 2026-04-05 10:55:41,580] Trial 2 finished with value: 0.6181898623014875 and parameters: {'n_d': 56, 'n_a': 56, 'n_steps': 3, 'gamma': 1.177270620195125, 'lambda_sparse': 1.4336606339002882e-07, 'lr': 0.023681220766658913, 'batch_size': 4096, 'virtual_batch_size': 128}. Best is trial 1 with value: 0.6251383140632227.

[TabNet|seed=456] trial=2 auc=0.618190 train_time=430.48s
[Optuna] Trial 002 | value=0.618190 | params={'n_d': 56, 'n_a': 56, 'n_steps': 3, 'gamma': 1.177270620195125, 'lambda_sparse': 1.4336606339002882e-07, 'lr': 0.023681220766658913, 'batch_size': 4096, 'virtual_batch_size': 128}
epoch 0  | loss: 0.16646 | valid_auc: 0.5439  |  0:00:18s
epoch 10 | loss: 0.15567 | valid_auc: 0.57248 |  0:03:20s
epoch 20 | loss: 0.15402 | valid_auc: 0.60806 |  0:06:23s
epoch 30 | loss: 0.15324 | valid_auc: 0.5983  |  0:09:28s
epoch 40 | loss: 0.15409 | valid_auc: 0.60725 |  0:12:33s

Early stopping occurred at epoch 47 with best_epoch = 35 and best_valid_auc = 0.61507

[I 2026-04-05 11:11:08,540] Trial 3 finished with value: 0.6150650643305562 and parameters: {'n_d': 16, 'n_a': 16, 'n_steps': 8, 'gamma': 1.3658497747520661, 'lambda_sparse': 0.0003071685307671165, 'lr': 0.03947948923738442, 'batch_size': 2048, 'virtual_batch_size': 256}. Best is trial 1 with value: 0.6251383140632227.

[TabNet|seed=456] trial=3 auc=0.615065 train_time=924.47s
[Optuna] Trial 003 | value=0.615065 | params={'n_d': 16, 'n_a': 16, 'n_steps': 8, 'gamma': 1.3658497747520661, 'lambda_sparse': 0.0003071685307671165, 'lr': 0.03947948923738442, 'batch_size': 2048, 'virtual_batch_size': 256}
epoch 0  | loss: 0.52454 | valid_auc: 0.48658 |  0:00:23s
epoch 10 | loss: 0.16211 | valid_auc: 0.53001 |  0:04:24s
epoch 20 | loss: 0.15782 | valid_auc: 0.54497 |  0:08:25s
epoch 30 | loss: 0.15615 | valid_auc: 0.55677 |  0:12:27s
epoch 40 | loss: 0.15573 | valid_auc: 0.56286 |  0:16:26s
epoch 50 | loss: 0.15538 | valid_auc: 0.57597 |  0:20:27s
epoch 60 | loss: 0.15523 | valid_auc: 0.5758  |  0:24:28s
epoch 70 | loss: 0.15515 | valid_auc: 0.57931 |  0:28:28s
Stop training because you reached max_epochs = 80 with best_epoch = 71 and best_valid_auc = 0.58514

[I 2026-04-05 11:44:26,288] Trial 4 finished with value: 0.5851351479834095 and parameters: {'n_d': 64, 'n_a': 16, 'n_steps': 7, 'gamma': 1.303685901987873, 'lambda_sparse': 8.61442853676912e-06, 'lr': 0.00030519694142741295, 'batch_size': 1024, 'virtual_batch_size': 256}. Best is trial 1 with value: 0.6251383140632227.

[TabNet|seed=456] trial=4 auc=0.585135 train_time=1994.31s
[Optuna] Trial 004 | value=0.585135 | params={'n_d': 64, 'n_a': 16, 'n_steps': 7, 'gamma': 1.303685901987873, 'lambda_sparse': 8.61442853676912e-06, 'lr': 0.00030519694142741295, 'batch_size': 1024, 'virtual_batch_size': 256}
[BEST] TabNet seed=456 best_valid_auc=0.625138
[BEST] params={'n_d': 32, 'n_a': 64, 'n_steps': 3, 'gamma': 1.6101304516898944, 'lambda_sparse': 5.519869466250662e-07, 'lr': 0.023472663855000447, 'batch_size': 4096, 'virtual_batch_size': 128}
epoch 0  | loss: 0.17329 | valid_auc: 0.53219 |  0:00:11s
epoch 10 | loss: 0.15444 | valid_auc: 0.59851 |  0:02:00s
epoch 20 | loss: 0.15418 | valid_auc: 0.60253 |  0:03:50s
epoch 30 | loss: 0.15353 | valid_auc: 0.60878 |  0:05:40s
epoch 40 | loss: 0.15298 | valid_auc: 0.61546 |  0:07:30s
epoch 50 | loss: 0.15173 | valid_auc: 0.62313 |  0:09:19s

Early stopping occurred at epoch 59 with best_epoch = 47 and best_valid_auc = 0.62514
Successfully saved model at artifacts/checkpoints/TabNet_seed456/tabnet_model.zip
[CKPT] Saved TabNet seed=456 -> artifacts/checkpoints/TabNet_seed456

==================== TabNet | seed=789 ====================

[I 2026-04-05 11:55:52,492] A new study created in memory with name: no-name-60e9c53d-7c66-4eee-a5db-d2c3d8b21433

epoch 0  | loss: 0.3275  | valid_auc: 0.50191 |  0:00:18s
epoch 10 | loss: 0.15621 | valid_auc: 0.5737  |  0:03:25s
epoch 20 | loss: 0.15576 | valid_auc: 0.5794  |  0:06:32s
epoch 30 | loss: 0.15494 | valid_auc: 0.59497 |  0:09:39s
epoch 40 | loss: 0.15466 | valid_auc: 0.60451 |  0:12:45s
epoch 50 | loss: 0.15411 | valid_auc: 0.61045 |  0:15:53s
epoch 60 | loss: 0.15389 | valid_auc: 0.60186 |  0:19:03s

Early stopping occurred at epoch 62 with best_epoch = 50 and best_valid_auc = 0.61045

[I 2026-04-05 12:16:29,311] Trial 0 finished with value: 0.6104496575146166 and parameters: {'n_d': 56, 'n_a': 32, 'n_steps': 5, 'gamma': 1.1049875022039695, 'lambda_sparse': 0.0007662583360741423, 'lr': 0.0009752395539501081, 'batch_size': 1024, 'virtual_batch_size': 256}. Best is trial 0 with value: 0.6104496575146166.

[TabNet|seed=789] trial=0 auc=0.610450 train_time=1234.08s
[Optuna] Trial 000 | value=0.610450 | params={'n_d': 56, 'n_a': 32, 'n_steps': 5, 'gamma': 1.1049875022039695, 'lambda_sparse': 0.0007662583360741423, 'lr': 0.0009752395539501081, 'batch_size': 1024, 'virtual_batch_size': 256}
epoch 0  | loss: 0.28297 | valid_auc: 0.50314 |  0:00:20s
epoch 10 | loss: 0.15616 | valid_auc: 0.56436 |  0:03:47s
epoch 20 | loss: 0.15539 | valid_auc: 0.57068 |  0:07:11s
epoch 30 | loss: 0.15509 | valid_auc: 0.58053 |  0:10:36s
epoch 40 | loss: 0.15481 | valid_auc: 0.58981 |  0:14:01s
epoch 50 | loss: 0.15451 | valid_auc: 0.5838  |  0:17:31s
epoch 60 | loss: 0.1544  | valid_auc: 0.58926 |  0:20:56s

Early stopping occurred at epoch 66 with best_epoch = 54 and best_valid_auc = 0.5967

[I 2026-04-05 12:40:40,561] Trial 1 finished with value: 0.5966989924964052 and parameters: {'n_d': 16, 'n_a': 32, 'n_steps': 7, 'gamma': 1.507523554731465, 'lambda_sparse': 1.687483141397986e-07, 'lr': 0.0007545389597889406, 'batch_size': 1024, 'virtual_batch_size': 512}. Best is trial 0 with value: 0.6104496575146166.

[TabNet|seed=789] trial=1 auc=0.596699 train_time=1448.32s
[Optuna] Trial 001 | value=0.596699 | params={'n_d': 16, 'n_a': 32, 'n_steps': 7, 'gamma': 1.507523554731465, 'lambda_sparse': 1.687483141397986e-07, 'lr': 0.0007545389597889406, 'batch_size': 1024, 'virtual_batch_size': 512}
epoch 0  | loss: 0.21194 | valid_auc: 0.48976 |  0:00:07s
epoch 10 | loss: 0.15733 | valid_auc: 0.54995 |  0:01:25s
epoch 20 | loss: 0.156   | valid_auc: 0.56318 |  0:02:42s
epoch 30 | loss: 0.15537 | valid_auc: 0.56883 |  0:04:02s
epoch 40 | loss: 0.1552  | valid_auc: 0.57502 |  0:05:29s
epoch 50 | loss: 0.15502 | valid_auc: 0.57509 |  0:06:54s

Early stopping occurred at epoch 50 with best_epoch = 38 and best_valid_auc = 0.57747

[I 2026-04-05 12:47:51,776] Trial 2 finished with value: 0.5774653128044099 and parameters: {'n_d': 48, 'n_a': 56, 'n_steps': 5, 'gamma': 1.6427083497681367, 'lambda_sparse': 0.0004862462723757967, 'lr': 0.0007511728861793214, 'batch_size': 4096, 'virtual_batch_size': 512}. Best is trial 0 with value: 0.6104496575146166.

[TabNet|seed=789] trial=2 auc=0.577465 train_time=429.76s
[Optuna] Trial 002 | value=0.577465 | params={'n_d': 48, 'n_a': 56, 'n_steps': 5, 'gamma': 1.6427083497681367, 'lambda_sparse': 0.0004862462723757967, 'lr': 0.0007511728861793214, 'batch_size': 4096, 'virtual_batch_size': 512}
epoch 0  | loss: 1.3355  | valid_auc: 0.50029 |  0:00:13s
epoch 10 | loss: 0.15795 | valid_auc: 0.55556 |  0:02:34s
epoch 20 | loss: 0.15574 | valid_auc: 0.57838 |  0:04:54s
epoch 30 | loss: 0.15531 | valid_auc: 0.57854 |  0:07:04s
epoch 40 | loss: 0.15507 | valid_auc: 0.58361 |  0:09:13s
epoch 50 | loss: 0.15492 | valid_auc: 0.59294 |  0:11:23s

Early stopping occurred at epoch 58 with best_epoch = 46 and best_valid_auc = 0.59524

[I 2026-04-05 13:01:22,760] Trial 3 finished with value: 0.5952422956018768 and parameters: {'n_d': 56, 'n_a': 24, 'n_steps': 7, 'gamma': 1.2346607486981376, 'lambda_sparse': 0.00044790117268557505, 'lr': 0.0015950687062487583, 'batch_size': 4096, 'virtual_batch_size': 256}. Best is trial 0 with value: 0.6104496575146166.

[TabNet|seed=789] trial=3 auc=0.595242 train_time=809.20s
[Optuna] Trial 003 | value=0.595242 | params={'n_d': 56, 'n_a': 24, 'n_steps': 7, 'gamma': 1.2346607486981376, 'lambda_sparse': 0.00044790117268557505, 'lr': 0.0015950687062487583, 'batch_size': 4096, 'virtual_batch_size': 256}
epoch 0  | loss: 0.3511  | valid_auc: 0.50103 |  0:00:09s
epoch 10 | loss: 0.1724  | valid_auc: 0.52351 |  0:01:40s
epoch 20 | loss: 0.16502 | valid_auc: 0.53824 |  0:03:11s
epoch 30 | loss: 0.1619  | valid_auc: 0.54774 |  0:04:43s
epoch 40 | loss: 0.16036 | valid_auc: 0.55526 |  0:06:15s
epoch 50 | loss: 0.15916 | valid_auc: 0.55988 |  0:07:46s
epoch 60 | loss: 0.15822 | valid_auc: 0.56235 |  0:09:17s
epoch 70 | loss: 0.15753 | valid_auc: 0.56863 |  0:10:48s
Stop training because you reached max_epochs = 80 with best_epoch = 79 and best_valid_auc = 0.57093

[I 2026-04-05 13:13:55,977] Trial 4 finished with value: 0.5709323497455868 and parameters: {'n_d': 48, 'n_a': 56, 'n_steps': 4, 'gamma': 1.202394214126921, 'lambda_sparse': 0.004719311882541049, 'lr': 0.0001328072816747972, 'batch_size': 2048, 'virtual_batch_size': 512}. Best is trial 0 with value: 0.6104496575146166.

[TabNet|seed=789] trial=4 auc=0.570932 train_time=751.91s
[Optuna] Trial 004 | value=0.570932 | params={'n_d': 48, 'n_a': 56, 'n_steps': 4, 'gamma': 1.202394214126921, 'lambda_sparse': 0.004719311882541049, 'lr': 0.0001328072816747972, 'batch_size': 2048, 'virtual_batch_size': 512}
[BEST] TabNet seed=789 best_valid_auc=0.610450
[BEST] params={'n_d': 56, 'n_a': 32, 'n_steps': 5, 'gamma': 1.1049875022039695, 'lambda_sparse': 0.0007662583360741423, 'lr': 0.0009752395539501081, 'batch_size': 1024, 'virtual_batch_size': 256}
epoch 0  | loss: 0.3275  | valid_auc: 0.50191 |  0:00:18s
epoch 10 | loss: 0.15621 | valid_auc: 0.5737  |  0:03:27s
epoch 20 | loss: 0.15576 | valid_auc: 0.5794  |  0:06:34s
epoch 30 | loss: 0.15494 | valid_auc: 0.59497 |  0:09:41s
epoch 40 | loss: 0.15466 | valid_auc: 0.60451 |  0:12:47s
epoch 50 | loss: 0.15411 | valid_auc: 0.61045 |  0:15:57s
epoch 60 | loss: 0.15389 | valid_auc: 0.60186 |  0:19:03s

Early stopping occurred at epoch 62 with best_epoch = 50 and best_valid_auc = 0.61045
Successfully saved model at artifacts/checkpoints/TabNet_seed789/tabnet_model.zip
[CKPT] Saved TabNet seed=789 -> artifacts/checkpoints/TabNet_seed789
[RESUME] TabNet best seed selected: 456

[SUMMARY] TabNet
  - accuracy            : mean=0.963551, std=0.000000
  - auc_roc             : mean=0.607374, std=0.011147
  - f1                  : mean=0.000000, std=0.000000
  - train_seconds       : mean=783.774971, std=330.551863
  - infer_ms_per_sample : mean=0.016480, std=0.004054
  - model_size_mb       : mean=0.624674, std=0.248978

In [ ]:
def run_fttransformer_experiment(n_trials=N_TRIALS, seeds=SEEDS):
    import joblib
    model_name = "FTTransformer"
    seed_results = []

    for seed in seeds:
        paths = get_seed_ckpt_paths(model_name, seed)
        cached_meta = load_seed_meta(model_name, seed)
        if cached_meta is not None and paths["ft_state"].exists() and paths["bundle_joblib"].exists():
            cached_metrics = cached_meta.get("metrics", {})
            if "seed" not in cached_metrics:
                cached_metrics["seed"] = int(seed)
            print(f"[RESUME] {model_name} seed={seed} loaded from checkpoint, skip training")
            seed_results.append(cached_metrics)
            continue

        print(f"\n{'='*20} {model_name} | seed={seed} {'='*20}")
        np.random.seed(seed)
        random.seed(seed)
        torch.manual_seed(seed)

        X_train_seed = X_train
        y_train_seed = y_train
        X_valid_seed = X_valid
        y_valid_seed = y_valid

        # More aggressive subsampling for FT only, to avoid memory/VRAM pressure causing kernel crashes
        train_cap = MAX_TRAIN_ROWS_FT if MAX_TRAIN_ROWS_FT is not None else MAX_TRAIN_ROWS
        valid_cap = MAX_VALID_ROWS_FT if MAX_VALID_ROWS_FT is not None else MAX_VALID_ROWS

        if train_cap is not None and len(X_train_seed) > train_cap:
            idx = X_train_seed.sample(n=train_cap, random_state=seed).index
            X_train_seed = X_train_seed.loc[idx]
            y_train_seed = y_train_seed.loc[idx]

        if valid_cap is not None and len(X_valid_seed) > valid_cap:
            idx = X_valid_seed.sample(n=valid_cap, random_state=seed).index
            X_valid_seed = X_valid_seed.loc[idx]
            y_valid_seed = y_valid_seed.loc[idx]

        bundle = prepare_deep_inputs(X_train_seed, X_valid_seed, X_test)
        ytr_np = y_train_seed.values.astype(int)
        yva_np = y_valid_seed.values.astype(int)
        yte_np = y_test.values.astype(int)

        def objective(trial):
            epoch_high = max(1, int(FT_MAX_EPOCHS))
            epoch_low = 1 if epoch_high < 8 else 8
            patience_high = min(6, epoch_high)
            patience_low = 1 if patience_high < 3 else 3

            params = {
                "dim": trial.suggest_categorical("dim", [8, 16]),
                "depth": trial.suggest_int("depth", 1, 3),
                "heads": trial.suggest_categorical("heads", [4]),
                "attn_dropout": trial.suggest_float("attn_dropout", 0.0, 0.3),
                "ff_dropout": trial.suggest_float("ff_dropout", 0.0, 0.3),
                "lr": trial.suggest_float("lr", 1e-4, 3e-3, log=True),
                "weight_decay": trial.suggest_float("weight_decay", 1e-6, 1e-2, log=True),
                "batch_size": trial.suggest_categorical("batch_size", [32, 64]),
                "epochs": trial.suggest_int("epochs", epoch_low, epoch_high),
                "patience": trial.suggest_int("patience", patience_low, patience_high),
            }
            t0 = time.perf_counter()
            # fit_fttransformer_once internally handles move to GPU and returns best AUC
            model, best_auc_valid = fit_fttransformer_once(bundle, ytr_np, yva_np, params, seed)
            t1 = time.perf_counter()

            print(
                f"[FTTransformer|seed={seed}] trial={trial.number} valid_auc={best_auc_valid:.6f} "
                f"train_time={t1-t0:.2f}s"
            )

            # Clean up immediately
            del model
            gc.collect()
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

            return best_auc_valid

        study = optuna.create_study(direction="maximize")
        study.optimize(objective, n_trials=n_trials, callbacks=[optuna_log_callback])
        best_params = study.best_trial.params
        print(f"[BEST] FTTransformer seed={seed} best_valid_auc={study.best_value:.6f}")
        print(f"[BEST] params={best_params}")

        t0 = time.perf_counter()
        final_model, _ = fit_fttransformer_once(bundle, ytr_np, yva_np, best_params, seed)
        y_prob_test = ft_predict_proba(final_model, bundle["Xte_cat"], bundle["Xte_num"])
        t1 = time.perf_counter()

        m = evaluate_predictions(yte_np, y_prob_test)
        m["seed"] = int(seed)
        m["train_seconds"] = float(t1 - t0)

        lat_list = []
        for _ in range(INFER_REPEAT):
            start = time.perf_counter()
            _ = ft_predict_proba(final_model, bundle["Xte_cat"], bundle["Xte_num"])
            end = time.perf_counter()
            lat_list.append((end - start) / len(bundle["Xte_num"]) * 1000)
        m["infer_ms_per_sample"] = float(np.mean(lat_list))
        m["infer_ms_per_sample_std"] = float(np.std(lat_list))

        torch.save(final_model.state_dict(), paths["ft_state"])
        m["model_size_mb"] = float(os.path.getsize(paths["ft_state"]) / (1024 * 1024))
        m["best_valid_auc"] = float(study.best_value)
        m["best_params"] = best_params
        seed_results.append(m)

        compact_bundle = compact_deep_bundle(bundle)
        joblib.dump(compact_bundle, paths["bundle_joblib"])
        save_seed_meta(
            model_name,
            seed,
            {
                "model_name": model_name,
                "seed": int(seed),
                "format": "ft_transformer",
                "metrics": m,
                "best_params": best_params,
                "state_path": str(paths["ft_state"]),
            },
        )
        print(f"[CKPT] Saved {model_name} seed={seed} -> {paths['dir']}")

        del final_model
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    if len(seed_results) == 0:
        raise RuntimeError("No FTTransformer seed results found")

    all_results[model_name] = seed_results

    # Reload best seed for the dictionary
    best_seed = int(max(seed_results, key=lambda r: r["auc_roc"])["seed"])
    best_paths = get_seed_ckpt_paths(model_name, best_seed)
    best_meta = load_seed_meta(model_name, best_seed)
    best_p = best_meta["best_params"]

    compact_bundle = joblib.load(best_paths["bundle_joblib"])
    best_model = FTTransformer(
        categories=tuple(compact_bundle["cat_dims"]),
        num_continuous=compact_bundle["n_num"],
        dim=best_p["dim"],
        dim_out=1,
        depth=best_p["depth"],
        heads=best_p["heads"],
        attn_dropout=best_p["attn_dropout"],
        ff_dropout=best_p["ff_dropout"],
    ).to(DEVICE)
    best_model.load_state_dict(torch.load(best_paths["ft_state"], map_location=DEVICE))

    best_models[model_name] = best_model
    best_preprocessors[model_name] = build_deep_infer_bundle_from_compact(compact_bundle, X_test)
    print(f"[RESUME] {model_name} best seed selected: {best_seed}")
    print_seed_metrics(model_name, seed_results)

run_fttransformer_experiment()

==================== FTTransformer | seed=123 ====================

[I 2026-04-05 14:19:06,085] A new study created in memory with name: no-name-a9d09517-6ca0-4c56-a430-2588863cc2c2

[FTTransformer|seed=123] epoch=001 loss=0.268460 valid_auc=0.547257
[FTTransformer|seed=123] epoch=002 loss=0.223667 valid_auc=0.545115
[FTTransformer|seed=123] epoch=003 loss=0.196577 valid_auc=0.466172
[FTTransformer|seed=123] epoch=004 loss=0.179464 valid_auc=0.548071
[FTTransformer|seed=123] epoch=005 loss=0.169153 valid_auc=0.557286
[FTTransformer|seed=123] epoch=006 loss=0.163239 valid_auc=0.500995
[FTTransformer|seed=123] epoch=007 loss=0.159984 valid_auc=0.558710
[FTTransformer|seed=123] epoch=008 loss=0.157897 valid_auc=0.566581
[FTTransformer|seed=123] epoch=009 loss=0.156095 valid_auc=0.566664
[FTTransformer|seed=123] epoch=010 loss=0.153801 valid_auc=0.571586
[FTTransformer|seed=123] epoch=011 loss=0.152998 valid_auc=0.579268
[FTTransformer|seed=123] epoch=012 loss=0.151696 valid_auc=0.570925
[FTTransformer|seed=123] epoch=013 loss=0.151061 valid_auc=0.583793
[FTTransformer|seed=123] epoch=014 loss=0.150122 valid_auc=0.580291
[FTTransformer|seed=123] epoch=015 loss=0.149756 valid_auc=0.569351
[FTTransformer|seed=123] epoch=016 loss=0.149181 valid_auc=0.566359
[FTTransformer|seed=123] Early stopping at epoch 16
[FTTransformer|seed=123] trial=0 valid_auc=0.583793 train_time=322.67s

[I 2026-04-05 14:24:29,075] Trial 0 finished with value: 0.5837925513853497 and parameters: {'dim': 8, 'depth': 3, 'heads': 4, 'attn_dropout': 0.05312059183937995, 'ff_dropout': 0.11792344503510276, 'lr': 0.00020867005316315684, 'weight_decay': 5.7985047923593995e-06, 'batch_size': 64, 'epochs': 19, 'patience': 3}. Best is trial 0 with value: 0.5837925513853497.

[Optuna] Trial 000 | value=0.583793 | params={'dim': 8, 'depth': 3, 'heads': 4, 'attn_dropout': 0.05312059183937995, 'ff_dropout': 0.11792344503510276, 'lr': 0.00020867005316315684, 'weight_decay': 5.7985047923593995e-06, 'batch_size': 64, 'epochs': 19, 'patience': 3}
[FTTransformer|seed=123] epoch=001 loss=0.202295 valid_auc=0.494063
[FTTransformer|seed=123] epoch=002 loss=0.157010 valid_auc=0.569729
[FTTransformer|seed=123] epoch=003 loss=0.156095 valid_auc=0.577155
[FTTransformer|seed=123] epoch=004 loss=0.154086 valid_auc=0.585396
[FTTransformer|seed=123] epoch=005 loss=0.152619 valid_auc=0.581387
[FTTransformer|seed=123] epoch=006 loss=0.151777 valid_auc=0.585058
[FTTransformer|seed=123] epoch=007 loss=0.151163 valid_auc=0.584533
[FTTransformer|seed=123] epoch=008 loss=0.150970 valid_auc=0.579238
[FTTransformer|seed=123] Early stopping at epoch 8
[FTTransformer|seed=123] trial=1 valid_auc=0.585396 train_time=112.11s

[I 2026-04-05 14:26:21,449] Trial 1 finished with value: 0.5853955172490393 and parameters: {'dim': 8, 'depth': 1, 'heads': 4, 'attn_dropout': 0.1381335454235461, 'ff_dropout': 0.17335161763784074, 'lr': 0.0016117495083049027, 'weight_decay': 5.550645047931115e-05, 'batch_size': 32, 'epochs': 10, 'patience': 4}. Best is trial 1 with value: 0.5853955172490393.

[Optuna] Trial 001 | value=0.585396 | params={'dim': 8, 'depth': 1, 'heads': 4, 'attn_dropout': 0.1381335454235461, 'ff_dropout': 0.17335161763784074, 'lr': 0.0016117495083049027, 'weight_decay': 5.550645047931115e-05, 'batch_size': 32, 'epochs': 10, 'patience': 4}
[FTTransformer|seed=123] epoch=001 loss=0.347062 valid_auc=0.574016
[FTTransformer|seed=123] epoch=002 loss=0.234476 valid_auc=0.566709
[FTTransformer|seed=123] epoch=003 loss=0.199208 valid_auc=0.569551
[FTTransformer|seed=123] epoch=004 loss=0.179152 valid_auc=0.574060
[FTTransformer|seed=123] epoch=005 loss=0.168117 valid_auc=0.565131
[FTTransformer|seed=123] epoch=006 loss=0.162308 valid_auc=0.565873
[FTTransformer|seed=123] epoch=007 loss=0.159322 valid_auc=0.529650
[FTTransformer|seed=123] epoch=008 loss=0.157866 valid_auc=0.524415
[FTTransformer|seed=123] epoch=009 loss=0.157233 valid_auc=0.555160
[FTTransformer|seed=123] Early stopping at epoch 9
[FTTransformer|seed=123] trial=2 valid_auc=0.574060 train_time=64.70s

[I 2026-04-05 14:27:26,416] Trial 2 finished with value: 0.5740601169716837 and parameters: {'dim': 16, 'depth': 1, 'heads': 4, 'attn_dropout': 0.17891398808417716, 'ff_dropout': 0.19170742693412107, 'lr': 0.0001878304505349977, 'weight_decay': 5.612004429873774e-05, 'batch_size': 64, 'epochs': 19, 'patience': 5}. Best is trial 1 with value: 0.5853955172490393.

[Optuna] Trial 002 | value=0.574060 | params={'dim': 16, 'depth': 1, 'heads': 4, 'attn_dropout': 0.17891398808417716, 'ff_dropout': 0.19170742693412107, 'lr': 0.0001878304505349977, 'weight_decay': 5.612004429873774e-05, 'batch_size': 64, 'epochs': 19, 'patience': 5}
[FTTransformer|seed=123] epoch=001 loss=0.250643 valid_auc=0.572487
[FTTransformer|seed=123] epoch=002 loss=0.193497 valid_auc=0.492352
[FTTransformer|seed=123] epoch=003 loss=0.169820 valid_auc=0.574758
[FTTransformer|seed=123] epoch=004 loss=0.160900 valid_auc=0.579713
[FTTransformer|seed=123] epoch=005 loss=0.157928 valid_auc=0.577017
[FTTransformer|seed=123] epoch=006 loss=0.156424 valid_auc=0.568638
[FTTransformer|seed=123] epoch=007 loss=0.154029 valid_auc=0.580031
[FTTransformer|seed=123] epoch=008 loss=0.152732 valid_auc=0.584491
[FTTransformer|seed=123] epoch=009 loss=0.152204 valid_auc=0.575239
[FTTransformer|seed=123] epoch=010 loss=0.150874 valid_auc=0.567702
[FTTransformer|seed=123] epoch=011 loss=0.150487 valid_auc=0.579803
[FTTransformer|seed=123] epoch=012 loss=0.149745 valid_auc=0.572766
[FTTransformer|seed=123] Early stopping at epoch 12
[FTTransformer|seed=123] trial=3 valid_auc=0.584491 train_time=472.05s

[I 2026-04-05 14:35:18,759] Trial 3 finished with value: 0.5844910970141439 and parameters: {'dim': 8, 'depth': 3, 'heads': 4, 'attn_dropout': 0.2749603869645788, 'ff_dropout': 0.18604812720635874, 'lr': 0.00018997414018049634, 'weight_decay': 1.261189747631064e-05, 'batch_size': 32, 'epochs': 14, 'patience': 4}. Best is trial 1 with value: 0.5853955172490393.

[Optuna] Trial 003 | value=0.584491 | params={'dim': 8, 'depth': 3, 'heads': 4, 'attn_dropout': 0.2749603869645788, 'ff_dropout': 0.18604812720635874, 'lr': 0.00018997414018049634, 'weight_decay': 1.261189747631064e-05, 'batch_size': 32, 'epochs': 14, 'patience': 4}
[FTTransformer|seed=123] epoch=001 loss=0.193240 valid_auc=0.528320
[FTTransformer|seed=123] epoch=002 loss=0.156921 valid_auc=0.560906
[FTTransformer|seed=123] epoch=003 loss=0.156625 valid_auc=0.560936
[FTTransformer|seed=123] epoch=004 loss=0.156039 valid_auc=0.582604
[FTTransformer|seed=123] epoch=005 loss=0.154497 valid_auc=0.585005
[FTTransformer|seed=123] epoch=006 loss=0.153236 valid_auc=0.577440
[FTTransformer|seed=123] epoch=007 loss=0.151369 valid_auc=0.572539
[FTTransformer|seed=123] epoch=008 loss=0.151260 valid_auc=0.567356
[FTTransformer|seed=123] Early stopping at epoch 8
[FTTransformer|seed=123] trial=4 valid_auc=0.585005 train_time=111.66s

[I 2026-04-05 14:37:10,696] Trial 4 finished with value: 0.5850051885160844 and parameters: {'dim': 16, 'depth': 1, 'heads': 4, 'attn_dropout': 0.22190905619396636, 'ff_dropout': 0.27418196605801526, 'lr': 0.0010079932383800926, 'weight_decay': 6.325730404602722e-06, 'batch_size': 32, 'epochs': 14, 'patience': 3}. Best is trial 1 with value: 0.5853955172490393.

[Optuna] Trial 004 | value=0.585005 | params={'dim': 16, 'depth': 1, 'heads': 4, 'attn_dropout': 0.22190905619396636, 'ff_dropout': 0.27418196605801526, 'lr': 0.0010079932383800926, 'weight_decay': 6.325730404602722e-06, 'batch_size': 32, 'epochs': 14, 'patience': 3}
[BEST] FTTransformer seed=123 best_valid_auc=0.585396
[BEST] params={'dim': 8, 'depth': 1, 'heads': 4, 'attn_dropout': 0.1381335454235461, 'ff_dropout': 0.17335161763784074, 'lr': 0.0016117495083049027, 'weight_decay': 5.550645047931115e-05, 'batch_size': 32, 'epochs': 10, 'patience': 4}
[FTTransformer|seed=123] epoch=001 loss=0.202295 valid_auc=0.494063
[FTTransformer|seed=123] epoch=002 loss=0.157010 valid_auc=0.569729
[FTTransformer|seed=123] epoch=003 loss=0.156095 valid_auc=0.577155
[FTTransformer|seed=123] epoch=004 loss=0.154086 valid_auc=0.585396
[FTTransformer|seed=123] epoch=005 loss=0.152619 valid_auc=0.581387
[FTTransformer|seed=123] epoch=006 loss=0.151777 valid_auc=0.585058
[FTTransformer|seed=123] epoch=007 loss=0.151163 valid_auc=0.584533
[FTTransformer|seed=123] epoch=008 loss=0.150970 valid_auc=0.579238
[FTTransformer|seed=123] Early stopping at epoch 8
[CKPT] Saved FTTransformer seed=123 -> artifacts/checkpoints/FTTransformer_seed123

==================== FTTransformer | seed=456 ====================

[I 2026-04-05 14:39:17,871] A new study created in memory with name: no-name-8a33b1e4-86db-4a6e-85bc-38a0cf7e758d

[FTTransformer|seed=456] epoch=001 loss=0.605687 valid_auc=0.460182
[FTTransformer|seed=456] epoch=002 loss=0.441321 valid_auc=0.496420
[FTTransformer|seed=456] epoch=003 loss=0.385462 valid_auc=0.492282
[FTTransformer|seed=456] epoch=004 loss=0.338369 valid_auc=0.488187
[FTTransformer|seed=456] epoch=005 loss=0.299036 valid_auc=0.484277
[FTTransformer|seed=456] epoch=006 loss=0.266790 valid_auc=0.479941
[FTTransformer|seed=456] epoch=007 loss=0.240856 valid_auc=0.476745
[FTTransformer|seed=456] epoch=008 loss=0.220181 valid_auc=0.479399
[FTTransformer|seed=456] Early stopping at epoch 8
[FTTransformer|seed=456] trial=0 valid_auc=0.496420 train_time=119.86s

[I 2026-04-05 14:41:18,050] Trial 0 finished with value: 0.496420202020202 and parameters: {'dim': 8, 'depth': 2, 'heads': 4, 'attn_dropout': 0.07796507702020002, 'ff_dropout': 0.010391527321753824, 'lr': 0.00017132375114772724, 'weight_decay': 0.001035480723954865, 'batch_size': 64, 'epochs': 9, 'patience': 6}. Best is trial 0 with value: 0.496420202020202.

[Optuna] Trial 000 | value=0.496420 | params={'dim': 8, 'depth': 2, 'heads': 4, 'attn_dropout': 0.07796507702020002, 'ff_dropout': 0.010391527321753824, 'lr': 0.00017132375114772724, 'weight_decay': 0.001035480723954865, 'batch_size': 64, 'epochs': 9, 'patience': 6}
[FTTransformer|seed=456] epoch=001 loss=0.187400 valid_auc=0.520745
[FTTransformer|seed=456] epoch=002 loss=0.155561 valid_auc=0.470045
[FTTransformer|seed=456] epoch=003 loss=0.155126 valid_auc=0.435542
[FTTransformer|seed=456] epoch=004 loss=0.154785 valid_auc=0.611345
[FTTransformer|seed=456] epoch=005 loss=0.154379 valid_auc=0.620927
[FTTransformer|seed=456] epoch=006 loss=0.153122 valid_auc=0.620668
[FTTransformer|seed=456] epoch=007 loss=0.152939 valid_auc=0.594810
[FTTransformer|seed=456] epoch=008 loss=0.152026 valid_auc=0.603317
[FTTransformer|seed=456] epoch=009 loss=0.150935 valid_auc=0.586690
[FTTransformer|seed=456] epoch=010 loss=0.150492 valid_auc=0.558332
[FTTransformer|seed=456] epoch=011 loss=0.149714 valid_auc=0.574197
[FTTransformer|seed=456] Early stopping at epoch 11
[FTTransformer|seed=456] trial=1 valid_auc=0.620927 train_time=313.87s

[I 2026-04-05 14:46:32,204] Trial 1 finished with value: 0.6209269841269841 and parameters: {'dim': 16, 'depth': 2, 'heads': 4, 'attn_dropout': 0.10882284925185416, 'ff_dropout': 0.1794138419982662, 'lr': 0.0005532738207190907, 'weight_decay': 0.003951542321888496, 'batch_size': 32, 'epochs': 12, 'patience': 6}. Best is trial 1 with value: 0.6209269841269841.

[Optuna] Trial 001 | value=0.620927 | params={'dim': 16, 'depth': 2, 'heads': 4, 'attn_dropout': 0.10882284925185416, 'ff_dropout': 0.1794138419982662, 'lr': 0.0005532738207190907, 'weight_decay': 0.003951542321888496, 'batch_size': 32, 'epochs': 12, 'patience': 6}
[FTTransformer|seed=456] epoch=001 loss=0.236896 valid_auc=0.534084
[FTTransformer|seed=456] epoch=002 loss=0.156090 valid_auc=0.529346
[FTTransformer|seed=456] epoch=003 loss=0.155368 valid_auc=0.533887
[FTTransformer|seed=456] epoch=004 loss=0.155324 valid_auc=0.560309
[FTTransformer|seed=456] epoch=005 loss=0.155274 valid_auc=0.582289
[FTTransformer|seed=456] epoch=006 loss=0.155284 valid_auc=0.586552
[FTTransformer|seed=456] epoch=007 loss=0.155091 valid_auc=0.593284
[FTTransformer|seed=456] epoch=008 loss=0.154489 valid_auc=0.612290
[FTTransformer|seed=456] epoch=009 loss=0.154178 valid_auc=0.608060
[FTTransformer|seed=456] epoch=010 loss=0.153874 valid_auc=0.442538
[FTTransformer|seed=456] epoch=011 loss=0.153636 valid_auc=0.565292
[FTTransformer|seed=456] Early stopping at epoch 11
[FTTransformer|seed=456] trial=2 valid_auc=0.612290 train_time=465.09s

[I 2026-04-05 14:54:17,581] Trial 2 finished with value: 0.6122901394901394 and parameters: {'dim': 8, 'depth': 3, 'heads': 4, 'attn_dropout': 0.20365844554611734, 'ff_dropout': 0.08965320687583024, 'lr': 0.0010057165320916965, 'weight_decay': 1.596136353858184e-05, 'batch_size': 32, 'epochs': 18, 'patience': 3}. Best is trial 1 with value: 0.6209269841269841.

[Optuna] Trial 002 | value=0.612290 | params={'dim': 8, 'depth': 3, 'heads': 4, 'attn_dropout': 0.20365844554611734, 'ff_dropout': 0.08965320687583024, 'lr': 0.0010057165320916965, 'weight_decay': 1.596136353858184e-05, 'batch_size': 32, 'epochs': 18, 'patience': 3}
[FTTransformer|seed=456] epoch=001 loss=0.545230 valid_auc=0.497438
[FTTransformer|seed=456] epoch=002 loss=0.385707 valid_auc=0.495385
[FTTransformer|seed=456] epoch=003 loss=0.311003 valid_auc=0.483471
[FTTransformer|seed=456] epoch=004 loss=0.257277 valid_auc=0.498350
[FTTransformer|seed=456] epoch=005 loss=0.220425 valid_auc=0.478688
[FTTransformer|seed=456] epoch=006 loss=0.195987 valid_auc=0.475761
[FTTransformer|seed=456] epoch=007 loss=0.180253 valid_auc=0.477005
[FTTransformer|seed=456] Early stopping at epoch 7
[FTTransformer|seed=456] trial=3 valid_auc=0.498350 train_time=104.28s

[I 2026-04-05 14:56:02,182] Trial 3 finished with value: 0.4983499759499759 and parameters: {'dim': 8, 'depth': 2, 'heads': 4, 'attn_dropout': 0.22037107340995263, 'ff_dropout': 0.12765164147770894, 'lr': 0.0002892734543116296, 'weight_decay': 0.00019906704736525265, 'batch_size': 64, 'epochs': 9, 'patience': 3}. Best is trial 1 with value: 0.6209269841269841.

[Optuna] Trial 003 | value=0.498350 | params={'dim': 8, 'depth': 2, 'heads': 4, 'attn_dropout': 0.22037107340995263, 'ff_dropout': 0.12765164147770894, 'lr': 0.0002892734543116296, 'weight_decay': 0.00019906704736525265, 'batch_size': 64, 'epochs': 9, 'patience': 3}
[FTTransformer|seed=456] epoch=001 loss=0.641134 valid_auc=0.448881
[FTTransformer|seed=456] epoch=002 loss=0.464340 valid_auc=0.513176
[FTTransformer|seed=456] epoch=003 loss=0.418600 valid_auc=0.506864
[FTTransformer|seed=456] epoch=004 loss=0.378264 valid_auc=0.502464
[FTTransformer|seed=456] epoch=005 loss=0.342593 valid_auc=0.494837
[FTTransformer|seed=456] epoch=006 loss=0.311367 valid_auc=0.491040
[FTTransformer|seed=456] epoch=007 loss=0.284394 valid_auc=0.488633
[FTTransformer|seed=456] epoch=008 loss=0.261236 valid_auc=0.483712
[FTTransformer|seed=456] Early stopping at epoch 8
[FTTransformer|seed=456] trial=4 valid_auc=0.513176 train_time=118.02s

[I 2026-04-05 14:58:00,510] Trial 4 finished with value: 0.5131755651755652 and parameters: {'dim': 8, 'depth': 2, 'heads': 4, 'attn_dropout': 0.1520002405296195, 'ff_dropout': 0.26660592010985246, 'lr': 0.00012968926289020654, 'weight_decay': 5.904654583630549e-06, 'batch_size': 64, 'epochs': 18, 'patience': 6}. Best is trial 1 with value: 0.6209269841269841.

[Optuna] Trial 004 | value=0.513176 | params={'dim': 8, 'depth': 2, 'heads': 4, 'attn_dropout': 0.1520002405296195, 'ff_dropout': 0.26660592010985246, 'lr': 0.00012968926289020654, 'weight_decay': 5.904654583630549e-06, 'batch_size': 64, 'epochs': 18, 'patience': 6}
[BEST] FTTransformer seed=456 best_valid_auc=0.620927
[BEST] params={'dim': 16, 'depth': 2, 'heads': 4, 'attn_dropout': 0.10882284925185416, 'ff_dropout': 0.1794138419982662, 'lr': 0.0005532738207190907, 'weight_decay': 0.003951542321888496, 'batch_size': 32, 'epochs': 12, 'patience': 6}
[FTTransformer|seed=456] epoch=001 loss=0.187400 valid_auc=0.520745
[FTTransformer|seed=456] epoch=002 loss=0.155561 valid_auc=0.470045
[FTTransformer|seed=456] epoch=003 loss=0.155126 valid_auc=0.435542
[FTTransformer|seed=456] epoch=004 loss=0.154785 valid_auc=0.611345
[FTTransformer|seed=456] epoch=005 loss=0.154379 valid_auc=0.620927
[FTTransformer|seed=456] epoch=006 loss=0.153122 valid_auc=0.620668
[FTTransformer|seed=456] epoch=007 loss=0.152939 valid_auc=0.594810
[FTTransformer|seed=456] epoch=008 loss=0.152026 valid_auc=0.603317
[FTTransformer|seed=456] epoch=009 loss=0.150935 valid_auc=0.586690
[FTTransformer|seed=456] epoch=010 loss=0.150492 valid_auc=0.558332
[FTTransformer|seed=456] epoch=011 loss=0.149714 valid_auc=0.574197
[FTTransformer|seed=456] Early stopping at epoch 11
[CKPT] Saved FTTransformer seed=456 -> artifacts/checkpoints/FTTransformer_seed456

==================== FTTransformer | seed=789 ====================

[I 2026-04-05 15:03:48,426] A new study created in memory with name: no-name-e580be83-1e7a-405d-a366-ed55e75c3694

[FTTransformer|seed=789] epoch=001 loss=0.193563 valid_auc=0.530060
[FTTransformer|seed=789] epoch=002 loss=0.164855 valid_auc=0.412978
[FTTransformer|seed=789] epoch=003 loss=0.164840 valid_auc=0.599182
[FTTransformer|seed=789] epoch=004 loss=0.163888 valid_auc=0.596163
[FTTransformer|seed=789] epoch=005 loss=0.162418 valid_auc=0.597203
[FTTransformer|seed=789] epoch=006 loss=0.161482 valid_auc=0.604591
[FTTransformer|seed=789] epoch=007 loss=0.161026 valid_auc=0.595905
[FTTransformer|seed=789] epoch=008 loss=0.160729 valid_auc=0.601897
[FTTransformer|seed=789] epoch=009 loss=0.159569 valid_auc=0.613729
[FTTransformer|seed=789] epoch=010 loss=0.158891 valid_auc=0.603541
[FTTransformer|seed=789] epoch=011 loss=0.158623 valid_auc=0.585566
[FTTransformer|seed=789] epoch=012 loss=0.159126 valid_auc=0.594691
[FTTransformer|seed=789] Early stopping at epoch 12
[FTTransformer|seed=789] trial=0 valid_auc=0.613729 train_time=175.60s

[I 2026-04-05 15:06:44,332] Trial 0 finished with value: 0.6137287884303846 and parameters: {'dim': 16, 'depth': 2, 'heads': 4, 'attn_dropout': 0.006194630309673132, 'ff_dropout': 0.0021426108305322654, 'lr': 0.001368269902654398, 'weight_decay': 0.0052225621890505105, 'batch_size': 64, 'epochs': 16, 'patience': 3}. Best is trial 0 with value: 0.6137287884303846.

[Optuna] Trial 000 | value=0.613729 | params={'dim': 16, 'depth': 2, 'heads': 4, 'attn_dropout': 0.006194630309673132, 'ff_dropout': 0.0021426108305322654, 'lr': 0.001368269902654398, 'weight_decay': 0.0052225621890505105, 'batch_size': 64, 'epochs': 16, 'patience': 3}
[FTTransformer|seed=789] epoch=001 loss=0.257555 valid_auc=0.507930
[FTTransformer|seed=789] epoch=002 loss=0.195498 valid_auc=0.516195
[FTTransformer|seed=789] epoch=003 loss=0.178791 valid_auc=0.526605
[FTTransformer|seed=789] epoch=004 loss=0.170708 valid_auc=0.517996
[FTTransformer|seed=789] epoch=005 loss=0.167098 valid_auc=0.515557
[FTTransformer|seed=789] epoch=006 loss=0.165628 valid_auc=0.528430
[FTTransformer|seed=789] epoch=007 loss=0.165036 valid_auc=0.555544
[FTTransformer|seed=789] epoch=008 loss=0.164856 valid_auc=0.566910
[FTTransformer|seed=789] epoch=009 loss=0.164783 valid_auc=0.586019
[FTTransformer|seed=789] epoch=010 loss=0.164325 valid_auc=0.596507
[FTTransformer|seed=789] trial=1 valid_auc=0.596507 train_time=75.31s

[I 2026-04-05 15:07:59,919] Trial 1 finished with value: 0.5965072566253529 and parameters: {'dim': 16, 'depth': 1, 'heads': 4, 'attn_dropout': 0.278630700428552, 'ff_dropout': 0.06744652018225654, 'lr': 0.00018406639401743013, 'weight_decay': 0.007812434753853376, 'batch_size': 64, 'epochs': 10, 'patience': 4}. Best is trial 0 with value: 0.6137287884303846.

[Optuna] Trial 001 | value=0.596507 | params={'dim': 16, 'depth': 1, 'heads': 4, 'attn_dropout': 0.278630700428552, 'ff_dropout': 0.06744652018225654, 'lr': 0.00018406639401743013, 'weight_decay': 0.007812434753853376, 'batch_size': 64, 'epochs': 10, 'patience': 4}
[FTTransformer|seed=789] epoch=001 loss=0.218395 valid_auc=0.599940
[FTTransformer|seed=789] epoch=002 loss=0.165527 valid_auc=0.478720
[FTTransformer|seed=789] epoch=003 loss=0.164856 valid_auc=0.585888
[FTTransformer|seed=789] epoch=004 loss=0.164901 valid_auc=0.510893
[FTTransformer|seed=789] epoch=005 loss=0.164551 valid_auc=0.576909
[FTTransformer|seed=789] Early stopping at epoch 5
[FTTransformer|seed=789] trial=2 valid_auc=0.599940 train_time=141.12s

[I 2026-04-05 15:10:21,328] Trial 2 finished with value: 0.5999397642266262 and parameters: {'dim': 8, 'depth': 2, 'heads': 4, 'attn_dropout': 0.19181446363684787, 'ff_dropout': 0.03854710512517216, 'lr': 0.0007973526278132735, 'weight_decay': 0.000525122945401058, 'batch_size': 32, 'epochs': 16, 'patience': 4}. Best is trial 0 with value: 0.6137287884303846.

[Optuna] Trial 002 | value=0.599940 | params={'dim': 8, 'depth': 2, 'heads': 4, 'attn_dropout': 0.19181446363684787, 'ff_dropout': 0.03854710512517216, 'lr': 0.0007973526278132735, 'weight_decay': 0.000525122945401058, 'batch_size': 32, 'epochs': 16, 'patience': 4}
[FTTransformer|seed=789] epoch=001 loss=0.221113 valid_auc=0.559138
[FTTransformer|seed=789] epoch=002 loss=0.166056 valid_auc=0.484843
[FTTransformer|seed=789] epoch=003 loss=0.164868 valid_auc=0.595613
[FTTransformer|seed=789] epoch=004 loss=0.164275 valid_auc=0.600058
[FTTransformer|seed=789] epoch=005 loss=0.163685 valid_auc=0.609956
[FTTransformer|seed=789] epoch=006 loss=0.162027 valid_auc=0.608752
[FTTransformer|seed=789] epoch=007 loss=0.161541 valid_auc=0.604843
[FTTransformer|seed=789] epoch=008 loss=0.160484 valid_auc=0.610209
[FTTransformer|seed=789] epoch=009 loss=0.159961 valid_auc=0.606987
[FTTransformer|seed=789] epoch=010 loss=0.159668 valid_auc=0.591356
[FTTransformer|seed=789] epoch=011 loss=0.159003 valid_auc=0.607423
[FTTransformer|seed=789] epoch=012 loss=0.158233 valid_auc=0.614877
[FTTransformer|seed=789] trial=3 valid_auc=0.614877 train_time=491.03s

[I 2026-04-05 15:18:32,647] Trial 3 finished with value: 0.6148772269188704 and parameters: {'dim': 16, 'depth': 3, 'heads': 4, 'attn_dropout': 0.12996486059101658, 'ff_dropout': 0.0826472990852878, 'lr': 0.0005228726043341119, 'weight_decay': 0.0006486407934084053, 'batch_size': 32, 'epochs': 12, 'patience': 4}. Best is trial 3 with value: 0.6148772269188704.

[Optuna] Trial 003 | value=0.614877 | params={'dim': 16, 'depth': 3, 'heads': 4, 'attn_dropout': 0.12996486059101658, 'ff_dropout': 0.0826472990852878, 'lr': 0.0005228726043341119, 'weight_decay': 0.0006486407934084053, 'batch_size': 32, 'epochs': 12, 'patience': 4}
[FTTransformer|seed=789] epoch=001 loss=0.206426 valid_auc=0.537307
[FTTransformer|seed=789] epoch=002 loss=0.165365 valid_auc=0.574508
[FTTransformer|seed=789] epoch=003 loss=0.164666 valid_auc=0.588282
[FTTransformer|seed=789] epoch=004 loss=0.163367 valid_auc=0.578208
[FTTransformer|seed=789] epoch=005 loss=0.162181 valid_auc=0.551476
[FTTransformer|seed=789] epoch=006 loss=0.161557 valid_auc=0.593466
[FTTransformer|seed=789] epoch=007 loss=0.160701 valid_auc=0.594321
[FTTransformer|seed=789] epoch=008 loss=0.159776 valid_auc=0.598372
[FTTransformer|seed=789] epoch=009 loss=0.158759 valid_auc=0.612651
[FTTransformer|seed=789] trial=4 valid_auc=0.612651 train_time=246.68s

[I 2026-04-05 15:22:39,618] Trial 4 finished with value: 0.6126513753705547 and parameters: {'dim': 16, 'depth': 2, 'heads': 4, 'attn_dropout': 0.10774598802271507, 'ff_dropout': 0.23084781912712685, 'lr': 0.00048096026175157414, 'weight_decay': 0.0076085734920716295, 'batch_size': 32, 'epochs': 9, 'patience': 5}. Best is trial 3 with value: 0.6148772269188704.

[Optuna] Trial 004 | value=0.612651 | params={'dim': 16, 'depth': 2, 'heads': 4, 'attn_dropout': 0.10774598802271507, 'ff_dropout': 0.23084781912712685, 'lr': 0.00048096026175157414, 'weight_decay': 0.0076085734920716295, 'batch_size': 32, 'epochs': 9, 'patience': 5}
[BEST] FTTransformer seed=789 best_valid_auc=0.614877
[BEST] params={'dim': 16, 'depth': 3, 'heads': 4, 'attn_dropout': 0.12996486059101658, 'ff_dropout': 0.0826472990852878, 'lr': 0.0005228726043341119, 'weight_decay': 0.0006486407934084053, 'batch_size': 32, 'epochs': 12, 'patience': 4}
[FTTransformer|seed=789] epoch=001 loss=0.221113 valid_auc=0.559138
[FTTransformer|seed=789] epoch=002 loss=0.166056 valid_auc=0.484843
[FTTransformer|seed=789] epoch=003 loss=0.164868 valid_auc=0.595613
[FTTransformer|seed=789] epoch=004 loss=0.164275 valid_auc=0.600058
[FTTransformer|seed=789] epoch=005 loss=0.163685 valid_auc=0.609956
[FTTransformer|seed=789] epoch=006 loss=0.162027 valid_auc=0.608752
[FTTransformer|seed=789] epoch=007 loss=0.161541 valid_auc=0.604843
[FTTransformer|seed=789] epoch=008 loss=0.160484 valid_auc=0.610209
[FTTransformer|seed=789] epoch=009 loss=0.159961 valid_auc=0.606987
[FTTransformer|seed=789] epoch=010 loss=0.159668 valid_auc=0.591356
[FTTransformer|seed=789] epoch=011 loss=0.159003 valid_auc=0.607423
[FTTransformer|seed=789] epoch=012 loss=0.158233 valid_auc=0.614877
[CKPT] Saved FTTransformer seed=789 -> artifacts/checkpoints/FTTransformer_seed789
[RESUME] FTTransformer best seed selected: 456

[SUMMARY] FTTransformer
  - accuracy            : mean=0.963551, std=0.000000
  - auc_roc             : mean=0.593717, std=0.001714
  - f1                  : mean=0.000000, std=0.000000
  - train_seconds       : mean=307.332049, std=151.844933
  - infer_ms_per_sample : mean=0.040271, std=0.017654
  - model_size_mb       : mean=0.088023, std=0.042500

In [ ]:
# ===== 3.6 Deep Model Utility: FT-Transformer Memory Cleanup =====
# Clean previously trained models from memory to free GPU space for FT-Transformer
print("[INFO] Clearing best_models and best_preprocessors to free GPU memory for FT-Transformer...")

# Explicitly delete model objects that might hold GPU memory
for model_name, model_obj in best_models.items():
    if hasattr(model_obj, 'to') and callable(getattr(model_obj, 'to')):
        # For PyTorch models, move to CPU or detach
        try:
            model_obj.to('cpu')
            del model_obj # Explicitly delete
        except Exception as e:
            print(f"[WARN] Could not move {model_name} model to CPU or delete: {e}")
    elif 'XGBoost' in model_name or 'LightGBM' in model_name or 'CatBoost' in model_name:
        # For tree models, explicit deletion might help
        try:
            del model_obj
        except Exception as e:
            print(f"[WARN] Could not delete {model_name} model object: {e}")

# Clear global dictionaries
best_models.clear()
best_preprocessors.clear()

gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()
    print(f"[INFO] CUDA memory after cleanup: {torch.cuda.memory_allocated() / (1024**2):.2f} MB allocated")
else:
    print("[INFO] GPU not available or PyTorch not using CUDA.")

print("[INFO] Memory cleanup complete. Proceeding with FT-Transformer experiment.")

[INFO] Clearing best_models and best_preprocessors to free GPU memory for FT-Transformer...
[INFO] CUDA memory after cleanup: 18.89 MB allocated
[INFO] Memory cleanup complete. Proceeding with FT-Transformer experiment.

### Fixing post-cleanup prediction/analysis issues: reload all best models



To fix the issue where cleaning models before FT-Transformer training breaks later prediction and analysis, reload each model's best checkpoint from disk after all model training (including FT-Transformer) completes. This ensures all models are available in the `best_models` and `best_preprocessors` dictionaries for summary and prediction steps.

In [ ]:
# ===== Reload all best models and preprocessors =====
import joblib

print("[INFO] Reloading all best models and preprocessors from checkpoints...")

# Clear existing in-memory objects to ensure fresh reload and avoid duplicates
best_models.clear()
best_preprocessors.clear()

for model_name, seed_results in all_results.items():
    if not seed_results:
        print(f"[WARN] No results found for {model_name}. Skipping reload.")
        continue

    # Find the best seed based on AUC-ROC from the stored results
    best_seed_result = max(seed_results, key=lambda r: r["auc_roc"])
    best_seed = int(best_seed_result["seed"])
    best_meta = best_seed_result.get("best_params", {})

    paths = get_seed_ckpt_paths(model_name, best_seed)

    # Handle different model types for loading
    if model_name in ["LogisticRegression", "RandomForest", "XGBoost", "LightGBM", "CatBoost"]:
        try:
            best_pack = joblib.load(paths["model_joblib"])
            best_models[model_name] = best_pack["model"]
            best_preprocessors[model_name] = best_pack["preprocessor"]
            print(f"[INFO] Reloaded {model_name} (seed={best_seed}) from {paths['model_joblib']}")
        except Exception as e:
            print(f"[ERROR] Failed to reload {model_name} from {paths['model_joblib']}: {e}")
    elif model_name == "TabNet":
        try:
            best_model = TabNetClassifier()
            # Use the exact path from meta if available, otherwise default
            meta_path = load_seed_meta(model_name, best_seed).get("model_zip", paths["tabnet_zip"])
            best_model.load_model(str(meta_path))
            best_models[model_name] = best_model

            compact_bundle = joblib.load(paths["bundle_joblib"])
            best_preprocessors[model_name] = build_deep_infer_bundle_from_compact(compact_bundle, X_test)
            print(f"[INFO] Reloaded {model_name} (seed={best_seed}) from {meta_path}")
        except Exception as e:
            print(f"[ERROR] Failed to reload {model_name} from {paths['tabnet_zip']}: {e}")
    elif model_name == "FTTransformer":
        try:
            best_params = load_seed_meta(model_name, best_seed)["best_params"]
            compact_bundle = joblib.load(paths["bundle_joblib"])

            best_model = FTTransformer(
                categories=tuple(compact_bundle["cat_dims"]),
                num_continuous=compact_bundle["n_num"],
                dim=best_params["dim"],
                dim_out=1,
                depth=best_params["depth"],
                heads=best_params["heads"],
                attn_dropout=best_params["attn_dropout"],
                ff_dropout=best_params["ff_dropout"],
            ).to(DEVICE)
            state_dict = torch.load(paths["ft_state"], map_location=DEVICE)
            best_model.load_state_dict(state_dict)

            best_models[model_name] = best_model
            best_preprocessors[model_name] = build_deep_infer_bundle_from_compact(compact_bundle, X_test)
            print(f"[INFO] Reloaded {model_name} (seed={best_seed}) from {paths['ft_state']}")
        except Exception as e:
            print(f"[ERROR] Failed to reload {model_name} from {paths['ft_state']}: {e}")

gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()

print("[INFO] All best models and preprocessors reloaded. You can now proceed with prediction and analysis.")

[INFO] Reloading all best models and preprocessors from checkpoints...
[INFO] Reloaded LogisticRegression (seed=456) from artifacts/checkpoints/LogisticRegression_seed456/model.joblib
[INFO] Reloaded RandomForest (seed=789) from artifacts/checkpoints/RandomForest_seed789/model.joblib
[INFO] Reloaded XGBoost (seed=456) from artifacts/checkpoints/XGBoost_seed456/model.joblib
[INFO] Reloaded LightGBM (seed=789) from artifacts/checkpoints/LightGBM_seed789/model.joblib
[INFO] Reloaded CatBoost (seed=456) from artifacts/checkpoints/CatBoost_seed456/model.joblib
[INFO] Reloaded TabNet (seed=456) from artifacts/checkpoints/TabNet_seed456/tabnet_model.zip
[INFO] Reloaded FTTransformer (seed=456) from artifacts/checkpoints/FTTransformer_seed456/ft_state.pt
[INFO] All best models and preprocessors reloaded. You can now proceed with prediction and analysis.

In [56]:
!nvidia-smi

Sun Apr  5 14:00:31 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   59C    P0             29W /   70W |   14853MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            8728      C   /usr/bin/python3                      14850MiB |
+-----------------------------------------------------------------------------------------+

## 4) Model Prediction and Comprehensive Analysis



Outputs from this stage:

- Overall test-set result table with mean 卤 standard deviation for each model

- Inference cost and model size comparison

- Stability analysis (cross-seed variance)

- Feature-importance consistency comparison

- Practice-oriented conclusion recommendations

In [ ]:
# ===== 4.1 Summary Results Table =====
rows = []
for model_name, seed_res in all_results.items():
    if len(seed_res) == 0:
        continue
    row = {"model": model_name}
    for m in ["accuracy", "auc_roc", "f1", "train_seconds", "infer_ms_per_sample", "model_size_mb", "best_valid_auc"]:
        vals = [r[m] for r in seed_res]
        row[f"{m}_mean"] = float(np.mean(vals))
        row[f"{m}_std"] = float(np.std(vals))
    rows.append(row)

summary_df = pd.DataFrame(rows).sort_values("auc_roc_mean", ascending=False).reset_index(drop=True)
display(summary_df)

summary_df.to_csv(SUMMARY_PATH, index=False)
print(f"[INFO] Saved summary to {SUMMARY_PATH}")

,model,accuracy_mean,accuracy_std,auc_roc_mean,auc_roc_std,f1_mean,f1_std,train_seconds_mean,train_seconds_std,infer_ms_per_sample_mean,infer_ms_per_sample_std,model_size_mb_mean,model_size_mb_std,best_valid_auc_mean,best_valid_auc_std
0,CatBoost,0.96,0.00e+00,0.64,1.08e-03,1.54e-04,2.17e-04,114.07,26.51,1.45e-02,1.73e-03,12.22,9.39,0.64,3.11e-04
1,XGBoost,0.96,0.00e+00,0.63,3.35e-04,0.00e+00,0.00e+00,9.12,2.12,8.37e-03,8.04e-04,4.28,4.62,0.63,2.63e-03
2,LightGBM,0.96,3.96e-06,0.63,1.59e-03,0.00e+00,0.00e+00,22.71,11.88,1.76e-02,7.87e-03,2.51,1.80,0.63,1.56e-03
3,LogisticRegression,0.62,6.99e-04,0.63,1.92e-03,9.60e-02,6.52e-04,816.12,859.86,6.75e-03,1.22e-04,0.01,0.00,0.62,2.09e-04
4,RandomForest,0.66,5.31e-02,0.62,1.50e-03,9.68e-02,1.75e-03,177.39,46.69,1.31e-01,3.25e-02,31.09,26.74,0.62,6.05e-04
5,TabNet,0.96,0.00e+00,0.61,1.11e-02,0.00e+00,0.00e+00,783.77,330.55,1.65e-02,4.05e-03,0.62,0.25,0.61,1.00e-02
6,FTTransformer,0.96,0.00e+00,0.59,1.71e-03,0.00e+00,0.00e+00,307.33,151.84,4.03e-02,1.77e-02,0.09,0.04,0.61,1.55e-02

[INFO] Saved summary to artifacts/model_summary.csv

In [ ]:
# ===== 4.2 Export Test-Set Predictions (Probabilities) =====
test_pred_df = pd.DataFrame(index=X_test.index)
test_pred_df[TARGET_COL] = y_test.values

for model_name, model in best_models.items():
    print(f"[PREDICT] {model_name}")
    if model_name in ["LogisticRegression", "RandomForest", "XGBoost", "LightGBM"]:
        prep = best_preprocessors[model_name]
        proba = model.predict_proba(prep.transform(X_test))[:, 1]
    elif model_name == "CatBoost":
        Xt = X_test.copy()
        for c in cat_cols:
            Xt[c] = Xt[c].astype("string").fillna("MISSING")
        proba = model.predict_proba(Xt)[:, 1]
    elif model_name in ["TabNet"]:
        bundle = best_preprocessors[model_name]
        Xte_tab = np.hstack([bundle["Xte_num"], bundle["Xte_cat"]]).astype(np.float32)
        proba = model.predict_proba(Xte_tab)[:, 1]
    elif model_name in ["FTTransformer"]:
        bundle = best_preprocessors[model_name]
        proba = ft_predict_proba(model, bundle["Xte_cat"], bundle["Xte_num"])
    else:
        continue
    test_pred_df[f"proba_{model_name}"] = proba

test_pred_df.to_csv(PRED_PATH, index=True)
print(f"[INFO] Saved test predictions to {PRED_PATH}")
display(test_pred_df.head())

[PREDICT] LogisticRegression
[PREDICT] RandomForest
[PREDICT] XGBoost
[PREDICT] LightGBM
[PREDICT] CatBoost
[PREDICT] TabNet
[PREDICT] FTTransformer
[INFO] Saved test predictions to artifacts/test_predictions_all_models.csv

,target,proba_LogisticRegression,proba_RandomForest,proba_XGBoost,proba_LightGBM,proba_CatBoost,proba_TabNet,proba_FTTransformer
235465,0,0.26,0.44,0.02,0.02,0.02,0.02,0.03
292820,0,0.49,0.50,0.05,0.04,0.04,0.04,0.03
434381,0,0.38,0.53,0.03,0.03,0.03,0.05,0.05
472579,0,0.44,0.48,0.03,0.03,0.03,0.02,0.03
238219,0,0.62,0.56,0.06,0.05,0.05,0.08,0.04

In [ ]:
# ===== 4.3 Preprocessing Cost and Robustness Analysis =====
preprocess_notes = pd.DataFrame([
    {"model": "LogisticRegression", "missing_handling": "median/mode imputation", "categorical": "one-hot", "effort_level": "high"},
    {"model": "RandomForest", "missing_handling": "median/mode imputation", "categorical": "ordinal encoding", "effort_level": "medium"},
    {"model": "XGBoost", "missing_handling": "native missing + imputation in this pipeline", "categorical": "ordinal encoding", "effort_level": "medium"},
    {"model": "LightGBM", "missing_handling": "native missing + imputation in this pipeline", "categorical": "ordinal encoding", "effort_level": "medium"},
    {"model": "CatBoost", "missing_handling": "native support", "categorical": "native categorical", "effort_level": "low"},
    {"model": "TabNet", "missing_handling": "numeric imputation + missing category token", "categorical": "learned embeddings", "effort_level": "high"},
    {"model": "FTTransformer", "missing_handling": "numeric imputation + missing category token", "categorical": "learned embeddings", "effort_level": "high"},
])

display(preprocess_notes)



if not summary_df.empty:
    stability = summary_df[["model", "auc_roc_std", "f1_std", "accuracy_std"]].sort_values("auc_roc_std")
    print("[INFO] Lower std => more stable across seeds")
    display(stability)

,model,missing_handling,categorical,effort_level
0,LogisticRegression,median/mode imputation,one-hot,high
1,RandomForest,median/mode imputation,ordinal encoding,medium
2,XGBoost,native missing + imputation in this pipeline,ordinal encoding,medium
3,LightGBM,native missing + imputation in this pipeline,ordinal encoding,medium
4,CatBoost,native support,native categorical,low
5,TabNet,numeric imputation + missing category token,learned embeddings,high
6,FTTransformer,numeric imputation + missing category token,learned embeddings,high

[INFO] Lower std => more stable across seeds

                model  auc_roc_std    f1_std  accuracy_std
1             XGBoost     3.35e-04  0.00e+00      0.00e+00
0            CatBoost     1.08e-03  2.17e-04      0.00e+00
4        RandomForest     1.50e-03  1.75e-03      5.31e-02
2            LightGBM     1.59e-03  0.00e+00      3.96e-06
6       FTTransformer     1.71e-03  0.00e+00      0.00e+00
3  LogisticRegression     1.92e-03  6.52e-04      6.99e-04
5              TabNet     1.11e-02  0.00e+00      0.00e+00

In [ ]:
# ===== 4.4 Feature Importance Comparison (Unified Permutation Importance on Validation Subsample) =====
def predict_proba_on_raw(model_name, Xraw):
    model = best_models[model_name]
    if model_name in ["LogisticRegression", "RandomForest", "XGBoost", "LightGBM"]:
        prep = best_preprocessors[model_name]
        return model.predict_proba(prep.transform(Xraw))[:, 1]

    if model_name == "CatBoost":
        Xt = Xraw.copy()
        for c in cat_cols:
            Xt[c] = Xt[c].astype("string").fillna("MISSING")
        return model.predict_proba(Xt)[:, 1]

    if model_name == "TabNet":
        bundle = best_preprocessors[model_name]
        b = prepare_deep_inputs(X_train, Xraw, Xraw)
        X_tab = np.hstack([b["Xva_num"], b["Xva_cat"]]).astype(np.float32)
        return model.predict_proba(X_tab)[:, 1]
    if model_name == "FTTransformer":
        b = prepare_deep_inputs(X_train, Xraw, Xraw)
        return ft_predict_proba(model, b["Xva_cat"], b["Xva_num"])
    raise ValueError(model_name)



def permutation_importance_auc(model_name, Xraw, ytrue, max_features=None, seed=42):
    rng = np.random.default_rng(seed)
    base_pred = predict_proba_on_raw(model_name, Xraw)
    base_auc = roc_auc_score(ytrue, base_pred)
    cols = list(Xraw.columns)
    if max_features is not None and len(cols) > max_features:
        cols = cols[:max_features]

    imps = []

    for c in cols:
        Xp = Xraw.copy()
        Xp[c] = rng.permutation(Xp[c].values)
        auc_p = roc_auc_score(ytrue, predict_proba_on_raw(model_name, Xp))
        imps.append((c, base_auc - auc_p))
    imp_df = pd.DataFrame(imps, columns=["feature", "importance_drop_auc"]).sort_values(
        "importance_drop_auc", ascending=False
    )

    return base_auc, imp_df

X_val_for_imp = X_valid.sample(min(len(X_valid), 6000), random_state=SEEDS[0])
y_val_for_imp = y_valid.loc[X_val_for_imp.index]

importance_tables = {}

for model_name in all_results.keys():
    print(f"\n[IMP] {model_name}")
    base_auc, imp_df = permutation_importance_auc(model_name, X_val_for_imp, y_val_for_imp, max_features=None, seed=SEEDS[0])
    importance_tables[model_name] = imp_df
    print(f"[IMP] base_auc={base_auc:.6f}")
    display(imp_df.head(15))

[IMP] LogisticRegression
[IMP] base_auc=0.638093

          feature  importance_drop_auc
5   ps_ind_05_cat             2.64e-02
19      ps_reg_01             1.10e-02
35      ps_car_13             1.09e-02
32  ps_car_11_cat             8.19e-03
22  ps_car_01_cat             7.15e-03
8   ps_ind_08_bin             7.11e-03
34      ps_car_12             6.68e-03
17  ps_ind_17_bin             5.42e-03
25  ps_car_04_cat             5.37e-03
28  ps_car_07_cat             4.52e-03
7   ps_ind_07_bin             2.62e-03
51     ps_calc_14             2.04e-03
15      ps_ind_15             2.04e-03
30  ps_car_09_cat             1.96e-03
21      ps_reg_03             1.62e-03

[IMP] RandomForest
[IMP] base_auc=0.635232

          feature  importance_drop_auc
5   ps_ind_05_cat             1.26e-02
21      ps_reg_03             8.96e-03
20      ps_reg_02             8.35e-03
6   ps_ind_06_bin             7.71e-03
35      ps_car_13             7.29e-03
22  ps_car_01_cat             6.99e-03
19      ps_reg_01             6.56e-03
17  ps_ind_17_bin             6.13e-03
25  ps_car_04_cat             4.16e-03
3       ps_ind_03             3.92e-03
15      ps_ind_15             2.63e-03
28  ps_car_07_cat             2.00e-03
9   ps_ind_09_bin             1.83e-03
30  ps_car_09_cat             1.43e-03
8   ps_ind_08_bin             1.34e-03

[IMP] XGBoost
[IMP] base_auc=0.649442

          feature  importance_drop_auc
35      ps_car_13             2.42e-02
5   ps_ind_05_cat             2.06e-02
3       ps_ind_03             1.39e-02
19      ps_reg_01             9.33e-03
20      ps_reg_02             8.21e-03
22  ps_car_01_cat             7.38e-03
1       ps_ind_01             7.19e-03
17  ps_ind_17_bin             6.74e-03
28  ps_car_07_cat             6.25e-03
6   ps_ind_06_bin             5.32e-03
37      ps_car_15             5.14e-03
34      ps_car_12             4.87e-03
21      ps_reg_03             4.77e-03
32  ps_car_11_cat             4.33e-03
8   ps_ind_08_bin             3.35e-03

[IMP] LightGBM
[IMP] base_auc=0.647498

          feature  importance_drop_auc
35      ps_car_13             1.80e-02
5   ps_ind_05_cat             1.73e-02
3       ps_ind_03             1.44e-02
19      ps_reg_01             7.82e-03
28  ps_car_07_cat             7.51e-03
17  ps_ind_17_bin             6.97e-03
21      ps_reg_03             6.93e-03
6   ps_ind_06_bin             6.66e-03
37      ps_car_15             6.52e-03
22  ps_car_01_cat             6.22e-03
15      ps_ind_15             5.87e-03
1       ps_ind_01             5.66e-03
20      ps_reg_02             5.23e-03
32  ps_car_11_cat             4.53e-03
9   ps_ind_09_bin             3.51e-03

[IMP] CatBoost
[IMP] base_auc=0.650043

          feature  importance_drop_auc
5   ps_ind_05_cat             1.96e-02
17  ps_ind_17_bin             9.47e-03
21      ps_reg_03             9.33e-03
3       ps_ind_03             8.79e-03
15      ps_ind_15             5.71e-03
35      ps_car_13             5.58e-03
6   ps_ind_06_bin             4.96e-03
20      ps_reg_02             4.77e-03
28  ps_car_07_cat             4.39e-03
24  ps_car_03_cat             3.68e-03
19      ps_reg_01             3.59e-03
25  ps_car_04_cat             3.36e-03
37      ps_car_15             3.23e-03
51     ps_calc_14             2.72e-03
34      ps_car_12             2.44e-03

[IMP] TabNet
[IMP] base_auc=0.633347

          feature  importance_drop_auc
5   ps_ind_05_cat             2.46e-02
35      ps_car_13             1.82e-02
21      ps_reg_03             1.54e-02
19      ps_reg_01             1.31e-02
28  ps_car_07_cat             8.76e-03
4   ps_ind_04_cat             6.28e-03
30  ps_car_09_cat             4.97e-03
8   ps_ind_08_bin             4.79e-03
20      ps_reg_02             4.64e-03
9   ps_ind_09_bin             4.48e-03
3       ps_ind_03             3.34e-03
38     ps_calc_01             3.13e-03
32  ps_car_11_cat             2.59e-03
39     ps_calc_02             2.06e-03
17  ps_ind_17_bin             2.03e-03

[IMP] FTTransformer
[IMP] base_auc=0.579587

          feature  importance_drop_auc
28  ps_car_07_cat             9.94e-03
17  ps_ind_17_bin             8.86e-03
5   ps_ind_05_cat             7.92e-03
25  ps_car_04_cat             5.37e-03
27  ps_car_06_cat             4.55e-03
6   ps_ind_06_bin             4.39e-03
24  ps_car_03_cat             3.21e-03
2   ps_ind_02_cat             2.88e-03
32  ps_car_11_cat             1.17e-03
49     ps_calc_12             8.08e-04
26  ps_car_05_cat             7.44e-04
46     ps_calc_09             7.11e-04
3       ps_ind_03             4.18e-04
50     ps_calc_13             1.78e-04
41     ps_calc_04             1.07e-04

In [ ]:
# ===== 4.5 Auto-Generate Conclusion Draft (Report-Ready) =====
if summary_df.empty:
    print("[WARN] summary_df is empty. Run training cells first.")
else:
    best_row = summary_df.iloc[0]
    fastest_row = summary_df.sort_values("infer_ms_per_sample_mean", ascending=True).iloc[0]
    smallest_row = summary_df.sort_values("model_size_mb_mean", ascending=True).iloc[0]
    most_stable_row = summary_df.sort_values("auc_roc_std", ascending=True).iloc[0]

    print("===== Practical Verdict Draft =====")
    print(f"1) Overall best predictive AUC: {best_row['model']} | AUC={best_row['auc_roc_mean']:.5f}卤{best_row['auc_roc_std']:.5f}")
    print(f"2) Fastest inference: {fastest_row['model']} | {fastest_row['infer_ms_per_sample_mean']:.6f} ms/sample")
    print(f"3) Smallest model size: {smallest_row['model']} | {smallest_row['model_size_mb_mean']:.3f} MB")
    print(f"4) Most stable across seeds: {most_stable_row['model']} | AUC std={most_stable_row['auc_roc_std']:.5f}")

===== Practical Verdict Draft =====
1) Overall best predictive AUC: CatBoost | AUC=0.63666卤0.00108
2) Fastest inference: LogisticRegression | 0.006752 ms/sample
3) Smallest model size: LogisticRegression | 0.011 MB
4) Most stable across seeds: XGBoost | AUC std=0.00033

## 5) Run Recommendations



- Production mode is enabled: `FAST_MODE=False`, suitable for the final report.

- GPU acceleration is enabled where supported (XGBoost, LightGBM, CatBoost, TabNet, FT-Transformer).

- Logistic Regression and Random Forest use sklearn implementations and remain CPU-trained by default.

- It is recommended to run up to Stage 2 first to confirm data and splits are correct.

- All key outputs are written to `artifacts/` using `` file names:

  - `fixed_split_indices.json`

  - `model_summary.csv`

  - `test_predictions_all_models.csv`

- CatBoost training logs are stored in `catboost_info/` to avoid conflicts with other runs.



### Checkpoint Resume Notes (New)



- Training checkpoints are automatically saved to `artifacts/checkpoints/`.

- Checkpoint granularity is model + seed: if interrupted, rerunning the training cell skips completed seeds and continues the remaining ones.

- If all seeds for a model are complete, rerun will directly load the best-seed checkpoint and proceed to summary/prediction.

- To force full retraining of a model, delete its checkpoint subfolder (for example `artifacts/checkpoints/TabNet_seed123/`).